act_code: '5356'
requisite: Решение маслихата Костанайской области от 15 декабря 1999 года. Зарегистрировано Управлением юстиции Костанайской области 31 января 2000 года № 174. Срок действия решения - до 1 января 2001 года
title:
  rus: Об областном бюджете Костанайской области на 2000 год
  kaz: 2000 жылға арналған Қостанай облысының облыстык бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-15
approved_by:
- '162000000002'
version_date:
  kaz: 1999-12-15
  rus: 1999-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/5356/kaz/15.12.1999
  rus: https://zan.gov.kz/client/#!/doc/5356/rus/15.12.1999
