act_code: '220402'
requisite: Решение маслихата города Рудного Костанайской области от 26 декабря 2025 года № 257
title:
  rus: О городском бюджете города Рудного на 2026-2028 годы
  kaz: Рудный қаласының 2026-2028 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '162021000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/220402/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220402/rus/26.12.2025
