act_code: '225050'
requisite: Решение маслихата Узункольского района Костанайской области от 8 мая 2026 года № 226
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по Узункольскому району
  kaz: Ұзынкөл ауданы бойынша шетелдіктер үшін 2026 жылға туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-08
approved_by:
- '162017000002'
version_date:
  kaz: 2026-05-08
  rus: 2026-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/225050/kaz/08.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225050/rus/08.05.2026
