act_code: '78945'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 19 марта 2014 года № 223. Зарегистрировано Департаментом юстиции Костанайской области 17 апреля 2014 года № 4603. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 12 февраля 2015 года № 289
title:
  rus: О корректировке базовых налоговых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-19
approved_by:
- '162013000002'
version_date:
  kaz: 2014-03-19
  rus: 2014-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/78945/kaz/19.03.2014
  rus: https://zan.gov.kz/client/#!/doc/78945/rus/19.03.2014
repealed_on: 2015-02-12
repealed_by:
  code: '78945'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 19 марта 2014 года № 223. Зарегистрировано Департаментом юстиции Костанайской области 17 апреля 2014 года № 4603. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 12 февраля 2015 года № 289
  title:
    rus: О корректировке базовых налоговых ставок земельного налога
    kaz: Жер салығының базалық ставкаларын түзету туралы
  link: https://zan.gov.kz/client/#!/doc/78945/rus
