act_code: '138900'
requisite: Решение маслихата Денисовского района Костанайской области от 14 января 2020 года № 5. Зарегистрировано Департаментом юстиции Костанайской области 20 января 2020 года № 8906
title:
  rus: О бюджетах сел и сельских округов Денисовского района на 2020-2022 годы
  kaz: Денисов ауданы ауылдарының және ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-14
approved_by:
- '162006000002'
version_date:
  kaz: 2020-07-15
  rus: 2020-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/138900/kaz/15.07.2020
  rus: https://zan.gov.kz/client/#!/doc/138900/rus/15.07.2020
caused_by:
  code: '145146'
  requisite: Решение маслихата Денисовского района Костанайской области от 15 июля 2020 года № 57. Зарегистрировано Департаментом юстиции Костанайской области 28 июля 2020 года № 9346
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 14 января 2020 года № 5 «О бюджетах сел и сельских округов Денисовского района на 2020-2022 годы»
    kaz: Мәслихаттың 2020 жылғы 14 қаңтардағы № 5 «Денисов ауданы 2020-2022 жылдарға арналған ауылдарының және ауылдық округтерінің бюджеттері туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145146/rus
