act_code: '102786'
requisite: Решение маслихата Амангельдинского района Костанайской области от 19 апреля 2016 года № 14. Зарегистрировано Департаментом юстиции Костанайской области 17 мая 2016 года № 6375. Утратило силу решением маслихата Амангельдинского района Костанайской области от 8 июня 2018 года № 221
title:
  rus: О повышении базовых ставок земельного налога и единого земельного налога на неиспользуемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-19
approved_by:
- '162004000002'
version_date:
  kaz: 2016-04-19
  rus: 2016-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/102786/kaz/19.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102786/rus/19.04.2016
