act_code: '188162'
requisite: Решение акима села Бестобе Камыстинского района Костанайской области от 7 ноября 2023 года № 10
title:
  rus: Об установлении акционерному обществу «Казахтелеком» право ограниченного целевого землепользования (публичный сервитут) на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне шектеулі нысаналы жер пайдалану құқығын (жария сервитут) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-07
approved_by:
- '162009003002'
version_date:
  kaz: 2024-03-01
  rus: 2024-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/188162/kaz/01.03.2024
  rus: https://zan.gov.kz/client/#!/doc/188162/rus/01.03.2024
caused_by:
  code: '194089'
  requisite: Решение акима села Бестобе Камыстинского района Костанайской области от 1 марта 2024 года № 3
  title:
    rus: О внесении изменения в решение акима села Бестобе от 7 ноября 2023 года № 10 «Об установлении акционерному обществу «Казахтелеком» право ограниченного целевого землепользования (публичный сервитут) на земельный участок»
    kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне шектеулі нысаналы жер пайдалану құқығын (жария сервитут) белгілеу туралы Бестөбе ауылы әкімінің 2023 жылғы 7 қарашадағы № 10 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194089/rus
