act_code: '224685'
requisite: Решение акима Денисовского района Костанайской области от 28 апреля 2026 года № 4
title:
  rus: Об отмене решения акима Денисовского района Костанайской области от 2 июля 2024 года № 4 «Об объявлении чрезвычайной ситуации природного характера местного масштаба»
  kaz: Қостанай облысы Денисов ауданы әкімінің 2024 жылғы 2 шілдедегі № 4 «Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдай жариялау туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-28
approved_by:
- '162006000003'
version_date:
  kaz: 2026-04-28
  rus: 2026-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/224685/kaz/28.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224685/rus/28.04.2026
