act_code: '182735'
requisite: Решение маслихата Костанайской области от 7 июня 2023 года № 28
title:
  rus: Об утверждении Правил создания, содержания и защиты зеленых насаждений населенных пунктов Костанайской области
  kaz: Қостанай облысы елді мекендерінің жасыл екпелерін жасау, күтіп-баптау және қорғаудың қағидаларын бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-06-07
approved_by:
- '162000000002'
version_date:
  kaz: 2023-06-07
  rus: 2023-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/182735/kaz/07.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182735/rus/07.06.2023
