act_code: '145669'
requisite: Решение маслихата города Аркалыка Костанайской области от 18 августа 2020 года № 337. Зарегистрировано Департаментом юстиции Костанайской области 21 августа 2020 года № 9399. Утратило силу решением маслихата города Аркалыка Костанайской области от 27 декабря 2023 года № 85 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-08-18
approved_by:
- '162019000002'
version_date:
  kaz: 2023-04-21
  rus: 2023-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/145669/kaz/21.04.2023
  rus: https://zan.gov.kz/client/#!/doc/145669/rus/21.04.2023
caused_by:
  code: '180845'
  requisite: Решение маслихата города Аркалыка Костанайской области от 21 апреля 2023 года № 10. Зарегистрировано Департаментом юстиции Костанайской области 5 мая 2023 года № 9998. Утратило силу решением маслихата города Аркалыка Костанайской области от 27 декабря 2023 года № 85 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 18 августа 2020 года № 337 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2020 жылғы 18 тамыздағы № 337 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180845/rus
