act_code: '92617'
requisite: Решение маслихата Амангельдинского района Костанайской области от 8 июля 2015 года № 329. Зарегистрировано Департаментом юстиции Костанайской области 6 августа 2015 года № 5785. Утратило силу решением маслихата Амангельдинского района Костанайской области от 11 мая  2016 года № 27
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Амангельдинского районного маслихата"
  kaz: '"Амангелді аудандық мәслихатының аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-07-08
approved_by:
- '162004000002'
version_date:
  kaz: 2016-03-18
  rus: 2016-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/92617/kaz/18.03.2016
  rus: https://zan.gov.kz/client/#!/doc/92617/rus/18.03.2016
caused_by:
  code: '100728'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 18 марта 2016 года № 404. Зарегистрировано Департаментом юстиции Костанайской области 28 марта 2016 года № 6236. Утратило силу решением маслихата Амангельдинского района Костанайской области от 11 мая  2016 года № 27
  title:
    rus: О внесении изменения в решение маслихата от 8 июля 2015 года № 329 "Об утверждении Положения государственного учреждения "Аппарат Амангельдинского районного маслихата"
    kaz: Мәслихаттың 2015 жылғы 8 шілдедегі № 329 "Амангелді аудандық мәслихатының аппараты" мемлекеттік мекемесінің ережесін бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100728/rus
