act_code: '127314'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 24 декабря 2018 года № 240. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2018 года № 8188
title:
  rus: О районном бюджете Мендыкаринского района на 2019-2021 годы
  kaz: Меңдіқара ауданының 2019 - 2021 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '162013000002'
version_date:
  kaz: 2019-11-14
  rus: 2019-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/127314/kaz/14.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127314/rus/14.11.2019
caused_by:
  code: '136101'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 14 ноября 2019 года № 321. Зарегистрировано Департаментом юстиции Костанайской области 19 ноября 2019 года № 8759
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2018 года № 240 «О районном бюджете Мендыкаринского района на 2019 - 2021 годы»
    kaz: Мәслихаттың 2018 жылғы 24 желтоқсандағы № 240 «Меңдіқара ауданының 2019 - 2021 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136101/rus
