act_code: '196121'
requisite: Решение маслихата Карасуского района Костанайской области от 19 апреля 2024 года № 128. Зарегистрировано в Департаменте юстиции Костанайской области 26 апреля 2024 года № 10183-10
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Карасуском районе
  kaz: Қарасу ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-19
approved_by:
- '162011000002'
version_date:
  kaz: 2025-01-22
  rus: 2025-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/196121/kaz/22.01.2025
  rus: https://zan.gov.kz/client/#!/doc/196121/rus/22.01.2025
caused_by:
  code: '206876'
  requisite: Решение маслихата Карасуского района Костанайской области от 22 января 2025 года № 200. Зарегистрировано в Департаменте юстиции Костанайской области 31 января 2025 года № 10366-10
  title:
    rus: О внесении изменения в решение маслихата от 19 апреля 2024 года № 128 «Об определении размера и порядка оказания жилищной помощи в Карасуском районе»
    kaz: Мәслихаттың 2024 жылғы 19 сәуірдегі № 128 «Қарасу ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206876/rus
