act_code: '196017'
requisite: Решение маслихата города Аркалыка Костанайской области от 22 апреля 2024 года № 105. Отменено решением маслихата города Аркалыка Костанайской области от 5 декабря 2025 года № 194 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Аркалыкского городского маслихата»
  kaz: «Арқалық қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2024-04-22
approved_by:
- '162019000002'
version_date:
  kaz: 2024-04-22
  rus: 2024-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/196017/kaz/22.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196017/rus/22.04.2024
