act_code: '7807'
requisite: Решение акима Костанайской области от 21 декабря 2000 года № 240. Зарегистрировано Управлением юстиции Костанайской области 26 декабря 2000 года № 544.  Утратило силу решением акима Костанайской области от 13 декабря 2004 года № 55
title:
  rus: «О реализации постановлений Правительства Республики Казахстан от 14 октября 2000 года № 1527 «О некоторых вопросах дорожной отрасли» и от 5 декабря 2000 года № 1809 «Об утверждении правил классификации и перечня автомобильных дорог общего пользования республиканского значения Республики Казахстан»
  kaz: Қазақстан Республикасы Үкіметінің "Жол саласының кейбір мәселелері туралы" 2000 жылғы 14 қазандағы № 1527 және "Қазақстан Республикасының республикалық маңыздағы жалпы пайдаланымдағы автомобиль жолдарын жіктеу ережесін және тізбесін бекіту туралы" 2000 жылғы 5 желтоқсандағы № 1809 қаулыларын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-21
approved_by:
- '162000000003'
version_date:
  kaz: 2000-12-21
  rus: 2000-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/7807/kaz/21.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7807/rus/21.12.2000
