act_code: '108835'
requisite: Решение маслихата Аулиекольского района Костанайской области от 22 декабря 2016 года № 76. Зарегистрировано Департаментом юстиции Костанайской области 5 января 2017 года № 6776
title:
  rus: О бюджете Аулиекольского района на 2017-2019 годы
  kaz: Әулиекөл ауданының 2017-2019 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-22
approved_by:
- '162005000002'
version_date:
  kaz: 2017-10-13
  rus: 2017-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/108835/kaz/13.10.2017
  rus: https://zan.gov.kz/client/#!/doc/108835/rus/13.10.2017
caused_by:
  code: '115356'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 13 октября 2017 года № 146. Зарегистрировано Департаментом юстиции Костанайской области 20 октября 2017 года № 7257
  title:
    rus: О внесении изменений  в решение маслихата от 22 декабря 2016 года  № 76  «О бюджете Аулиекольского района на 2017-2019 годы»
    kaz: Мәслихаттың 2016 жылғы 22 желтоқсандағы № 76 «Әулиекөл ауданының 2017-2019 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/115356/rus
