act_code: '50653'
requisite: Қостанай облысы Жангелдин ауданы әкімінің 2010 жылғы 13 қаңтардағы № 1 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2010 жылғы 10 ақпанда № 9-9-114 тіркелді
title:
  rus: Қазақстан Республикасының тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды Жангелдин ауданының шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
  kaz: Қазақстан Республикасының тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды Жангелдин ауданының шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-13
approved_by:
- '162007000001'
version_date:
  kaz: 2010-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/50653/kaz/13.01.2010
