act_code: '177032'
requisite: Решение маслихата Костанайского района Костанайской области от 6 января 2023 года № 268
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат Костанайского районного маслихата»
  kaz: «Қостанай аудандық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-01-06
approved_by:
- '162012000002'
version_date:
  kaz: 2026-08-14
  rus: 2026-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/177032/kaz/14.08.2026
  rus: https://zan.gov.kz/client/#!/doc/177032/rus/14.08.2026
caused_by:
  code: '228942'
  requisite: Решение Костанайского районного маслихата Костанайской области от 14 августа 2026 года № 389
  title:
    rus: О внесении изменения в решение маслихата от 6 января 2023 года № 268 «Об утверждении Положения о государственном учреждении «Аппарат Костанайского районного маслихата»
    kaz: Мәслихаттың 2023 жылғы 6 қаңтардағы № 268 «Қостанай аудандық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228942/rus
