act_code: '223496'
requisite: Решение маслихата Карабалыкского района Костанайской области от 27 марта 2026 года № 252
title:
  rus: О предоставлении в 2026 году социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселка и сельских округов прибывшим для работы и проживания в сельские населенные пункты Карабалыкского района
  kaz: Қарабалық ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер және ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2026 жылы әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-27
approved_by:
- '162010000002'
version_date:
  kaz: 2026-03-27
  rus: 2026-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/223496/kaz/27.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223496/rus/27.03.2026
