act_code: '549'
requisite: Решение акима Костанайской области от 22 октября 1997 года № 173. Зарегистрировано Управлением юстиции Костанайской области 10 апреля 1998 года № 6. Утратило силу решением акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: О дополнительных мерах по реализации региональной программы поддержки и развития малого предпринимательства на 1997-1998 годы
  kaz: 1997-1998 жылдарға арналған шағын кәсіпкерлікті қолдау мен дамытудың аймақтық бағдарламасын жүзеге асыру жөніндегі қосымша шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-10-21
approved_by:
- '162000000003'
version_date:
  kaz: 1997-10-21
  rus: 1997-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/549/kaz/21.10.1997
  rus: https://zan.gov.kz/client/#!/doc/549/rus/21.10.1997
