act_code: '45058'
requisite: Қостанай облысы Науырзым ауданы мәслихатының 2009 жылғы 12 ақпандағы № 169 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2009 жылғы 24 наурызда № 9-16-89 тіркелді. Күші жойылды - Қостанай облысы Науырзым ауданы мәслихатының 2010 жылғы 22 қазандағы № 319 шешімімен
title:
  rus: Науырзым ауданының селолық округтері аймақтарында иттер мен мысықтарды ұстау қағидасы туралы
  kaz: Науырзым ауданының селолық округтері аймақтарында иттер мен мысықтарды ұстау қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-02-12
approved_by:
- '162014000002'
version_date:
  kaz: 2009-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/45058/kaz/12.02.2009
