act_code: '227570'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 9 июля 2026 года № 280
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-07-09
approved_by:
- '162013000002'
version_date:
  kaz: 2026-07-09
  rus: 2026-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/227570/kaz/09.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227570/rus/09.07.2026
