act_code: '12587'
requisite: Решение маслихата Костанайской области от 24 мая 2002 года № 209. Зарегистрировано Управлением юстиции Костанайской области 19 июня 2002 года № 1594. Срок действия решения - до 1 января 2003 года
title:
  rus: О ходе реализации региональной программы борьбы с преступностью в Костанайской области на 2001-2002 годы
  kaz: Қостанай облысында қылмысқа қарсы күрестің 2001-2002 жылдарға арналған аймақтық бағдарламасын жүзеге асырудың барысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-23
approved_by:
- '162000000002'
version_date:
  kaz: 2002-05-23
  rus: 2002-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/12587/kaz/23.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12587/rus/23.05.2002
