act_code: '157803'
requisite: Решение акима Диевского сельского округа Аулиекольского района Костанайской области от 5 августа 2021 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 августа 2021 года № 23960
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-08-05
approved_by:
- '162005002002'
version_date:
  kaz: 2021-08-05
  rus: 2021-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/157803/kaz/05.08.2021
  rus: https://zan.gov.kz/client/#!/doc/157803/rus/05.08.2021
