act_code: '2406'
requisite: Решение акима Костанайской области от 11 ноября 1998 года № 114. Зарегистрировано Управлением юстиции Костанайской области 23 ноября 1998 года № 37. Утратило силу решением акима Костанайской области от 19 ноября 2004 года № 50
title:
  rus: О создании государственной областной инспекции по контролю за использованием и охраной земель
  kaz: Жерді  пайдалану және қорғауға бақылау жасау жөніндегі мемлекеттік облыстық инспекция құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-11-11
approved_by:
- '162000000003'
version_date:
  kaz: 1998-11-11
  rus: 1998-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/2406/kaz/11.11.1998
  rus: https://zan.gov.kz/client/#!/doc/2406/rus/11.11.1998
