act_code: '149674'
requisite: Решение акима Калининского сельского округа района Беимбета Майлина Костанайской области от 9 декабря 2020 года № 7. Зарегистрировано Департаментом юстиции Костанайской области 11 декабря 2020 года № 9629
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-09
approved_by:
- '162016005002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/149674/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/149674/rus/09.12.2020
