act_code: '121945'
requisite: Решение маслихата Наурзумского района Костанайской области от 21 мая 2018 года № 189. Зарегистрировано Департаментом юстиции Костанайской области 24 мая 2018 года № 7788. Утратило силу решением маслихата Наурзумского района Костанайской области от 20 января 2020 года № 331 (вводится в действие для сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Карамендинского сельского округа Наурзумского района Костанайской области
  kaz: Қостанай облысы Науырзым ауданы Қарамеңді ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-21
approved_by:
- '162014000002'
version_date:
  kaz: 2018-05-21
  rus: 2018-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/121945/kaz/21.05.2018
  rus: https://zan.gov.kz/client/#!/doc/121945/rus/21.05.2018
