act_code: '177881'
requisite: Решение маслихата Аулиекольского района Костанайской области от 29 декабря 2022 года № 177
title:
  rus: О бюджете Аманкарагайского сельского округа Аулиекольского района на 2023-2025 годы
  kaz: Әулиекөл ауданы Аманқарағай ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162005000002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/177881/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177881/rus/07.12.2023
caused_by:
  code: '189791'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 7 декабря 2023 года № 104
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2022 года № 177 «О бюджете Аманкарагайского сельского округа Аулиекольского района на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 29 желтоқсандағы № 177 «Әулиекөл ауданы Аманқарағай ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189791/rus
