act_code: '164370'
requisite: Решение маслихата Карасуского района Костанайской области от 4 февраля 2022 года № 99. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 февраля 2022 года № 26758
title:
  rus: О признании утратившим силу решения Карасуского районного маслихата от 14 марта 2018 года № 211 «О повышении базовых ставок земельного налога»
  kaz: Қарасу аудандық мәслихаттың 2018 жылғы 14 наурыздағы № 211 «Жер салығының базалық мөлшерлемелерін арттыру туралы» шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-02-04
approved_by:
- '162011000002'
version_date:
  kaz: 2022-02-04
  rus: 2022-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/164370/kaz/04.02.2022
  rus: https://zan.gov.kz/client/#!/doc/164370/rus/04.02.2022
