act_code: '221367'
requisite: Решение акима Тогузакского сельского округа Карабалыкского района Костанайской области от 14 января 2026 года № 2
title:
  rus: О предоставлении товариществу с ограниченной ответственностью «ЭПК-forfait» права ограниченного целевого землепользования (публичный сервитут) для обслуживания и эксплуатации воздушных линии электропередач
  kaz: «ЭПК-forfait» жауапкершілігі шектеулі серіктестігіне әуе электр беру желілеріне қызмет көрсету және пайдалану үшін шектеулі нысаналы жер пайдалану құқығын (қоғамдық сервитут) беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-14
approved_by:
- '162010006002'
version_date:
  kaz: 2026-01-14
  rus: 2026-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/221367/kaz/14.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221367/rus/14.01.2026
