act_code: '127484'
requisite: Решение маслихата города Аркалыка Костанайской области от 25 декабря 2018 года № 223. Зарегистрировано Департаментом юстиции Костанайской области 26 декабря 2018 года № 8191
title:
  rus: О бюджете села Родина города Аркалыка на 2019 - 2021 годы
  kaz: Арқалық қаласы Родина ауылының 2019 - 2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '162019000002'
version_date:
  kaz: 2019-10-11
  rus: 2019-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/127484/kaz/11.10.2019
  rus: https://zan.gov.kz/client/#!/doc/127484/rus/11.10.2019
caused_by:
  code: '135333'
  requisite: Решение маслихата города Аркалыка Костанайской области от 11 октября 2019 года № 272. Зарегистрировано Департаментом юстиции Костанайской области 16 октября 2019 года № 8706
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 25 декабря 2018 года № 223 «О бюджете села Родина города Аркалыка на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 25 желтоқсандағы № 223 «Арқалық қаласы Родина ауылының 2019–2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135333/rus
