act_code: '136382'
requisite: Решение акима села Жанакала города Аркалыка Костанайской области от 14 ноября 2019 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 27 ноября 2019 года № 8782
title:
  rus: О снятии ограничительных мероприятий в селе Жанакала города Аркалыка
  kaz: Арқалық қаласы Жаңақала ауылында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-14
approved_by:
- '162019009001'
version_date:
  kaz: 2019-11-14
  rus: 2019-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/136382/kaz/14.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136382/rus/14.11.2019
