act_code: '201445'
requisite: Решение маслихата Наурзумского района Костанайской области от 24 сентября 2024 года № 138. Зарегистрировано в Департаменте юстиции Костанайской области 3 октября 2024 года № 10273-10
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Караменды и населенных пунктов Наурзумского района
  kaz: Қарамеңді ауылы және Науырзым ауданы елді мекендерінің жерлерін аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2024-09-24
approved_by:
- '162014000002'
version_date:
  kaz: 2024-09-24
  rus: 2024-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/201445/kaz/24.09.2024
  rus: https://zan.gov.kz/client/#!/doc/201445/rus/24.09.2024
