act_code: '227478'
requisite: Решение акима Айдарлинского сельского округа Карасуского района Костанайской области от 7 июля 2026 года № 3
title:
  rus: Об установлении публичного сервитута частной компании «Kazakhstan JinijangCo., Ltd»
  kaz: «Kazakhstan JinijangCo., Ltd» жеке компаниясына жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-07
approved_by:
- '162011001002'
version_date:
  kaz: 2026-07-07
  rus: 2026-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/227478/kaz/07.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227478/rus/07.07.2026
