act_code: '97011'
requisite: Решение маслихата Карабалыкского района Костанайской области от 24 декабря 2015 года № 417. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2015 года № 6100
title:
  rus: О районном бюджете Карабалыкского района на 2016-2018 годы
  kaz: Қарабалық ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '162010000002'
version_date:
  kaz: 2016-04-11
  rus: 2016-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/97011/kaz/11.04.2016
  rus: https://zan.gov.kz/client/#!/doc/97011/rus/11.04.2016
caused_by:
  code: '101278'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 11 апреля 2016 года № 17. Зарегистрировано Департаментом юстиции Костанайской области 12 апреля 2016 года № 6282
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2015 года № 417 "О районном бюджете Карабалыкского района на 2016-2018 годы"
    kaz: Мәслихаттың 2015 жылғы 24 желтоқсандағы № 417 "Қарабалық ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101278/rus
