act_code: '97011'
requisite: Решение маслихата Карабалыкского района Костанайской области от 24 декабря 2015 года № 417. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2015 года № 6100
title:
  rus: О районном бюджете Карабалыкского района на 2016-2018 годы
  kaz: Қарабалық ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '162010000002'
version_date:
  kaz: 2016-12-09
  rus: 2016-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/97011/kaz/09.12.2016
  rus: https://zan.gov.kz/client/#!/doc/97011/rus/09.12.2016
caused_by:
  code: '108492'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 9 декабря 2016 года № 87. Зарегистрировано Департаментом юстиции Костанайской области 14 декабря 2016 года № 6739
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2015 года № 417 "О районном бюджете Карабалыкского района на 2016-2018 годы"
    kaz: Мәслихаттың 2015 жылғы 24 желтоқсандағы № 417 "Қарабалық ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108492/rus
