act_code: '13554'
requisite: Решение маслихата Костанайской области от 18 октября 2002 года № 226. Зарегистрировано Управлением юстиции Костанайской области 5 ноября 2002 года № 1856. Утратило силу решением маслихата Костанайской области от 13 июля 2007 года № 470
title:
  rus: О повышении окладов и тарифных ставок специалистам здравоохранения, социального обеспечения, образования, здравоохранения, культуры и спорта, работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерлерде жұмыс атқарып жүрген денсаулық сақтау, әлеуметтік қамтамасыз ету, білім, мәдениет және спорт мекемелері мамандарының жалақылары мен тарифтік ставкаларын көтеру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-10-17
approved_by:
- '162000000002'
version_date:
  kaz: 2002-10-17
  rus: 2002-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/13554/kaz/17.10.2002
  rus: https://zan.gov.kz/client/#!/doc/13554/rus/17.10.2002
