act_code: '54010'
requisite: Қостанай облысы Меңдіқара ауданы Боровской селосы әкімінің 2010 жылғы 14 шілдедегі № 7 шешімі. Қостанай облысы Меңдіқара ауданының Әділет басқармасында 2010 жылғы 13 тамызда № 9-15-134 тіркелді
title:
  rus: Красных партизан көшесін, Набережная көшесінің бөлігін, Школьная көшесін Тұрсынбай батыр көшесіне қайта атау туралы
  kaz: Красных партизан көшесін, Набережная көшесінің бөлігін, Школьная көшесін Тұрсынбай батыр көшесіне қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-14
approved_by:
- '162013013001'
version_date:
  kaz: 2010-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/54010/kaz/14.07.2010
