act_code: '206512'
requisite: Решение маслихата Наурзумского района Костанайской области от 13 января 2025 года № 178
title:
  rus: О бюджете села Кожа Наурзумского района на 2025-2027 годы
  kaz: Науырзым ауданы Қожа ауылының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-13
approved_by:
- '162014000002'
version_date:
  kaz: 2025-09-04
  rus: 2025-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/206512/kaz/04.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206512/rus/04.09.2025
caused_by:
  code: '213859'
  requisite: Решение маслихата Наурзумского района Костанайской области от 4 сентября 2025 года № 221
  title:
    rus: О внесении изменений в решение Наурзумского районного маслихата от 13 января 2025 года № 178 «О бюджете села Кожа Наурзумского района на 2025-2027 годы»
    kaz: Науырзым аудандық маслихатының 2025 жылғы 13 қаңтардағы № 178 «Науырзым ауданы Қожа ауылының 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213859/rus
