act_code: '183684'
requisite: Решение акима Узункольского сельского округа Узункольского района Костанайской области от 4 июля 2023 года № 6-р
title:
  rus: О предоставлении право ограниченного землепользования земельного участка государственному учреждению «Отдел жилищно-коммунального хозяйства, пассажирского транспорта и автомобильных дорог Узункольского района» во временное возмездное краткосрочное землепользование для строительства инженерных сетей и блочно-модульной котельной села Узунколь
  kaz: «Ұзынкөл ауданының тұрғын үй-коммуналдық шаруашылық, жолаушылар көлігі және автомобиль жолдары бөлімі» ММ Ұзынкөл ауылында инженерлік жылу желілері мен блоктық-модульдік қазандық құрылысы үшін уақытша өтеулі шектеулі жер пайдалану құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-04
approved_by:
- '162017013002'
version_date:
  kaz: 2023-07-04
  rus: 2023-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/183684/kaz/04.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183684/rus/04.07.2023
