act_code: '20304'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 28 мая 2004 года № 70. Зарегистрировано Департаментом юстиции Костанайской области 15 июня 2004 года № 2985
title:
  rus: Об Инструкции назначения и выплаты материальной помощи участникам, инвалидам Великой Отечественной войны и малообеспеченным гражданам
  kaz: Ұлы Отан соғысының қатысушыларына, мүгедектеріне және аз қамтылған азаматтарға материалдық көмекті тағайындау мен төлеу Нұсқауы туралы
form: РЕШ
type_codes:
- ИНСТ
- РЕШ
approved_on: 2004-05-27
approved_by:
- '162013000002'
version_date:
  kaz: 2004-05-27
  rus: 2004-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/20304/kaz/27.05.2004
  rus: https://zan.gov.kz/client/#!/doc/20304/rus/27.05.2004
