act_code: '62015'
requisite: Решение маслихата Костанайской области от 8 декабря 2011 года № 450. Зарегистрировано Департаментом юстиции Костанайской области 12 декабря 2011 года № 3788
title:
  rus: Об областном бюджете Костанайской области на 2012-2014 годы
  kaz: Қостанай облысының 2012-2014 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-08
approved_by:
- '162000000002'
version_date:
  kaz: 2012-12-19
  rus: 2012-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/62015/kaz/19.12.2012
  rus: https://zan.gov.kz/client/#!/doc/62015/rus/19.12.2012
caused_by:
  code: '69381'
  requisite: Решение маслихата Костанайской области от 19 декабря 2012 года № 109. Зарегистрировано Департаментом юстиции Костанайской области 24 декабря 2012 года № 3944
  title:
    rus: О внесении изменений в решение маслихата от 8 декабря 2011 года № 450 "Об областном бюджете Костанайской области на 2012-2014 годы"
    kaz: Мәслихаттың 2011 жылғы 8 желтоқсандағы № 450 "Қостанай облысының 2012-2014 жылдарға арналған облыстық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/69381/rus
