act_code: '127113'
requisite: Решение маслихата Костанайской области от 12 декабря 2018 года № 347. Зарегистрировано Департаментом юстиции Костанайской области 13 декабря 2018 года № 8166
title:
  rus: Об областном бюджете Костанайской области на 2019-2021 годы
  kaz: Қостанай облысының 2019-2021 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-12
approved_by:
- '162000000002'
version_date:
  kaz: 2019-09-20
  rus: 2019-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/127113/kaz/20.09.2019
  rus: https://zan.gov.kz/client/#!/doc/127113/rus/20.09.2019
caused_by:
  code: '134893'
  requisite: Решение маслихата Костанайской области от 20 сентября 2019 года № 428. Зарегистрировано Департаментом юстиции Костанайской области 26 сентября 2019 года № 8674
  title:
    rus: О внесении изменений в решение маслихата от 12 декабря 2018 года № 347 «Об областном бюджете Костанайской области на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 12 желтоқсандағы № 347 «Қостанай облысының 2019-2021 жылдарға арналған облыстық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134893/rus
