act_code: '14346'
requisite: Решение Костанайского областного маслихата от 18 декабря 2002 года № 239. Зарегистрировано Управлением юстиции Костанайской области 24 декабря 2002 года № 1934. Срок действия решения до 1 января 2004 года
title:
  rus: Об областном бюджете Костанайской области на 2003 год
  kaz: 2003 жылға арналған Қостанай облысының облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-18
approved_by:
- '162000000002'
version_date:
  kaz: 2002-12-18
  rus: 2002-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/14346/kaz/18.12.2002
  rus: https://zan.gov.kz/client/#!/doc/14346/rus/18.12.2002
