act_code: '105996'
requisite: Решение маслихата Костанайского района Костанайской области от 11 августа 2016 года № 51. Зарегистрировано Департаментом юстиции Костанайской области 5 сентября 2016 года № 6610. Утратило силу решением маслихата Костанайского района Костанайской области от 13 апреля 2020 года № 511 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-08-11
approved_by:
- '162012000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/105996/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/105996/rus/09.04.2019
caused_by:
  code: '130582'
  requisite: Решение маслихата Костанайского района Костанайской области от 9 апреля 2019 года № 377. Зарегистрировано Департаментом юстиции Костанайской области 15 апреля 2019 года № 8355. Утратило силу решением маслихата Костанайского района Костанайской области от 13 апреля 2020 года № 511 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 11 августа 2016 года № 51 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
    kaz: Мәслихаттың 2016 жылғы 11 тамыздағы № 51 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130582/rus
