act_code: '207216'
requisite: Решение маслихата города Аркалыка Костанайской области от 10 февраля 2025 года № 151. Зарегистрировано в Департаменте юстиции Костанайской области 19 февраля 2025 года № 10381-10
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по городу Аркалык
  kaz: Арқалық қаласы бойынша шетелдіктер үшін 2025 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-10
approved_by:
- '162019000002'
version_date:
  kaz: 2025-02-10
  rus: 2025-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/207216/kaz/10.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207216/rus/10.02.2025
