act_code: '146455'
requisite: Решение акима села Уленды Наурзумского района Костанайской области от 14 сентября 2020 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 18 сентября 2020 года № 9460
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-14
approved_by:
- '162014007001'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/146455/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146455/rus/14.09.2020
