act_code: '144083'
requisite: Решение акима Карамендинского сельского округа Наурзумского района Костанайской области от 18 июня 2020 года № 6. Зарегистрировано Департаментом юстиции Костанайской области 25 июня 2020 года № 9284
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-18
approved_by:
- '162014001002'
version_date:
  kaz: 2020-06-18
  rus: 2020-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/144083/kaz/18.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144083/rus/18.06.2020
