act_code: '91602'
requisite: Решение маслихата Сарыкольского района Костанайской области от 25 июня 2015 года № 257. Зарегистрировано Департаментом юстиции Костанайской области 9 июля 2015 года № 5749. Утратило силу решением маслихата Сарыкольского района Костанайской области от 15 марта 2018 года № 146
title:
  rus: О корректировке базовых налоговых ставок земельного налога и повышении ставок единого земельного налога по Сарыкольскому району
  kaz: Сарыкөл ауданы бойынша жер салығының базалық салық мөлшерлемелерін түзету және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-25
approved_by:
- '162015000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/91602/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/91602/rus/01.04.2016
caused_by:
  code: '102192'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 1 апреля 2016 года № 11. Зарегистрировано Департаментом юстиции Костанайской области 11 мая 2016 года № 6346. Утратило силу решением маслихата Сарыкольского района Костанайской области от 15 марта 2018 года № 146
  title:
    rus: О внесении изменения в решение маслихата  от  25  июня  2015  года № 257 «О корректировке базовых налоговых ставок земельного налога и повышении ставок единого земельного налога по Сарыкольскому району»
    kaz: Мәслихаттың 2015 жылғы 25 маусымдағы № 257 «Сарыкөл ауданы бойынша жер салығының базалық салық мөлшерлемелерін түзету және бірыңғай жер салығының мөлшерлемелерін  жоғарылату туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102192/rus
