act_code: '146082'
requisite: Решение акима Сорочинского сельского округа Сарыкольского района Костанайской области от 4 сентября 2020 года № 7-р. Зарегистрировано Департаментом юстиции Костанайской области 7 сентября 2020 года № 9433. Утратило силу решением акима Сорочинского сельского округа Сарыкольского района Костанайской области от 8 февраля 2021 года № 3-р (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс–шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-04
approved_by:
- '162015010002'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/146082/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146082/rus/04.09.2020
