act_code: '138353'
requisite: Решение маслихата Федоровского района Костанайской области от 9 января 2020 года № 397. Зарегистрировано Департаментом юстиции Костанайской области 14 января 2020 года № 8882
title:
  rus: О районном бюджете Федоровского района на 2020–2022 годы
  kaz: Федоров ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-09
approved_by:
- '162018000002'
version_date:
  kaz: 2020-10-20
  rus: 2020-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/138353/kaz/20.10.2020
  rus: https://zan.gov.kz/client/#!/doc/138353/rus/20.10.2020
caused_by:
  code: '147664'
  requisite: Решение маслихата Федоровского района Костанайской области от 20 октября 2020 года № 474. Зарегистрировано Департаментом юстиции Костанайской области 22 октября 2020 года № 9503
  title:
    rus: О внесении изменений в решение маслихата от 9 января 2020 года № 397 «О районном бюджете Федоровского района на 2020-2022 годы»
    kaz: Мәслихаттың 2020 жылғы 9 қаңтардағы № 397 «Федоров ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147664/rus
