act_code: '122968'
requisite: Решение маслихата Костанайского района Костанайской области от 30 мая 2018 года № 266. Зарегистрировано Департаментом юстиции Костанайской области 21 июня 2018 года № 7889. Утратило силу решением маслихата Костанайского района Костанайской области от 27 января 2020 года № 472 (вводится в действие для сельских округов с численностью населения более двух тысяч человек с 1 января 2018 года и для сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Мичуринского сельского округа Костанайского района Костанайской области
  kaz: Қостанай облысы Қостанай ауданы Мичурин ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-30
approved_by:
- '162012000002'
version_date:
  kaz: 2019-10-22
  rus: 2019-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/122968/kaz/22.10.2019
  rus: https://zan.gov.kz/client/#!/doc/122968/rus/22.10.2019
caused_by:
  code: '135675'
  requisite: Решение маслихата Костанайского района Костанайской области от 22 октября 2019 года № 440. Зарегистрировано Департаментом юстиции Костанайской области 31 октября 2019 года № 8730. Утратило силу решением маслихата Костанайского района Костанайской области от 27 января 2020 года № 472 (вводится в действие для сельских округов с численностью населения более двух тысяч человек с 1 января 2018 года и для сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 30 мая 2018 года № 266 «Об утверждении Регламента собрания местного сообщества Мичуринского сельского округа Костанайского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 30 мамырдағы № 266 «Қостанай облысы Қостанай ауданы Мичурин ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135675/rus
