act_code: '127708'
requisite: Решение маслихата Карасуского района Костанайской области от 28 декабря 2018 года № 282. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8220
title:
  rus: О бюджетах Железнодорожного сельского округа, села Карасу, села Октябрьское Карасуского района на 2019-2021 годы
  kaz: 2019 - 2021 жылдарға арналған Қарасу ауданының Железнодорожный ауылдық округінің, Қарасу ауылының, Октябрь ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '162011000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/127708/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127708/rus/09.04.2019
caused_by:
  code: '130404'
  requisite: Решение маслихата Карасуского района Костанайской области от 9 апреля 2019 года № 312. Зарегистрировано Департаментом юстиции Костанайской области 11 апреля 2019 года № 8334
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 28 декабря 2018 года № 282 «О бюджетах Железнодорожного сельского округа, села Карасу, села Октябрьское Карасуского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 28 желтоқсандағы № 282 «2019 – 2021 жылдарға арналған Қарасу ауданының Железнодорожный ауылдық округінің, Қарасу ауылының, Октябрь ауылының бюджеттері туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130404/rus
