act_code: '222186'
requisite: Решение акима поселка Качар города Рудного Костанайской области от 29 декабря 2025 года № 102-р
title:
  rus: Об установлении публичного сервитута
  kaz: Жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-29
approved_by:
- '162021001001'
version_date:
  kaz: 2025-12-29
  rus: 2025-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/222186/kaz/29.12.2025
  rus: https://zan.gov.kz/client/#!/doc/222186/rus/29.12.2025
