act_code: '182555'
requisite: Решение акима села Троебратское Узункольского района Костанайской области от 6 июня 2023 года № 2-р
title:
  rus: О предоставлении право ограниченного землепользования ГУ «Отдел архитектуры, градостроительства и строительства Узункольского района» во временное возмездное краткосрочное землепользование для строительства водопроводных разводящих сетей в селе Троебратское
  kaz: «Ұзынкөл ауданының сәулет, қала құрылысы және құрылыс бөлімі ММ Троебратское ауылында су тарату құбырларын салу үшін қысқа мерзімді уақытша өтеулі шектеулі жер пайдалану құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-06
approved_by:
- '162017016001'
version_date:
  kaz: 2023-06-06
  rus: 2023-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/182555/kaz/06.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182555/rus/06.06.2023
