act_code: '67326'
requisite: Решение маслихата города Костаная Костанайской области от 25 июля 2012 года № 60. Зарегистрировано Департаментом юстиции Костанайской области 24 августа 2012 года № 9-1-198. Утратило силу решением маслихата города Костаная Костанайской области от 15 мая 2018 года № 243
title:
  rus: О ставках налога на земли, выделенные под автостоянки (паркинг)
  kaz: Автотұрақтар (паркингтер) үшін бөлінген жерлерге арналған салық мөлшерлемері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-25
approved_by:
- '162002000002'
version_date:
  kaz: 2015-08-13
  rus: 2015-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/67326/kaz/13.08.2015
  rus: https://zan.gov.kz/client/#!/doc/67326/rus/13.08.2015
caused_by:
  code: '93704'
  requisite: Решение маслихата города Костаная Костанайской области от 13 августа 2015 года № 348. Зарегистрировано Департаментом юстиции Костанайской области 16 сентября 2015 года № 5878. Утратило силу решением маслихата города Костаная Костанайской области от 15 мая 2018 года № 243
  title:
    rus: О внесении изменений в решение маслихата от 25 июля  2012 года № 60 "О ставках налога на земли, выделенные под автостоянки (паркинги)"
    kaz: Мәслихаттың 2012 жылғы 25 шілдедегі № 60 «Автотұрақтар (паркингтер) үшін бөлінген жерлерге арналған салық ставкалары туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93704/rus
