act_code: '122995'
requisite: Решение маслихата Костанайского района Костанайской области от 30 мая 2018 года № 264. Зарегистрировано Департаментом юстиции Костанайской области 21 июня 2018 года № 7887. Утратило силу решением маслихата Костанайского района Костанайской области от 5 февраля 2020 года № 477 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества поселка Затобольск Костанайского района Костанайской области
  kaz: Қостанай облысы Қостанай ауданы Затобол кентінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-30
approved_by:
- '162012000002'
version_date:
  kaz: 2019-10-22
  rus: 2019-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/122995/kaz/22.10.2019
  rus: https://zan.gov.kz/client/#!/doc/122995/rus/22.10.2019
caused_by:
  code: '135671'
  requisite: Решение маслихата Костанайского района Костанайской области от 22 октября 2019 года № 438. Зарегистрировано Департаментом юстиции Костанайской области 31 октября 2019 года № 8729. Утратило силу решением маслихата Костанайского района Костанайской области от 5 февраля 2020 года № 477 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 30 мая 2018 года № 264 «Об утверждении Регламента собрания местного сообщества поселка Затобольск Костанайского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 30 мамырдағы № 264 «Қостанай облысы Қостанай ауданы Затобол кентінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135671/rus
