act_code: '16412'
requisite: Решение маслихата города Рудного Костанайской области от 19 июля 2003 года № 262. Зарегистрировано Департаментом юстиции Костанайской области 29 июля 2003 года № 2390. Утратило силу решением маслихата города Рудного Костанайской области от 17 июня 2005 года № 183
title:
  rus: Об утверждении Правил благоустройства, санитарной очистки территории, содержания и защиты зеленых насаждений в городе Рудном
  kaz: Рудный қаласының аумағын абаттандыру, санитарлық тазалау, жасыл көшеттерін ұстау және қорғау ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-18
approved_by:
- '162021000002'
version_date:
  kaz: 2003-07-18
  rus: 2003-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/16412/kaz/18.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16412/rus/18.07.2003
