act_code: '43022'
requisite: Қостанай облысы Науырзым ауданы мәслихатының 2008 жылғы 19 желтоқсандағы № 147 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2008 жылғы 27 желтоқсанда № 9-16-80 болып тіркелді
title:
  rus: Науырзым ауданының 2009 жылға аудандық бюджеті туралы
  kaz: Науырзым ауданының 2009 жылға аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '162014000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43022/kaz/19.12.2008
