act_code: '220974'
requisite: Решение маслихата Сарыкольского района Костанайской области от 29 декабря 2025 года № 390
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по Сарыкольскому району
  kaz: Сарыкөл ауданы бойынша шетелдіктер үшін 2026 жылға туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-29
approved_by:
- '162015000002'
version_date:
  kaz: 2025-12-29
  rus: 2025-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/220974/kaz/29.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220974/rus/29.12.2025
