act_code: '31985'
requisite: Решение маслихата Узункольского района Костанайской области от 19 января 2007 года № 319. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 19 февраля 2007 года № 9-19-39. Утратило силу решением маслихата Узункольского района Костанайской области от 23 мая 2007 года № 359
title:
  rus: Об установлении размеров ставок фиксированного суммарного налога с единицы объекта налогообложения на объекты игорного бизнеса для налогоплательщиков, оказывающих услуги по бильярду и игровых автоматов с денежным выигрышем, предназначенные для проведения игры с участием более одного игрока (за исключением электронной рулетки)
  kaz: Бильярд және (электрондық рулеткадан басқа) бір адамнан артық ойын өткізуге арналған ақшалай ұтысы бар ойын автоматтар бойынша қызмет көрсететін, салық төлеушілер үшін ойын бизнес объектілеріне бір салық объектісінен алынатын тіркелген жиынтық салық ставкаларының мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-19
approved_by:
- '162017000002'
version_date:
  kaz: 2007-02-19
  rus: 2007-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/31985/kaz/19.02.2007
  rus: https://zan.gov.kz/client/#!/doc/31985/rus/19.02.2007
