act_code: '145660'
requisite: Решение маслихата Карасуского района Костанайской области от 17 августа 2020 года № 420. Зарегистрировано Департаментом юстиции Костанайской области 21 августа 2020 года № 9395
title:
  rus: Об организации и проведении мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-08-17
approved_by:
- '162011000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/145660/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/145660/rus/19.03.2024
caused_by:
  code: '195229'
  requisite: Решение маслихата Карасуского района Костанайской области от 19 марта 2024 года № 124. Зарегистрировано в Департаменте юстиции Костанайской области 3 апреля 2024 года № 10167-10
  title:
    rus: О внесении изменений в решение маслихата от 17 августа 2020 года № 420 «Об организации и проведении мирных собраний»
    kaz: Мәслихаттың 2020 жылғы 17 тамыздағы № 420 «Бейбіт жиналыстарды ұйымдастыру және өткізу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195229/rus
