act_code: '208906'
requisite: Решение акима села Перелески Денисовского района Костанайской области от 7 апреля 2025 года № 5
title:
  rus: Об установлении публичного сервитута государственному учреждению «Отдел архитектуры, градостроительства и строительства акимата Денисовского района»
  kaz: «Денисов ауданы әкімдігінің сәулет, қала құрылысы және құрылыс бөлімі» мемлекеттік мекемесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-07
approved_by:
- '162006014001'
version_date:
  kaz: 2025-04-07
  rus: 2025-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/208906/kaz/07.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208906/rus/07.04.2025
