act_code: '116259'
requisite: Решение маслихата Житикаринского района Костанайской области от 31 октября 2017 года № 155. Зарегистрировано Департаментом юстиции Костанайской области 27 ноября 2017 года № 7336. Утратило силу решением маслихата Житикаринского района Костанайской области от 10 сентября 2018 года № 232
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в Житикаринском районе на период 2017-2018 годы
  kaz: Жітіқара ауданында 2017-2018 жылдар кезеңіне арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2017-10-31
approved_by:
- '162008000002'
version_date:
  kaz: 2017-10-31
  rus: 2017-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/116259/kaz/31.10.2017
  rus: https://zan.gov.kz/client/#!/doc/116259/rus/31.10.2017
