act_code: '16337'
requisite: Решение маслихата города Костаная Костанайской области от 13 июня 2003 года № 254. Зарегистрировано Управлением юстиции города Костаная Костанайской области 30 июня 2003 года № 2344. Утратило силу решением маслихата города Костаная Костанайской области от 23 февраля 2012 года № 27
title:
  rus: Об утверждении Правил благоустройства, санитарной очистки территории, содержания, защиты и сноса зеленых насаждений в городе Костанае
  kaz: Қостанай қаласындағы аумақты көріктендіру, санитарлық тазалау, жасыл желектерді күтіп ұстау, қорғау және шығарып тастау ережелері бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-06-12
approved_by:
- '162002000002'
version_date:
  kaz: 2005-10-21
  rus: 2005-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/16337/kaz/21.10.2005
  rus: https://zan.gov.kz/client/#!/doc/16337/rus/21.10.2005
caused_by:
  code: '25676'
  requisite: Решение маслихата города Костаная Костанайской области (третьего созыва) от 21 октября 2005 года № 182. Зарегистрировано Управлением юстиции города Костаная Костанайской области 26 октября 2005 года № 9-1-27. Утратило силу решением маслихата города Костаная Костанайской области от 23 февраля 2012 года № 27
  title:
    rus: О внесении дополнения в решение маслихата от 13 июня 2003 года № 254 "Об утверждении Правил благоустройства, санитарной очистки территории, содержания, защиты и сноса зеленых насаждений в городе Костанае и персонального состава комиссии по вопросам благоустройства города Костаная"
    kaz: '"Қостанай қаласындағы аумақты көріктендіру, санитарлық тазалау, жасыл желектерді күтіп ұстау, қорғау және шығарып тастау ережелері" мен Қостанай қаласын көріктендіру мәселелері жөніндегі комиссияның дербес құрамын бекіту туралы" мәслихатының 2003 жылғы 13 маусымдағы № 254 шешіміне толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/25676/rus
