act_code: '170617'
requisite: Решение маслихата города Костаная Костанайской области от 9 августа 2022 года № 139. Зарегистрировано в Министерстве юстиции Республики Казахстан 16 августа 2022 года № 29126
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Костанай
  kaz: Қостанай қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2022-08-09
approved_by:
- '162002000002'
version_date:
  kaz: 2022-08-09
  rus: 2022-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/170617/kaz/09.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170617/rus/09.08.2022
