act_code: '135123'
requisite: Решение акима села Уленды Наурзумского района Костанайской области от 4 октября 2019 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 8 октября 2019 года № 8689. Утратило силу решением акима села Уленды Наурзумского района Костанайской области от 14 сентября 2020 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-04
approved_by:
- '162014007001'
version_date:
  kaz: 2019-10-04
  rus: 2019-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/135123/kaz/04.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135123/rus/04.10.2019
