act_code: '162251'
requisite: Решение маслихата Наурзумского района Костанайской области от 27 декабря 2021 года № 86. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26037
title:
  rus: О районном бюджете Наурзумского района на 2022-2024 годы
  kaz: Науырзым ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '162014000002'
version_date:
  kaz: 2022-05-19
  rus: 2022-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/162251/kaz/19.05.2022
  rus: https://zan.gov.kz/client/#!/doc/162251/rus/19.05.2022
caused_by:
  code: '167887'
  requisite: Решение маслихата Наурзумского района Костанайской области от 19 мая 2022 года № 128
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2021 года № 86 «О районном бюджете Наурзумского района на 2022-2024 годы»
    kaz: Мәслихаттың 2021 жылғы 27 желтоқсандағы  № 86 «Науырзым ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167887/rus
