act_code: '97120'
requisite: Решение маслихата города Аркалыка Костанайской области от 21 декабря 2015 года № 278. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2015 года № 6099
title:
  rus: О бюджете города Аркалыка на 2016-2018 годы
  kaz: Арқалық қаласының 2016-2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '162019000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/97120/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/97120/rus/01.04.2016
caused_by:
  code: '101086'
  requisite: Решение маслихата города Аркалык Костанайской области от 1 апреля 2016 года № 10. Зарегистрировано Департаментом юстиции Костанайской области 11 апреля 2016 года № 6274
  title:
    rus: О внесении изменений в решение маслихата от 21 декабря 2015 года № 278 "О бюджете города Аркалыка на 2016 - 2018 годы"
    kaz: Мәслихаттың 2015 жылғы 21 желтоқсандағы № 278 "Арқалық қаласының 2016-2018 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101086/rus
