act_code: '118083'
requisite: Решение маслихата Федоровского района Костанайской области от 25 декабря 2017 года № 198. Зарегистрировано Департаментом юстиции Костанайской области 15 января 2018 года № 7482
title:
  rus: О бюджетах сельских округов Федоровского района на 2018 - 2020 годы
  kaz: Федоров ауданы ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '162018000002'
version_date:
  kaz: 2018-12-07
  rus: 2018-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/118083/kaz/07.12.2018
  rus: https://zan.gov.kz/client/#!/doc/118083/rus/07.12.2018
caused_by:
  code: '126932'
  requisite: Решение маслихата Федоровского района Костанайской области от 7 декабря 2018 года № 289. Зарегистрировано Департаментом юстиции Костанайской области 13 декабря 2018 года № 8164
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2017 года № 198 «О бюджетах сельских округов Федоровского района на 2018-2020 годы»
    kaz: Мәслихаттың 2017 жылғы 25 желтоқсандағы № 198 «Федоров ауданы ауылдық округтерінің 2018-2020 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126932/rus
