act_code: '87837'
requisite: Решение маслихата Джангельдинского района Костанайской области от 26 февраля 2015 года № 206. Зарегистрировано Департаментом юстиции Костанайской области 19 марта 2015 года № 5442. Утратило силу решением маслихата Жангельдинского района Костанайской области от 18 января 2016 года № 253
title:
  rus: Об утверждении Правил оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-02-26
approved_by:
- '162007000002'
version_date:
  kaz: 2015-02-26
  rus: 2015-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/87837/kaz/26.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87837/rus/26.02.2015
