act_code: '79290'
requisite: Решение маслихата Карабалыкского района Костанайской области от 26 марта 2014 года № 213. Зарегистрировано Департаментом юстиции Костанайской области 24 апреля 2014 года № 4648. Утратило силу решением маслихата Карабалыкского района Костанайской области от 11 мая 2017 года № 148
title:
  rus: Об утверждении регламента Карабалыкского районного маслихата
  kaz: Қарабалық аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-26
approved_by:
- '162010000002'
version_date:
  kaz: 2014-03-26
  rus: 2014-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/79290/kaz/26.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79290/rus/26.03.2014
