act_code: '219921'
requisite: Решение акима поселка Карабалык Карабалыкского района Костанайской области от 19 ноября 2025 года № 15-р
title:
  rus: О предоставлении товариществу с ограниченной ответственностью «ЭПК-forfait» права ограниченного целевого землепользования (публичный сервитут) для обслуживания и эксплуатации воздушных линии электропередач
  kaz: «ЭПК-forfait» жауапкершілігі шектеулі серіктестігіне әуе электр беру желілеріне қызмет көрсету және пайдалану үшін шектеулі нысаналы жер пайдалану құқығын (қоғамдық сервитут) беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-19
approved_by:
- '162010014001'
version_date:
  kaz: 2025-11-19
  rus: 2025-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219921/kaz/19.11.2025
  rus: https://zan.gov.kz/client/#!/doc/219921/rus/19.11.2025
