act_code: '26468'
requisite: Решение маслихата города Лисаковска Костанайской области от 15 декабря 2005 года № 218. Зарегистрировано Управлением юстиции Костанайской области 30 декабря 2005 года № 9-4-36. Срок действия решения - до 1 января 2007 года
title:
  rus: Об утверждении Правил оказания жилищной помощи на 2006 год в городе Лисаковске
  kaz: Лисаков қаласындағы 2006 жылға арналған тұрғын үй көмегін көрсету Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-12-15
approved_by:
- '162020000002'
version_date:
  kaz: 2005-12-15
  rus: 2005-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/26468/kaz/15.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26468/rus/15.12.2005
