act_code: '4441'
requisite: Решение акима Костанайской области от 24 мая 1999 года № 139. Зарегистрировано Управлением юстиции Костанайской области 14 октября 1999 года № 126. Утратило силу решением акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: О мерах по выполнению Постановления Правительства Республики Казахстан от 6 мая 1999 года № 532 «О реализации Указа Президента Республики Казахстан от 3 мая 1999 года № 128 «О квоте иммиграции на 1999 год»
  kaz: '"1999 жылға арналған қоныс аударушылардың квотасы туралы" Қазақстан Республикасы Президентінің 1999 жылғы 3 мамырдағы 128 Жарлығын жүзеге асыру туралы" Казақстан Республикасы Үкіметінің 1999 жылғы 6 мамырдағы 532 Қаулысын орындау жөніндегі шаралар туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-05-23
approved_by:
- '162000000003'
version_date:
  kaz: 1999-05-23
  rus: 1999-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/4441/kaz/23.05.1999
  rus: https://zan.gov.kz/client/#!/doc/4441/rus/23.05.1999
