act_code: '32103'
requisite: Решение акима поселка Карабалык Карабалыкского района Костанайской области от 19 февраля 2007 года № 3. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 26 февраля 2007 года № 9-12-35
title:
  rus: Об определении перечня объектов и видов общественных работ для лиц, осужденных к мере наказания в виде привлечения к общественным работам
  kaz: Қоғамдық жұмыстарға тарту түріндегі жазаға кесілген тұлғалар үшін қоғамдық жұмыстардың объектілері және оның түрлерінің тізбесін анықтау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2007-02-19
approved_by:
- '162010014001'
version_date:
  kaz: 2007-02-19
  rus: 2007-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/32103/kaz/19.02.2007
  rus: https://zan.gov.kz/client/#!/doc/32103/rus/19.02.2007
