act_code: '137781'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 30 декабря 2019 года № 331. Зарегистрировано Департаментом юстиции Костанайской области 31 декабря 2019 года № 8862
title:
  rus: О районном бюджете Мендыкаринского района на 2020 - 2022 годы
  kaz: Меңдіқара ауданының 2020 - 2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '162013000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137781/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137781/rus/30.12.2019
