act_code: '78656'
requisite: Решение маслихата Денисовского района Костанайской области от 28 февраля 2014 года № 18. Зарегистрировано Департаментом юстиции Костанайской области 8 апреля 2014 года № 4546. Утратило силу решением маслихата Денисовского района Костанайской области от 9 июня 2022 года № 44 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Аршалинского сельского округа Денисовского района Костанайской области
  kaz: Қостанай облысы Денисов ауданы Аршалы  ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-28
approved_by:
- '162006000002'
version_date:
  kaz: 2015-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/78656/kaz/19.06.2015
caused_by:
  code: '91466'
  requisite: Решение маслихата Денисовского района Костанайской области от 19 июня 2015 года № 53. Зарегистрировано Департаментом юстиции Костанайской области 8 июля 2015 года № 5731. Утратило силу решением маслихата Денисовского района Костанайской области от 9 июня 2022 года № 44 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Денисовского районного маслихата от 28 февраля 2014 года № 18 "Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Аршалинского сельского округа Денисовского района Костанайской области"
    kaz: Денисов аудандық мәслихатының 2014 жылғы 28 ақпандағы № 18 "Қостанай облысы Денисов ауданы Аршалы ауылдық округінің жергілікті қоғамдастықтың жиынына қатысу үшін бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/91466/rus
