act_code: '47474'
requisite: Решение маслихата Федоровского района Костанайской области от 19 августа 2009 года № 213. Зарегистрировано Управлением юстиции Федоровского района Костанайской области 20 августа 2009 года № 9-20-159
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты на 2009 год
  kaz: 2009 жылы ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-19
approved_by:
- '162018000002'
version_date:
  kaz: 2009-08-19
  rus: 2009-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/47474/kaz/19.08.2009
  rus: https://zan.gov.kz/client/#!/doc/47474/rus/19.08.2009
