act_code: '74511'
requisite: Решение маслихата Тарановского района Костанайской области от 27 августа 2013 года № 145. Зарегистрировано Департаментом юстиции Костанайской области 23 сентября 2013 года № 4222. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 10 августа 2020 года № 403 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-27
approved_by:
- '162016000002'
version_date:
  kaz: 2019-06-04
  rus: 2019-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/74511/kaz/04.06.2019
  rus: https://zan.gov.kz/client/#!/doc/74511/rus/04.06.2019
caused_by:
  code: '132343'
  requisite: Решение маслихата Тарановского района Костанайской области от 4 июня 2019 года № 281. Зарегистрировано Департаментом юстиции Костанайской области 7 июня 2019 года № 8510. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 10 августа 2020 года № 403 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 27 августа 2013 года № 145 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2013 жылғы 27 тамыздағы № 145 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132343/rus
