act_code: '127702'
requisite: Решение маслихата города Лисаковска Костанайской области от 27 декабря 2018 года № 310. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8207
title:
  rus: О бюджете поселка Октябрьский города Лисаковска на 2019-2021 годы
  kaz: Лисаков қаласы Октябрь кентінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '162020000002'
version_date:
  kaz: 2019-12-04
  rus: 2019-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/127702/kaz/04.12.2019
  rus: https://zan.gov.kz/client/#!/doc/127702/rus/04.12.2019
caused_by:
  code: '136910'
  requisite: Решение маслихата города Лисаковска Костанайской области от 4 декабря 2019 года № 369. Зарегистрировано Департаментом юстиции Костанайской области 11 декабря 2019 года № 8819
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2018 года № 310 «О бюджете поселка Октябрьский города Лисаковска  на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 27 желтоқсандағы № 310 «Лисаков қаласы Октябрь кентінің 2019-2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136910/rus
