act_code: '11620'
requisite: Решение маслихата Костанайской области от 18 февраля 2002 года № 180. Зарегистрировано Управлением юстиции Костанайской области 11 марта 2002 года № 1279. Утратило силу решением маслихата Костанайской области от 14 декабря 2004 года № 139
title:
  rus: О ставках платы за загрязнение окружающей среды на 2002 год
  kaz: Қоршаған ортаны ластағаны үшін 2002 жылға арналған төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-02-18
approved_by:
- '162000000002'
version_date:
  kaz: 2002-02-18
  rus: 2002-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/11620/kaz/18.02.2002
  rus: https://zan.gov.kz/client/#!/doc/11620/rus/18.02.2002
