act_code: '192900'
requisite: Решение маслихата Амангельдинского района Костанайской области от 5 декабря 2023 года № 62. Зарегистрировано в Департаменте юстиции Костанайской области 26 января 2024 года № 10133-10
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий  нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-05
approved_by:
- '162004000002'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/192900/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192900/rus/05.12.2023
