act_code: '192900'
requisite: Решение маслихата Амангельдинского района Костанайской области от 5 декабря 2023 года № 62. Зарегистрировано в Департаменте юстиции Костанайской области 26 января 2024 года № 10133-10
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий  нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-05
approved_by:
- '162004000002'
version_date:
  kaz: 2025-04-01
  rus: 2025-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/192900/kaz/01.04.2025
  rus: https://zan.gov.kz/client/#!/doc/192900/rus/01.04.2025
caused_by:
  code: '209177'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 1 апреля 2025 года № 141. Зарегистрировано в Департаменте юстиции Костанайской области 17 апреля 2025 года № 10426-10
  title:
    rus: О внесении изменения в решение маслихата от 5 декабря 2023 года № 62 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2023 жылғы 5 желтоқсандағы № 62 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209177/rus
