act_code: '144804'
requisite: Решение маслихата города Аркалыка Костанайской области от 8 июля 2020 года № 326. Зарегистрировано Департаментом юстиции Костанайской области 15 июля 2020 года № 9325. Утратило силу решением маслихата города Аркалыка Костанайской области от 21 апреля 2023 года № 11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Ашутастинского сельского округа города Аркалыка Костанайской области
  kaz: Қостанай облысы Арқалық қаласы Ашутасты ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-07-08
approved_by:
- '162019000002'
version_date:
  kaz: 2020-07-08
  rus: 2020-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/144804/kaz/08.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144804/rus/08.07.2020
