act_code: '164221'
requisite: Решение маслихата Сарыкольского района Костанайской области от 31 января 2022 года № 106. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 февраля 2022 года № 26706
title:
  rus: О признании утратившим силу решения маслихата от 27 июня 2018 года № 184 «О повышении базовых ставок земельного налога»
  kaz: Мәслихаттың 2018 жылғы 27 мауысымдағы № 184 «Жер салығының базалық мөлшерлемелерін арттыру туралы» шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-31
approved_by:
- '162015000002'
version_date:
  kaz: 2022-01-31
  rus: 2022-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/164221/kaz/31.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164221/rus/31.01.2022
