act_code: '98095'
requisite: Решение маслихата Костанайской области от 11 декабря 2015 года № 475. Зарегистрировано Департаментом юстиции Костанайской области 20 января 2016 года № 6151
title:
  rus: Об утверждении Положения о награждении Почётной грамотой области (города, района)
  kaz: Облыстың (қаланың, ауданның) Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-12-11
approved_by:
- '162000000002'
version_date:
  kaz: 2016-06-27
  rus: 2016-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/98095/kaz/27.06.2016
  rus: https://zan.gov.kz/client/#!/doc/98095/rus/27.06.2016
caused_by:
  code: '104660'
  requisite: Решение маслихата Костанайской области от 27 июня 2016 года № 39. Зарегистрировано Департаментом юстиции Костанайской области 19 июля 2016 года № 6548
  title:
    rus: О внесении дополнений в решение Костанайского областного маслихата от 11 декабря 2015 года № 475 "Об утверждении Положения о награждении Почетной грамотой области (города, района)
    kaz: Қостанай облыстық мәслихатының 2015 жылғы 11 желтоқсандағы № 475 "Облыстың (қаланың, ауданның) Құрмет грамотасымен наградтау туралы ережені бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104660/rus
