act_code: '124852'
requisite: Решение маслихата Костанайского района Костанайской области от 7 сентября 2018 года № 318. Зарегистрировано Департаментом юстиции Костанайской области 2 октября 2018 года № 8055. Утратило силу решением маслихата Костанайского района Костанайской области от 5 февраля 2020 года № 479 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц для участия в сходе местного сообщества села имени И.Ф. Павлова Костанайского района Костанайской области
  kaz: Қостанай облысы Қостанай ауданы И.Ф. Павлов атындағы ауылының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін көшелер тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-09-07
approved_by:
- '162012000002'
version_date:
  kaz: 2018-09-07
  rus: 2018-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/124852/kaz/07.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124852/rus/07.09.2018
