act_code: '132470'
requisite: Решение акима Майкольского сельского округа Костанайского района Костанайской области от 6 июня 2019 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 10 июня 2019 года № 8513
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «SilkNetCom»
  kaz: «SilkNetCom» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-06
approved_by:
- '162012008002'
version_date:
  kaz: 2019-06-06
  rus: 2019-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/132470/kaz/06.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132470/rus/06.06.2019
