act_code: '177734'
requisite: Решение маслихата Карасуского района Костанайской области от 29 декабря 2022 года № 202
title:
  rus: О бюджете Ушаковского сельского округа Карасуского района на 2023-2025 годы
  kaz: Қарасу ауданы Ушаков ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162011000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177734/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177734/rus/29.12.2022
