act_code: '123615'
requisite: Решение маслихата Карабалыкского района Костанайской области от 27 июня 2018 года № 265. Зарегистрировано Департаментом юстиции Костанайской области 13 июля 2018 года № 7957. Утратило силу решением маслихата Карабалыкского района Костанайской области от 15 февраля 2022 года № 102 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-27
approved_by:
- '162010000002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123615/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123615/rus/27.06.2018
