act_code: '8736'
requisite: Решение маслихата Костанайской области от 2 марта 2001 года № 99. Зарегистрировано Управлением юстиции Костанайской области 11 апреля 2001 года № 720. Утратило силу решением маслихата Костанайской области от 31 января 2007 года № 408
title:
  rus: О Правилах определения и обеспечения периодичности бюджетных изъятий, передаваемых из бюджетов районов (городов) в областной бюджет, и условиях выделения субвенций из областного бюджета бюджетам районов (городов) Костанайской области
  kaz: Аудандар (қалалар) бюджеттерінен облыстық бюджетке берілетін бюджеттік алулардың дуркінділігін қамтамасыз етудің және анықтаудың ережелері және Қостанай облысының аудандық қалалық бюджеттеріне облыстық бюджеттен субвенциялар бөлудің шарттары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2001-03-02
approved_by:
- '162000000002'
version_date:
  kaz: 2001-03-02
  rus: 2001-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/8736/kaz/02.03.2001
  rus: https://zan.gov.kz/client/#!/doc/8736/rus/02.03.2001
