act_code: '82627'
requisite: Решение маслихата города Лисаковск Костанайской области от 24 июля 2014 года № 237. Зарегистрировано Департаментом юстиции Костанайской области 22 августа 2014 года № 5042. Утратило силу решением маслихата города Лисаковска Костанайской области от 19 августа 2021 года № 62 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц, домов для участия в сходе местного сообщества села Красногорское города Лисаковска Костанайской области
  kaz: Қостанай облысы Лисаков қаласы Красногор ауылының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін көшелер, үйлер тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-24
approved_by:
- '162020000002'
version_date:
  kaz: 2014-07-24
  rus: 2014-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/82627/kaz/24.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82627/rus/24.07.2014
