act_code: '205873'
requisite: Решение маслихата города Аркалыка Костанайской области от 30 декабря 2024 года № 144
title:
  rus: О бюджете города Аркалыка на 2025-2027 годы
  kaz: Арқалық қаласының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162019000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205873/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205873/rus/30.12.2024
