act_code: '205873'
requisite: Решение маслихата города Аркалыка Костанайской области от 30 декабря 2024 года № 144
title:
  rus: О бюджете города Аркалыка на 2025-2027 годы
  kaz: Арқалық қаласының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162019000002'
version_date:
  kaz: 2025-02-18
  rus: 2025-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/205873/kaz/18.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205873/rus/18.02.2025
caused_by:
  code: '207281'
  requisite: Решение маслихата города Аркалыка Костанайской области от 18 февраля 2025 года № 154
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2024 года № 144 «О бюджете города Аркалыка на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 30 желтоқсандағы № 144 «Арқалық қаласының 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207281/rus
