act_code: '6064'
requisite: Қостанай облысы Әкімінің 2000 жылғы 12 сәуірдегі № 85 шешімі. Қостанай облысының әділет басқармасында 2000 жылғы 21 сәуірде № 237 болып тіркелді
title:
  rus: 2000 жылға арналған жастарды қолдау жөнiндегi аймақтық бағдарламаны бекiту туралы
  kaz: 2000 жылға арналған жастарды қолдау жөнiндегi аймақтық бағдарламаны бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-11
approved_by:
- '162000000003'
version_date:
  kaz: 2000-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/6064/kaz/11.04.2000
