act_code: '127710'
requisite: Решение маслихата Камыстинского района Костанайской области от 27 декабря 2018 года № 219. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8219
title:
  rus: О бюджете Камыстинского сельского округа Камыстинского района на 2019- 2021 годы
  kaz: Қамысты ауданы Қамысты  ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '162009000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/127710/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127710/rus/27.12.2018
