act_code: '131491'
requisite: Решение акима Восточного сельского округа Карасуского района Костанайской области от 14 мая 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 15 мая 2019 года № 8435. Утратило силу решением акима Карасуского сельского округа Карасуского района Костанайской области от 10 сентября 2021 года № 6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении публичного сервитута акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-14
approved_by:
- '162011003002'
version_date:
  kaz: 2019-05-14
  rus: 2019-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/131491/kaz/14.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131491/rus/14.05.2019
