act_code: '83774'
requisite: Решение маслихата города Рудного Костанайской области от 12 сентября 2014 года № 317. Зарегистрировано Департаментом юстиции Костанайской области 15 октября 2014 года № 5116. Утратило силу решением маслихата города Рудного Костанайской области от 6 февраля 2015 года № 363
title:
  rus: Об утверждении Правил оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-09-12
approved_by:
- '162021000002'
version_date:
  kaz: 2014-09-12
  rus: 2014-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/83774/kaz/12.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83774/rus/12.09.2014
