act_code: '37369'
requisite: Решение маслихата Карасуского района Костанайской области от 21 декабря 2007 года № 24. Зарегистрировано управлением юстиции Карасуского района Костанайской области 29 января 2008 года № 9-13-52
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок гражданским служащим социального обеспечения, образования, культуры, работающим в аульной (сельской) местности, за счет средств районного бюджета на 2008 год
  kaz: 2008 жылға арналған аудандық бюджеттің қаражаты есебінен жиырма бес процентке жоғары лауазымдық жалақылар мен тарифтік ставкаларды ауылдық (селолық) жерде жұмыс істейтін әлеуметтік қамсыздандыру білім беру, мәдениет азаматтық қызметшілеріне белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '162011000002'
version_date:
  kaz: 2007-12-21
  rus: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37369/kaz/21.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37369/rus/21.12.2007
