act_code: '191284'
requisite: Решение маслихата Камыстинского района Костанайской области от 28 декабря 2023 года № 136
title:
  rus: О бюджете Аралкольского сельского округа Камыстинского района на 2024-2026 годы
  kaz: Қамысты ауданы Аралкөл ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '162009000002'
version_date:
  kaz: 2024-11-26
  rus: 2024-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/191284/kaz/26.11.2024
  rus: https://zan.gov.kz/client/#!/doc/191284/rus/26.11.2024
caused_by:
  code: '203184'
  requisite: Решение маслихата Камыстинского района Костанайской области от 26 ноября 2024 года № 257
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2023 года № 136 «О бюджете Аралкольского сельского округа Камыстинского района на 2024 – 2026 годы»
    kaz: Мәслихаттың 2023 жылғы 28 желтоқсандағы № 136 «Қамысты ауданы Аралкөл ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203184/rus
