act_code: '37119'
requisite: Решение маслихата Тарановского района Костанайской области от 21 декабря 2007 года № 35. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 28 января 2008 года № 9-18-57. Утратило силу решением маслихата Тарановского района Костанайской области от 29 января 2009 года № 155
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок гражданским служащим социального обеспечения, образования, культуры, работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерлерде жұмыс істейтін есебінен азаматтық қызметкерлердің мамандықтар, жиырма бес пайызға көтеру үшін лауазымдық жалақылары мен тарифтік мөлшерлемелерге білім, мәдениет лауазымдарының тізімін қалыптастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '162016000002'
version_date:
  kaz: 2007-12-21
  rus: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37119/kaz/21.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37119/rus/21.12.2007
