act_code: '56437'
requisite: Қостанай облысы Аманкелді ауданы мәслихатының 2010 жылғы 22 желтоқсандағы № 223 шешімі. Қостанай облысы Аманкелді ауданының Әділет басқармасында 2010 жылғы 30 желтоқсанда № 9-6-119 тіркелді
title:
  rus: Аманкелді ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Аманкелді ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '162004000002'
version_date:
  kaz: 2011-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56437/kaz/14.11.2011
caused_by:
  code: '61630'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 14 ноября 2011 года № 300. Зарегистрировано Управлением юстиции Амангельдинского района Костанайской области 24 ноября 2011 года № 9-6-136
  title:
    rus: О внесении изменений в решение маслихата от 22 декабря 2010 года № 223 "О районном бюджете Амангельдинского района на 2011-2013 годы"
    kaz: Мәслихаттың 2010 жылғы 22 желтоқсандағы № 223 "Аманкелді ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61630/rus
