act_code: '162903'
requisite: Решение маслихата Джангельдинского района Костанайской области от 31 декабря 2021 года № 73
title:
  rus: О бюджетах сел, сельских округов Джангельдинского района на 2022 - 2024 годы
  kaz: Жангелдин ауданы ауылдарының, ауылдық округтерінің 2022-2024 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-31
approved_by:
- '162007000002'
version_date:
  kaz: 2022-05-18
  rus: 2022-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/162903/kaz/18.05.2022
  rus: https://zan.gov.kz/client/#!/doc/162903/rus/18.05.2022
caused_by:
  code: '168033'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 18 мая 2022 года № 107
  title:
    rus: О внесении изменений в решение маслихата от 31 декабря 2021 года № 73 «О бюджетах сел, сельских округов Джангельдинского района на 2022-2024 годы»
    kaz: Мәслихаттың 2021 жылғы 31 желтоқсандағы № 73 «Жангелдин ауданы ауылдарының, ауылдық округтерінің 2022-2024 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168033/rus
