act_code: '191948'
requisite: Решение маслихата Сарыкольского района Костанайской области от 29 декабря 2023 года № 131
title:
  rus: О бюджете села Большие Дубравы Сарыкольского района Костанайской области на 2024-2026 годы
  kaz: Қостанай облысы Сарыкөл ауданы Большие Дубравы ауылының 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '162015000002'
version_date:
  kaz: 2024-12-13
  rus: 2024-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/191948/kaz/13.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191948/rus/13.12.2024
caused_by:
  code: '204563'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 13 декабря 2024 года № 231
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2023 года № 131 «О бюджете села Большие Дубравы Сарыкольского района Костанайской области на 2024-2026 годы»
    kaz: Мәслихаттың 2023 жылғы 29 желтoқсандағы № 131 «Қостанай облысы Сарыкөл ауданы Большие Дубравы ауылының 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204563/rus
