act_code: '44162'
requisite: Қостанай облысы Аманкелді ауданың Әкімінің 2009 жылғы 21 қаңтардағы № 1 шешімі. Қостанай облысы Аманкелді ауданың Әділет басқармасында 2009 жылғы 11 ақпанда № 9-6-88 тіркелді
title:
  rus: 2009 жылы шақыру учаскесіне 1992 жылы туған еркек жынысты азаматтардың тіркелуін ұйымдастыру және қамтамасыз ету туралы
  kaz: 2009 жылы шақыру учаскесіне 1992 жылы туған еркек жынысты азаматтардың тіркелуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-21
approved_by:
- '162004000003'
version_date:
  kaz: 2009-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/44162/kaz/21.01.2009
