act_code: '61510'
requisite: Решение акима Узункольского района Костанайской области от 17 ноября 2011 года № 2. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 17 ноября 2011 года № 9-19-164. Утратило силу решением акима Узункольского района Костанайской области от 2 апреля 2014 года № 8
title:
  rus: Об образовании избирательных участков на территории Узункольского района Костанайской области
  kaz: Қостанай облысы Ұзынкөл ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-17
approved_by:
- '162017000003'
version_date:
  kaz: 2011-11-17
  rus: 2011-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/61510/kaz/17.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61510/rus/17.11.2011
