act_code: '182148'
requisite: Решение акима села Карабатыр Камыстинского района Костанайской области от 25 мая 2023 года № 5-р
title:
  rus: Об установлении публичного сервитута государственному учреждению «Управление энергетики и жилищно-коммунального хозяйства акимата Костанайской области»
  kaz: «Қостанай облысы әкімдігінің энергетика және тұрғын үй-коммуналдық шаруашылық басқармасы» мемлекеттік мекемесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-25
approved_by:
- '162009012001'
version_date:
  kaz: 2023-05-25
  rus: 2023-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/182148/kaz/25.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182148/rus/25.05.2023
