act_code: '13057'
requisite: Решение акима Костанайской области от 30 июля 2002 года № 67а. Зарегистрировано Управлением юстиции Костанайской области 22 августа 2002 года № 1707. Утратило силу решением акима Костанайской области от 12 ноября 2009 года № 27
title:
  rus: О создании областных служб Гражданской обороны и чрезвычайных ситуаций
  kaz: Азаматтық қорғаныстың және төтенше жағдайлардың облыстық қызметтерiн құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-07-29
approved_by:
- '162000000003'
version_date:
  kaz: 2002-07-29
  rus: 2002-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/13057/kaz/29.07.2002
  rus: https://zan.gov.kz/client/#!/doc/13057/rus/29.07.2002
