act_code: '145708'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 19 августа 2020 года № 406. Зарегистрировано Департаментом юстиции Костанайской области 24 августа 2020 года № 9401
title:
  rus: Об организации и проведении мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-08-19
approved_by:
- '162016000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/145708/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/145708/rus/28.03.2024
caused_by:
  code: '195549'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 28 марта 2024 года № 89. Зарегистрировано в Департаменте юстиции Костанайской области 12 апреля 2024 года № 10175-10
  title:
    rus: О внесении изменений в решение маслихата от 19 августа 2020 года № 406 «Об организации и проведении мирных собраний»
    kaz: Мәслихаттың 2020 жылғы 19 тамыздағы № 406 «Бейбіт жиналыстарды ұйымдастыру және өткізу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195549/rus
