act_code: '130284'
requisite: Решение акима села Коктал Аулиекольского района Костанайской области от 8 апреля 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 10 апреля 2019 года № 8327
title:
  rus: О снятии ограничительных мероприятий на территории села Коктал Аулиекольского района Костанайской области
  kaz: Қостанай облысы Әулиекөл ауданы Көктал ауылының аумағында шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-08
approved_by:
- '162005014001'
version_date:
  kaz: 2019-04-08
  rus: 2019-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/130284/kaz/08.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130284/rus/08.04.2019
