act_code: '76457'
requisite: Решение маслихата Федоровского района Костанайской области от 27 декабря 2013 года № 183. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2013 года № 4392
title:
  rus: О районном бюджете Федоровского района на 2014-2016 годы
  kaz: Федоров ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-27
approved_by:
- '162018000002'
version_date:
  kaz: 2014-02-18
  rus: 2014-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/76457/kaz/18.02.2014
  rus: https://zan.gov.kz/client/#!/doc/76457/rus/18.02.2014
caused_by:
  code: '77595'
  requisite: Решение маслихата Федоровского района Костанайской области от 18 февраля 2014 года № 194. Зарегистрировано Департаментом юстиции Костанайской области 26 февраля 2014 года № 4454
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 27 декабря 2013 года № 183 "О районном бюджете Федоровского района на 2014-2016 годы"
    kaz: Мәслихаттың 2013 жылғы 27 желтоқсандағы № 183 "Федоров ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/77595/rus
