act_code: '108286'
requisite: Решение маслихата Костанайской области от 8 декабря 2016 года № 91. Зарегистрировано Департаментом юстиции Костанайской области 20 декабря 2016 года № 6750
title:
  rus: Об областном бюджете Костанайской области на 2017-2019 годы
  kaz: Қостанай облысының 2017-2019 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-08
approved_by:
- '162000000002'
version_date:
  kaz: 2016-12-08
  rus: 2016-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/108286/kaz/08.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108286/rus/08.12.2016
