act_code: '140902'
requisite: Решение акима города Аркалыка Костанайской области от 1 апреля 2020 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 2 апреля 2020 года № 9072
title:
  rus: Об образовании избирательных участков на территории города Аркалыка
  kaz: Арқалық қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-01
approved_by:
- '162019000003'
version_date:
  kaz: 2025-05-06
  rus: 2025-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/140902/kaz/06.05.2025
  rus: https://zan.gov.kz/client/#!/doc/140902/rus/06.05.2025
caused_by:
  code: '209847'
  requisite: Решение акима города Аркалыка Костанайской области от 6 мая 2025 года № 3. Зарегистрировано в Департаменте юстиции Костанайской области 6 мая 2025 года № 10460-10
  title:
    rus: О внесении изменений в решение акима города Аркалыка от 1 апреля 2020 года № 3 «Об образовании избирательных участков на территории города Аркалыка»
    kaz: Арқалық қаласы әкімінің 2020 жылғы 1 сәуірдегі № 3 «Арқалық қаласының аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209847/rus
