act_code: '163134'
requisite: Решение маслихата Житикаринского района Костанайской области от 29 декабря 2021 года № 106
title:
  rus: О бюджете Большевистского сельского округа Житикаринского района на 2022-2024 годы
  kaz: Жітіқара ауданы Большевик ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '162008000002'
version_date:
  kaz: 2022-03-11
  rus: 2022-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/163134/kaz/11.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163134/rus/11.03.2022
caused_by:
  code: '165542'
  requisite: Решение маслихата Житикаринского района Костанайской области от 11 марта 2022 года № 148
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2021 года № 106 «О бюджете Большевистского сельского округа Житикаринского района на 2022-2024 годы»
    kaz: Мәслихаттың 2021 жылғы 29 желтоқсандағы № 106 «Жітіқара ауданы Большевик ауылдық округінің 2022-2024 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165542/rus
