act_code: '68770'
requisite: Решение от 31.10.2012 №78, Маслихат Амангельдинского района. Зарегистрировано Департаментом юстиции Костанайской области 22 ноября 2012 года № 3897. Утратило силу решением маслихата Амангельдинского района Костанайской области от 24 декабря 2014 года № 285
title:
  rus: О правилах оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-10-31
approved_by:
- '162004000002'
version_date:
  kaz: 2012-10-31
  rus: 2012-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/68770/kaz/31.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68770/rus/31.10.2012
