act_code: '81500'
requisite: Решение маслихата Сарыкольского района Костанайской области от 25 июня 2014 года № 182. Зарегистрировано Департаментом юстиции Костанайской области 21 июля 2014 года № 4946. Утратило силу решением маслихата Сарыкольского района Костанайской области от 25 сентября 2023 года № 59 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Севастопольского сельского округа Сарыкольского района Костанайской области
  kaz: Қостанай облысы Сарыкөл ауданы Севастополь ауылдық округінің жергілікті қоғамдастығының бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-06-25
approved_by:
- '162015000002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/81500/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/81500/rus/27.06.2018
caused_by:
  code: '123474'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 27 июня 2018 года № 182. Зарегистрировано Департаментом юстиции Костанайской области 9 июля 2018 года № 7938. Утратило силу решением маслихата Сарыкольского района Костанайской области от 25 сентября 2023 года № 59 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 25 июня 2014 года № 182 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Севастопольского сельского округа Сарыкольского района Костанайской области»
    kaz: Мәслихаттың 2014 жылғы 25 маусымдағы № 182 «Қостанай облысы Сарыкөл ауданының Севастополь ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123474/rus
