act_code: '172200'
requisite: Решение маслихата города Костаная Костанайской области от 26 сентября 2022 года № 155. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 сентября 2022 года № 29878
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Костанай
  kaz: Қостанай қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-26
approved_by:
- '162002000002'
version_date:
  kaz: 2024-12-13
  rus: 2024-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/172200/kaz/13.12.2024
  rus: https://zan.gov.kz/client/#!/doc/172200/rus/13.12.2024
caused_by:
  code: '204242'
  requisite: Решение маслихата города Костаная Костанайской области от 13 декабря 2024 года № 137. Отменено решением маслихата города Костаная Костанайской области от 6 марта 2026 года № 223 (вступает в силу с момента принятия)
  title:
    rus: О внесении изменения в решение маслихата от 26 сентября 2022 года № 155 «Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Костанай»
    kaz: «Қостанай қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы» мәслихаттың 2022 жылғы 26 қыркүйектегі № 155 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204242/rus
