act_code: '104950'
requisite: Решение маслихата Костанайской области от 27 июня 2016 года № 42. Зарегистрировано Департаментом юстиции Костанайской области 28 июля 2016 года № 6562. Утратило силу решением маслихата Костанайской области от 15 марта 2017 года № 137
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "Аппарат Костанайского областного маслихата"
  kaz: '"Қостанай облыстық мәслихатының аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-27
approved_by:
- '162000000002'
version_date:
  kaz: 2016-06-27
  rus: 2016-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/104950/kaz/27.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104950/rus/27.06.2016
