act_code: '49641'
requisite: Қостанай облысы Науырзым ауданы мәслихатының 2009 жылғы 25 желтоқсандағы № 233 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда № 9-16-98 тіркелді
title:
  rus: Науырзым ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Науырзым ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '162014000002'
version_date:
  kaz: 2010-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/49641/kaz/08.07.2010
caused_by:
  code: '53624'
  requisite: Қостанай облысы Науырзым ауданы мәслихатының 2010 жылғы 8 шілдедегі № 285 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2010 жылғы 22 шілдеде № 9-16-109 тіркелді
  title:
    rus: '"Науырзым ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" мәслихаттың 2009 жылғы 25 желтоқсандағы № 233  шешіміне өзгерістер енгізу туралы'
    kaz: '"Науырзым ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" мәслихаттың 2009 жылғы 25 желтоқсандағы № 233  шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53624/rus
