act_code: '77778'
requisite: Решение акима Житикаринского района Костанайской области от 7 февраля 2014 года № 2. Зарегистрировано Департаментом юстиции Костанайской области 28 февраля 2014 года № 4462. Утратило силу решением акима Житикаринского района Костанайской области от 28 ноября 2017 года № 1
title:
  rus: Об образовании избирательных участков на территории Житикаринского района
  kaz: Жітіқара ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-07
approved_by:
- '162008000001'
version_date:
  kaz: 2015-10-23
  rus: 2015-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/77778/kaz/23.10.2015
  rus: https://zan.gov.kz/client/#!/doc/77778/rus/23.10.2015
caused_by:
  code: '94926'
  requisite: Решение акима Житикаринского района Костанайской области от 23 октября 2015 года № 7. Зарегистрировано Департаментом юстиции Костанайской области 29 октября 2015 года № 5972. Утратило силу решением акима Житикаринского района Костанайской области от 28 ноября 2017 года № 1
  title:
    rus: О внесении изменений и дополнений в решение от 7 февраля 2014 года № 2 "Об образовании избирательных участков на территории Житикаринского района"
    kaz: 2014 жылғы 7 ақпандағы № 2 "Жітіқара ауданының аумағында сайлау учаскелерін құру туралы" шешімге өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94926/rus
