act_code: '16268'
requisite: Решение акима города Аркалыка Костанайской области от 24 июня 2003 года № 16. Зарегистрировано Управлением юстиции Костанайской области 8 июля 2003 года № 2361. Утратило силу решением акима города Аркалыка Костанайской области от 19 мая 2006 года № 18
title:
  rus: Об утверждении положения о городской комиссии по инвентаризации имеющегося фонда защитных сооружений, предназначенных под противорадиационные укрытия
  kaz: Радиациядан тасалануға арналған қорғану ғимараттарын түгендеу жөніндегі қалалық комиссия туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2003-06-23
approved_by:
- '162019000003'
version_date:
  kaz: 2003-06-23
  rus: 2003-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/16268/kaz/23.06.2003
  rus: https://zan.gov.kz/client/#!/doc/16268/rus/23.06.2003
