act_code: '54684'
requisite: Решение акима села Карасу Карасуского района Костанайской области от 31 августа 2010 года № 4. Зарегистрировано Управлением юстиции Карасуского района Костанайской области 1 октября 2010 года № 9-13-115
title:
  rus: О переименовании улицы села Карасу
  kaz: Қарасу ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-31
approved_by:
- '162007010001'
version_date:
  kaz: 2020-11-04
  rus: 2020-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/54684/kaz/04.11.2020
  rus: https://zan.gov.kz/client/#!/doc/54684/rus/04.11.2020
caused_by:
  code: '148236'
  requisite: Решение акима Карасуского сельского округа Карасуского района Костанайской области от 4 ноября 2020 года № 13. Зарегистрировано Департаментом юстиции Костанайской области 6 ноября 2020 года № 9540
  title:
    rus: О внесении изменений в решение акима от 31 августа 2010 года № 4 «О переименовании улицы села Карасу»
    kaz: Әкімнің 2010 жылғы 31 тамыздағы № 4 «Қарасу ауылының көшесін атауын өзгерту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148236/rus
