act_code: '124922'
requisite: Решение маслихата Денисовского района Костанайской области от 4 сентября 2018 года № 222. Зарегистрировано Департаментом юстиции Костанайской области 27 сентября 2018 года № 8049. Утратило силу решением маслихата Денисовского района Костанайской области от 13 апреля 2022 года № 26 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-04
approved_by:
- '162006000002'
version_date:
  kaz: 2018-09-04
  rus: 2018-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/124922/kaz/04.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124922/rus/04.09.2018
