act_code: '122749'
requisite: Решение акима Боскольского сельского округа Карабалыкского района Костанайской области от 12 июня 2018 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 13 июня 2018 года № 7839
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-12
approved_by:
- '162010002002'
version_date:
  kaz: 2018-06-12
  rus: 2018-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/122749/kaz/12.06.2018
  rus: https://zan.gov.kz/client/#!/doc/122749/rus/12.06.2018
