act_code: '14963'
requisite: Решение маслихата Денисовского района Костанайской области от 28 февраля 2003 года № 15. Зарегистрировано Департаментом юстиции Костанайской области 18 марта 2003 года № 2099. Утратило силу решением маслихата Денисовского района Костанайской области от 7 марта 2007 года № 14
title:
  rus: Об утверждении Правил о порядке оказания помощи малообеспеченным семьям (гражданам) на оплату содержания жилища (кроме содержания индивидуального жилого дома) и потребления коммунальных услуг
  kaz: Табысы аз отбасыларға (азаматтарға) баспанасын ұстау (жеке меншік тұрғын үйді ұстаудан басқа) және коммуналдық қызметтерді пайдаланғаны үшін төлемін өтеу мақсатта көмек көрсету тәртібінің ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-02-28
approved_by:
- '162006000002'
version_date:
  kaz: 2003-02-28
  rus: 2003-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/14963/kaz/28.02.2003
  rus: https://zan.gov.kz/client/#!/doc/14963/rus/28.02.2003
