act_code: '98027'
requisite: Решение маслихата Костанайской области от 11 декабря 2015 года № 468. Зарегистрировано Департаментом юстиции Костанайской области 21 января 2016 года № 6157. Утратило силу решением маслихата Костанайской области от 12 ноября 2025 года № 251 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении Правил общего водопользования на водных объектах Костанайской области
  kaz: Қостанай облысының су объектілерінде ортақ су пайдалану қағидаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '162000000002'
version_date:
  kaz: 2021-06-21
  rus: 2021-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/98027/kaz/21.06.2021
  rus: https://zan.gov.kz/client/#!/doc/98027/rus/21.06.2021
caused_by:
  code: '156810'
  requisite: Решение маслихата Костанайской области от 21 июня 2021 года № 66. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 июля 2021 года № 23353. Утратило силу решением маслихата Костанайской области от 12 ноября 2025 года № 251 (вводится в действие после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 11 декабря 2015 года № 468 «Об установлении Правил общего водопользования на водных объектах Костанайской области»
    kaz: Мәслихаттың 2015 жылғы 11 желтоқсандағы № 468 «Қостанай облысының су объектілерінде ортақ су пайдалану қағидаларын белгілеу туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156810/rus
