act_code: '24612'
requisite: Решение маслихата Камыстинского района Костанайской области от 23 июня 2005 года № 120. Зарегистрировано Управлением юстиции Камыстинского района Костанайской области 29 июня 2005 года № 9-11-9. Утратило силу решением маслихата Камыстинского района Костанайской области от 2 июня 2010 года № 231
title:
  rus: О Правилах содержания собак, кошек и других животных на территории Камыстинского района
  kaz: Қамысты ауданының аумағындағы иттерді, мысықтарды және басқа жануарларды күтіп ұстау Ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-06-23
approved_by:
- '162009000002'
version_date:
  kaz: 2005-06-23
  rus: 2005-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/24612/kaz/23.06.2005
  rus: https://zan.gov.kz/client/#!/doc/24612/rus/23.06.2005
