act_code: '37192'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 21 декабря 2007 года № 23. Зарегистрировано Управлением юстиции Алтынсаринского района Костанайской области 26 января 2008 года № 9-5-56. Утратило силу решением маслихата Алтынсаринского района Костанайской области от 20 февраля 2008 года № 51
title:
  rus: Об утверждении правил благоустройства, санитарной очистки территории, содержания и защиты зеленых насаждений в населенных пунктах Алтынсаринского района
  kaz: Об утверждении правил благоустройства, санитарной очистки территории, содержания и защиты зеленых насаждений в населенных пунктах Алтынсаринского района
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-12-21
approved_by:
- '162003000002'
version_date:
  rus: 2007-12-21
source:
  rus: https://zan.gov.kz/client/#!/doc/37192/rus/21.12.2007
