act_code: '44045'
requisite: Решение акима города Аркалыка Костанайской области от 29 января 2009 года № 8. Зарегистрировано Управлением юстиции города Аркалыка Костанайской области 4 февраля 2009 года № 9-3-103
title:
  rus: Об организации и обеспечении приписки граждан мужского пола 1992 года к призывному участку в 2009 году
  kaz: 2009 жылы шақыру учаскесіне 1992 жылы туған еркек жынысты азаматтардың тіркелуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '162019000001'
version_date:
  kaz: 2009-01-29
  rus: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44045/kaz/29.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44045/rus/29.01.2009
