act_code: '50754'
requisite: Решение маслихата города Рудного Костанайской области от 8 февраля 2010 года № 287. Зарегистрировано Управлением юстиции города Рудного Костанайской области 17 февраля 2010 года № 9-2-153. Утратило силу решением маслихата города Рудного Костанайской области от 4 мая  2016 года № 19
title:
  rus: О корректировке базовых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-08
approved_by:
- '162021000002'
version_date:
  kaz: 2010-02-08
  rus: 2010-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/50754/kaz/08.02.2010
  rus: https://zan.gov.kz/client/#!/doc/50754/rus/08.02.2010
