act_code: '104344'
requisite: Решение маслихата Костанайского района Костанайской области от 6 июня 2016 года № 30. Зарегистрировано Департаментом юстиции Костанайской области 5 июля 2016 года № 6530. Утратило силу решением маслихата Костанайского района Костанайской области от 17 июля 2020 года № 545 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил о дополнительном регламентировании проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткiзуді қосымша реттеу туралы қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-06-06
approved_by:
- '162012000002'
version_date:
  kaz: 2020-03-12
  rus: 2020-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/104344/kaz/12.03.2020
  rus: https://zan.gov.kz/client/#!/doc/104344/rus/12.03.2020
caused_by:
  code: '140596'
  requisite: Решение маслихата Костанайского района Костанайской области от 12 марта 2020 года № 500. Зарегистрировано Департаментом юстиции Костанайской области 27 марта 2020 года № 9048. Утратило силу решением маслихата Костанайского района Костанайской области от 17 июля 2020 года № 545 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 6 июня 2016 года № 30 «Об утверждении Правил о дополнительном регламентировании проведения собраний, митингов, шествий, пикетов и демонстраций»
    kaz: Мәслихаттың 2016 жылғы 6 маусымдағы № 30 «Жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткiзуді қосымша реттеу туралы қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140596/rus
