act_code: '210097'
requisite: Решение акима сельского округа имени Мариям Хәкімжановой Алтынсаринского района Костанайской области от 8 мая 2025 года № 5
title:
  rus: Об установлении публичного сервитута АО «Казахтелеком»
  kaz: «Казахтелеком» АҚ қоғамдық сервитутын орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-08
approved_by:
- '162003009002'
version_date:
  kaz: 2025-05-08
  rus: 2025-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/210097/kaz/08.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210097/rus/08.05.2025
