act_code: '704'
requisite: Решение акима Костанайской области от 27 мая 1998 года № 86. Зарегистрировано Управлением юстиции Костанайской области 4 июня 1998 года № 16.  Утратило силу решением акима Костанайской области от 26 февраля 2005 года № 13
title:
  rus: О закреплении и комплексном использовании рыбохозяйственных водоемов
  kaz: Балық шаруашылығы су айдындарын бекіту және кешенді пайдалану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-26
approved_by:
- '162000000003'
version_date:
  kaz: 1998-05-26
  rus: 1998-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/704/kaz/26.05.1998
  rus: https://zan.gov.kz/client/#!/doc/704/rus/26.05.1998
