act_code: '177924'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 27 декабря 2022 года № 135
title:
  rus: О районном бюджете Алтынсаринского района на 2023-2025 годы
  kaz: Алтынсарин ауданының 2023–2025 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '162003000002'
version_date:
  kaz: 2023-11-23
  rus: 2023-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/177924/kaz/23.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177924/rus/23.11.2023
caused_by:
  code: '189433'
  requisite: Решение маслихата Алтынсаринского района Костанайской области от 23 ноября 2023 года № 41
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2022 года № 135 «О районном бюджете Алтынсаринского района на 2023-2025 годы»
    kaz: Мәслихаттың «Алтынсарин ауданының 2023-2025 жылдарға арналған аудандық бюджеті туралы» 2022 жылғы 27 желтоқсандағы № 135 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189433/rus
