act_code: '44492'
requisite: Решение маслихата Тарановского района Костанайской области от 29 января 2009 года № 155. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 26 февраля 2009 года № 9-18-80. Утратило силу решением маслихата Тарановского района Костанайской области от 28 апреля 2015 года № 278
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, ветеринарии, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметші болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '162016000002'
version_date:
  kaz: 2009-09-24
  rus: 2009-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/44492/kaz/24.09.2009
  rus: https://zan.gov.kz/client/#!/doc/44492/rus/24.09.2009
caused_by:
  code: '48092'
  requisite: Решение маслихата Тарановского района Костанайской области от 24 сентября 2009 года № 211. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 9 октября № 9-18-97. Утратило силу решением маслихата Тарановского района Костанайской области от 28 апреля 2015 года № 278
  title:
    rus: О внесении дополнения в решение от 29 января 2009 года № 155 "Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок гражданским служащим социального обеспечения, образования, культуры, работающим в аульной (сельской) местности"
    kaz: '"Ауылдық (селолық) жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамтамасыздандыру, білім беру, мәдениет азаматтық қызметшілеріне жиырма бес пайызға жоғары лауазымдық жалақылар мен тарифтік ставкаларды белгілеу туралы" 2009 жылғы 29 қаңтардағы № 155 шешіміне толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/48092/rus
