act_code: '31591'
requisite: Решение маслихата города Рудного Костанайской области от 15 января 2007 года № 401. Зарегистрировано Управлением юстиции города Рудного Костанайской области 29 января 2007 года № 9-2-70. Срок действия решения - до 1 января 2008 года
title:
  rus: Об установлении размеров ставок фиксированного суммарного налога по игорному бизнесу с единицы объекта налогообложения в год и ставок акциза на объекты игорного бизнеса на 2007 год
  kaz: Бір салық салу объектісінен жылына ойын бизнесі бойынша тіркелген сомалық салық ставкаларының және ойын бизнесі объектісіне акциздер ставкаларының 2007 жылға арналған мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-15
approved_by:
- '162021000002'
version_date:
  kaz: 2007-01-15
  rus: 2007-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/31591/kaz/15.01.2007
  rus: https://zan.gov.kz/client/#!/doc/31591/rus/15.01.2007
