act_code: '187244'
requisite: Решение маслихата Карасуского района Костанайской области от 12 октября 2023 года № 65
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Ильичевского сельского округа Карасуского района Костанайской области
  kaz: Қостанай облысы Қарасу ауданы Ильичев ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-12
approved_by:
- '162011000002'
version_date:
  kaz: 2026-02-17
  rus: 2026-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/187244/kaz/17.02.2026
  rus: https://zan.gov.kz/client/#!/doc/187244/rus/17.02.2026
caused_by:
  code: '222162'
  requisite: Решение маслихата Карасуского района Костанайской области от 17 февраля 2026 года № 298
  title:
    rus: О внесении изменений в решение маслихата Карасуского района Костанайской области от 12 октября 2023 года № 65 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Ильичевского сельского округа Карасуского района Костанайской области»
    kaz: «Қостанай облысы Қарасу ауданы Ильич ауылдық округінің жергілікті қоғамдастық жиынына қатысу үшін бөлек жергілікті қоғамдастық жиындарын және ауыл тұрғындары өкілдерінің сандық құрамын өткізу қағидаларын бекіту туралы» Қостанай облысы Қарасу аудандық мәслихатының 2023 жылғы 12 қазандағы № 65 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222162/rus
