act_code: '25677'
requisite: Решение Костанайского областного маслихата от 23 сентября 2005 года № 227. Зарегистрировано Департаментом юстиции Костанайской области 11 октября 2005 года за № 3510. Утратило силу решением маслихата Костанайской области от 19 июля 2012 года № 61
title:
  rus: О предоставлении бесплатного или льготного проезда гражданам за пределы территории Костанайской области по Республике Казахстан, направленным на лечение в лечебно-профилактические и другие учреждения здравоохранения
  kaz: Қазақстан Республикасы бойынша Қостанай облысы аумағынан тыс жерлерге емдеу-профилактикалық және басқа денсаулық сақтау мекемелеріне жіберген азаматтарға тегін немесе жеңілдікпен жол жүрулеріне көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-09-23
approved_by:
- '162000000002'
version_date:
  kaz: 2008-07-11
  rus: 2008-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/25677/kaz/11.07.2008
  rus: https://zan.gov.kz/client/#!/doc/25677/rus/11.07.2008
caused_by:
  code: '41152'
  requisite: Решение маслихата Костанайской области от 11 июля 2008 года № 115. Зарегистрировано департаментом юстиции Костанайской области 8 августа 2008 года № 3647. Утратило силу решением маслихата Костанайской области от 19 июля 2012 года № 61
  title:
    rus: О внесении изменений и дополнений в решение от 23 сентября 2005 года № 227 "О предоставлении бесплатного или льготного проезда гражданам за пределы территории Костанайской области по Республике Казахстан, направленным на лечение в лечебно-профилактические и другие учреждения здравоохранения"
    kaz: 2005 жылғы 23 қыркүйектегі № 227 "Қазақстан Республикасы бойынша Қостанай облысы аумағынан тыс жерлерге емдеу-профилактикалық және басқа денсаулық сақтау мекемелеріне жіберілген азаматтарға тегін немесе жеңілдікпен жол жүрулеріне көмек көрсету туралы" шешімге өзгерістер пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/41152/rus
