act_code: '218456'
requisite: Решение маслихата города Аркалыка Костанайской области от 5 декабря 2025 года № 193
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума на 2025 год по городу Аркалыку
  kaz: Арқалық қаласы бойынша 2025 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-05
approved_by:
- '162019000002'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/218456/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218456/rus/05.12.2025
