act_code: '52541'
requisite: Решение акима Узункольского района Костанайской области от 4 мая 2010 года № 11. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 17 мая 2010 года № 9-19-130
title:
  rus: О переименовании улицы в селе Узунколь
  kaz: Ұзынкөл ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-04
approved_by:
- '162017000003'
version_date:
  kaz: 2014-03-07
  rus: 2014-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/52541/kaz/07.03.2014
  rus: https://zan.gov.kz/client/#!/doc/52541/rus/07.03.2014
caused_by:
  code: '78837'
  requisite: Решение акима Узункольского сельского округа Узункольского района Костанайской области от 7 марта 2014 года № 01-р. Зарегистрировано Департаментом юстиции Костанайской области 10 апреля 2014 года № 4574
  title:
    rus: О внесении изменения в решение акима села Узунколь от 4 мая 2010 года № 11 "О переименовании улицы в селе Узунколь"
    kaz: Ұзынкөл ауылы әкімінің 2010 жылғы 4 мамырдағы № 11 "Ұзынкөл селосындағы көшені қайта атау туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/78837/rus
