act_code: '138101'
requisite: Решение маслихата Джангельдинского района Костанайской области от 30 декабря 2019 года № 272. Зарегистрировано Департаментом юстиции Костанайской области 10 января 2020 года № 8872
title:
  rus: Об утверждении Регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-12-30
approved_by:
- '162007000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/138101/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/138101/rus/30.12.2019
