act_code: '206020'
requisite: Решение маслихата Сарыкольского района Костанайской области от 27 декабря 2024 года № 243
title:
  rus: О районном бюджете Сарыкольского района на 2025-2027 годы
  kaz: Сарыкөл ауданының 2025-2027 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '162015000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206020/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206020/rus/27.12.2024
