act_code: '50434'
requisite: Решение маслихата города Рудного Костанайской области от 23 декабря 2009 года № 275. Зарегистрировано Управлением юстиции города Рудного Костанайской области 27 января 2010 года № 9-2-152. Утратило силу - Решением маслихата города Рудного Костанайской области от 22 января 2013 года № 98
title:
  rus: Об установлении стоимости разовых талонов
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '162021000002'
version_date:
  kaz: 2009-12-23
  rus: 2009-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/50434/kaz/23.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50434/rus/23.12.2009
