act_code: '151922'
requisite: Решение маслихата Карабалыкского района Костанайской области от 8 января 2021 года № 562. Зарегистрировано Департаментом юстиции Костанайской области 15 января 2021 года № 9719
title:
  rus: О бюджетах сел, поселка, сельских округов Карабалыкского района на 2021-2023 годы
  kaz: Қарабалық ауданы ауылдарының, кентінің, ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '162010000002'
version_date:
  kaz: 2021-02-22
  rus: 2021-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/151922/kaz/22.02.2021
  rus: https://zan.gov.kz/client/#!/doc/151922/rus/22.02.2021
caused_by:
  code: '153136'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 22 февраля 2021 года № 18. Зарегистрировано Департаментом юстиции Костанайской области 24 февраля 2021 года № 9789
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 8 января 2021 года № 562 «О бюджетах сел, поселка, сельских округов Карабалыкского района на 2021-2023 годы»
    kaz: Мәслихаттың 2021 жылғы 8 қаңтардағы № 562 «Қарабалық ауданы ауылдарының, кентінің, ауылдық округтерінің 2021-2023 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер мен толықтыруларды енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153136/rus
