act_code: '54011'
requisite: Қостанай облысы Меңдіқара ауданы Боровской селосы әкімінің 2010 жылғы 29 шілдедегі № 8 шешімі. Қостанай облысы Меңдіқара ауданының Әділет басқармасында 2010 жылғы 13 тамызда № 9-15-135 тіркелді
title:
  rus: Заводская, СПТУ-19, 25 лет Целины көшелерін Нұрахмет Қосаев атындағы көшеге қайта атау туралы
  kaz: Заводская, СПТУ-19, 25 лет Целины көшелерін Нұрахмет Қосаев атындағы көшеге қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-29
approved_by:
- '162013013001'
version_date:
  kaz: 2010-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/54011/kaz/29.07.2010
