act_code: '127701'
requisite: Решение маслихата Камыстинского района Костанайской области от 25 декабря 2018 года № 212. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8205
title:
  rus: О районном бюджете Камыстинского района на 2019-2021 годы
  kaz: Қамысты ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '162009000002'
version_date:
  kaz: 2019-02-15
  rus: 2019-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/127701/kaz/15.02.2019
  rus: https://zan.gov.kz/client/#!/doc/127701/rus/15.02.2019
caused_by:
  code: '129171'
  requisite: Решение маслихата Камыстинского района Костанайской области от 15 февраля 2019 года № 229. Зарегистрировано Департаментом юстиции Костанайской области 20 февраля 2019 года № 8267
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2018 года № 212 «О районном бюджете Камыстинского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 25 желтоқсандағы № 212 «Қамысты ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129171/rus
