act_code: '159762'
requisite: Решение маслихата Федоровского района Костанайской области от 11 октября 2021 года № 58. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 октября 2021 года № 24914
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Федоровском районе
  kaz: Федоров ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-10-11
approved_by:
- '162018000002'
version_date:
  kaz: 2022-05-04
  rus: 2022-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/159762/kaz/04.05.2022
  rus: https://zan.gov.kz/client/#!/doc/159762/rus/04.05.2022
caused_by:
  code: '167334'
  requisite: Решение маслихата Федоровского района Костанайской области от 4 мая 2022 года № 127. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 мая 2022 года № 27895
  title:
    rus: О внесении изменений в решение маслихата от 11 октября 2021 года № 58 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Федоровском районе»
    kaz: Мәслихаттың 2021 жылғы 11 қазандағы № 58 «Федоров ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167334/rus
