act_code: '77875'
requisite: Решение акима Джангельдинского района Костанайской области от 3 февраля 2014 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 5 марта 2014 года № 4473
title:
  rus: Об образовании избирательных участков на территории Джангельдинского района
  kaz: Жангелдин ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-03
approved_by:
- '162007000003'
version_date:
  kaz: 2015-02-20
  rus: 2015-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/77875/kaz/20.02.2015
  rus: https://zan.gov.kz/client/#!/doc/77875/rus/20.02.2015
caused_by:
  code: '87821'
  requisite: Решение акима Джангельдинского района Костанайской области от 20 февраля 2015 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 17 марта 2015 года № 5424
  title:
    rus: О внесений изменения в решение акима от 3 февраля 2014 года № 1 "Об образовании избирательных участков на территории Джангельдинского района"
    kaz: Әкімнің 2014 жылғы 3 ақпандағы № 1 "Жангелдин ауданының аумағында сайлау учаскелерін құру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87821/rus
