act_code: '137705'
requisite: Решение маслихата Костанайского района Костанайской области от 30 декабря 2019 года № 460. Зарегистрировано Департаментом юстиции Костанайской области 31 декабря 2019 года № 8857
title:
  rus: О районном бюджете Костанайского района на 2020-2022 годы
  kaz: Қостанай ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '162012000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137705/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137705/rus/30.12.2019
