act_code: '137655'
requisite: Решение маслихата Житикаринского района Костанайской области от 30 декабря 2019 года № 370. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2019 года № 8854
title:
  rus: О районном бюджете Житикаринского района на 2020-2022 годы
  kaz: Жітіқара ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '162008000002'
version_date:
  kaz: 2020-11-04
  rus: 2020-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/137655/kaz/04.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137655/rus/04.11.2020
caused_by:
  code: '148285'
  requisite: Решение маслихата Житикаринского района Костанайской области от 4 ноября 2020 года № 449. Зарегистрировано Департаментом юстиции Костанайской области 9 ноября 2020 года № 9542
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 30 декабря 2019 года № 370 «О районном бюджете Житикаринского района на 2020-2022 годы»
    kaz: Мәслихаттың 2019 жылғы 30 желтоқсандағы № 370 «Жітіқара ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148285/rus
