act_code: '137725'
requisite: Решение маслихата Джангельдинского района Костанайской области от 30 декабря 2019 года № 271. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2019 года № 8851
title:
  rus: О районном бюджете Джангельдинского района на 2020-2022 годы
  kaz: Жангелдин ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '162007000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137725/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137725/rus/30.12.2019
