act_code: '205865'
requisite: Решение маслихата Карасуского района Костанайской области от 30 декабря 2024 года № 192
title:
  rus: О районном бюджете Карасуского района на 2025-2027 годы
  kaz: Қарасу ауданының 2025-2027 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162011000002'
version_date:
  kaz: 2025-07-23
  rus: 2025-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205865/kaz/23.07.2025
  rus: https://zan.gov.kz/client/#!/doc/205865/rus/23.07.2025
caused_by:
  code: '212794'
  requisite: Решение маслихата Карасуского района Костанайской области от 23 июля 2025 года № 242
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2024 года № 192 «О районном бюджете Карасуского района на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 30 желтоқсандағы № 192 «Қарасу ауданының 2025-2027 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212794/rus
