act_code: '78841'
requisite: Решение маслихата Джангельдинского района Костанайской области от 28 февраля 2014 года № 147. Зарегистрировано Департаментом юстиции Костанайской области 10 апреля 2014 года № 4580. Утратило силу решением маслихата Джангельдинского района Костанайской области от 31 мая 2022 года № 110 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Акшыганакского сельского округа Джангельдинского района Костанайской области
  kaz: Қостанай облысы Жангелдин ауданының Ақшығанақ ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысатын ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-28
approved_by:
- '162007000002'
version_date:
  kaz: 2017-04-20
  rus: 2017-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/78841/kaz/20.04.2017
  rus: https://zan.gov.kz/client/#!/doc/78841/rus/20.04.2017
caused_by:
  code: '111915'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 20 апреля 2017 года № 89. Зарегистрировано Департаментом юстиции Костанайской области 4 мая 2017 года № 7024. Утратило силу решением маслихата Джангельдинского района Костанайской области от 31 мая 2022 года № 110 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 28 февраля 2014 года № 147 «Об утверждении Правил проведения раздельных сходов местного сообщества  и количественного состава представителей жителей сел для участия в сходе местного сообщества Акшыганакского сельского округа Джангельдинского района Костанайской области»
    kaz: Мәслихаттың 2014 жылғы 28 ақпандағы № 147 «Қостанай облысы Жангелдин ауданының Ақшығанақ ауылдық округінде  бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті  қоғамдастық жиындарына қатысатын ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111915/rus
