act_code: '146997'
requisite: Решение маслихата Житикаринского района Костанайской области от 4 сентября 2020 года № 438. Зарегистрировано Департаментом юстиции Костанайской области 2 октября 2020 года № 9478. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 93 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-09-04
approved_by:
- '162008000002'
version_date:
  kaz: 2022-04-08
  rus: 2022-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/146997/kaz/08.04.2022
  rus: https://zan.gov.kz/client/#!/doc/146997/rus/08.04.2022
caused_by:
  code: '166809'
  requisite: Решение маслихата Житикаринского района Костанайской области от 8 апреля 2022 года № 152. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 апреля 2022 года № 27674. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 93 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 04 сентября 2020 года № 438 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2020 жылғы 04 қыркүйектегі № 438 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166809/rus
