act_code: '26281'
requisite: Решение Костанайского областного маслихата от 6 декабря 2005 года № 258. Зарегистрировано Департаментом юстиции Костанайской области 20 декабря 2005 года № 3529. Срок действия решения до 1 января 2007 года
title:
  rus: Об областном бюджете Костанайской области на 2006 год
  kaz: Қостанай облысының 2006 жылға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '162000000002'
version_date:
  kaz: 2005-12-06
  rus: 2005-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26281/kaz/06.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26281/rus/06.12.2005
