act_code: '206041'
requisite: Решение маслихата Житикаринского района Костанайской области от 30 декабря 2024 года № 250
title:
  rus: О бюджете Тохтаровского сельского округа Житикаринского района на 2025-2027 годы
  kaz: Жітіқара ауданы Тоқтаров ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162008000002'
version_date:
  kaz: 2025-03-14
  rus: 2025-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/206041/kaz/14.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206041/rus/14.03.2025
caused_by:
  code: '208188'
  requisite: Решение маслихата Житикаринского района Костанайской области от 14 марта 2025 года № 274
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 30 декабря 2024 года № 250 «О бюджете Тохтаровского сельского округа Житикаринского района на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 30 желтоқсандағы № 250 «Жітіқара ауданы Тоқтаров ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208188/rus
