act_code: '221222'
requisite: Решение маслихата Наурзумского района Костанайской области от 8 января 2026 года № 271
title:
  rus: О бюджете села Раздольное Наурзумского района на 2026-2028 годы
  kaz: Науырзым ауданы Раздольное ауылының 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-08
approved_by:
- '162014000002'
version_date:
  kaz: 2026-05-15
  rus: 2026-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/221222/kaz/15.05.2026
  rus: https://zan.gov.kz/client/#!/doc/221222/rus/15.05.2026
caused_by:
  code: '225277'
  requisite: Решение маслихата Наурзумского района Костанайской области от 15 мая 2026 года № 302
  title:
    rus: О внесении изменений в решение Наурзумского районного маслихата от 8 января 2026 года № 271 «О бюджете села Раздольное Наурзумского района на 2026-2028 годы»
    kaz: Науырзым аудандық мәслихатының 2026 жылғы 8 қаңтардағы № 271 «Науырзым ауданы Раздольное ауылының 2026-2028 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225277/rus
