act_code: '161753'
requisite: Решение маслихата Костанайской области от 15 декабря 2021 года № 139. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 декабря 2021 года № 25799
title:
  rus: Об областном бюджете Костанайской области на 2022-2024 годы
  kaz: Қостанай облысының 2022-2024 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-15
approved_by:
- '162000000002'
version_date:
  kaz: 2022-01-17
  rus: 2022-01-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/161753/kaz/17.01.2022
  rus: https://zan.gov.kz/client/#!/doc/161753/rus/17.01.2022
caused_by:
  code: '163848'
  requisite: Решение маслихата Костанайской области от 17 января 2022 года № 141. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 января 2022 года № 26552
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 15 декабря 2021 года № 139 «Об областном бюджете Костанайской области на 2022-2024 годы»
    kaz: Мәслихаттың 2021 жылғы 15 желтоқсандағы № 139 «Қостанай облысының 2022-2024 жылдарға арналған облыстық бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/163848/rus
