act_code: '131985'
requisite: Решение акима Кумкешуского сельского округа Амангельдинского района Костанайской области от 24 мая 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 28 мая 2019 года № 8486. Утратило силу решением акима Кумкешуского сельского округа Амангельдинского района Костанайской области от 19 октября 2021 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении публичного сервитута на земельные участки
  kaz: Жер учаскелеріне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-24
approved_by:
- '162004006002'
version_date:
  kaz: 2019-05-24
  rus: 2019-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/131985/kaz/24.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131985/rus/24.05.2019
