act_code: '42997'
requisite: Решение маслихата Тарановского района Костанайской области от 25 декабря 2008 года № 147. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 29 декабря 2008 года № 9-18-75
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '162016000002'
version_date:
  kaz: 2008-12-25
  rus: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/42997/kaz/25.12.2008
  rus: https://zan.gov.kz/client/#!/doc/42997/rus/25.12.2008
