act_code: '206281'
requisite: Решение маслихата города Рудного Костанайской области от 31 декабря 2024 года № 192
title:
  rus: О бюджетах поселков Горняцкий и Качар на 2025-2027 годы
  kaz: Горняцк және Қашар кенттерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '162021000002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/206281/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206281/rus/09.09.2025
caused_by:
  code: '214145'
  requisite: Решение маслихата города Рудного Костанайской области от 9 сентября 2025 года № 240
  title:
    rus: О внесении изменений в решение маслихата от 31 декабря 2024 года № 192 «О бюджетах поселков Горняцкий и Качар на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 31 желтоқсандағы № 192 «Горняцк және Қашар кенттерінің 2025-2027 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214145/rus
