act_code: '91461'
requisite: Решение маслихата Федоровского района Костанайской области от 10 июня 2015 года № 335. Зарегистрировано Департаментом юстиции Костанайской области 7 июля 2015 года № 5724. Утратило силу решением маслихата Федоровского района Костанайской области от 14 февраля 2018 года № 206
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-10
approved_by:
- '162018000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/91461/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/91461/rus/01.04.2016
caused_by:
  code: '102273'
  requisite: Решение маслихата Федоровского района Костанайской области от 1 апреля 2016 года № 13. Зарегистрировано Департаментом юстиции Костанайской области 6 мая 2016 года № 6325. Утратило силу решением маслихата Федоровского района Костанайской области от 14 февраля 2018 года № 206
  title:
    rus: О внесении изменения в решение маслихата от 10 июня 2015 года № 335 "О повышении базовых ставок земельного налога"
    kaz: Мәслихаттың 2015 жылғы 10 маусымдағы № 335 "Жер салығының базалық мөлшерлемелерін жоғарылату туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102273/rus
