act_code: '36300'
requisite: Решение маслихата города Костаная Костанайской области от 14 декабря 2007 года № 26. Зарегистрировано управлением юстиции города Костаная Костанайской области 26 декабря 2007 года № 9-1-93
title:
  rus: О бюджете города Костаная на 2008 год
  kaz: Қостанай қаласының 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-14
approved_by:
- '162002000002'
version_date:
  rus: 2008-01-16
source:
  rus: https://zan.gov.kz/client/#!/doc/36300/rus/16.01.2008
caused_by:
  code: '37030'
  requisite: Решение маслихата города Костаная Костанайской области от 16 января 2008 года № 41. Зарегистрировано Управлением юстиции города Костаная Костанайской области 23 января 2008 года № 9-1-96
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 14 декабря 2007 года № 26 "О бюджете города Костаная на 2008 год"
    kaz: '"Қостанай қаласының 2008 жылға арналған бюджеті туралы" мәслихаттың 2007 жылғы 14 желтоқсандағы № 26 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/37030/rus
