act_code: '69688'
requisite: Решение маслихата Федоровского района Костанайской области от 20 декабря 2012 года № 75. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2012 года № 3973
title:
  rus: О районном бюджете Федоровского района на 2013-2015 годы
  kaz: Федоров ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '162018000002'
version_date:
  kaz: 2013-12-12
  rus: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/69688/kaz/12.12.2013
  rus: https://zan.gov.kz/client/#!/doc/69688/rus/12.12.2013
caused_by:
  code: '75895'
  requisite: Решение маслихата Федоровского района Костанайской области от 12 декабря 2013 года № 181. Зарегистрировано Департаментом юстиции Костанайской области 13 декабря 2013 года № 4353
  title:
    rus: О внесении изменений в решение маслихата от 20 декабря 2012 года № 75 "О районном бюджете Федоровского района на 2013-2015 годы"
    kaz: Мәслихаттың 2012 жылғы 20 желтоқсандағы № 75 "Федоров ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75895/rus
