act_code: '178895'
requisite: Решение акима села Алтынсарино Камыстинского района Костанайской области от 20 февраля 2023 года № 3-р
title:
  rus: Об установлении публичного сервитута государственному учреждению «Управление энергетики и жилищно-коммунального хозяйства акимата Костанайской области»
  kaz: Қостанай облысы әкімдігінің «Энергетика және тұрғын үй-коммуналдық шаруашылығы басқармасы» мемлекеттік мекемесіне қауымдық сервитут орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-02-20
approved_by:
- '162009002002'
version_date:
  kaz: 2023-02-20
  rus: 2023-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/178895/kaz/20.02.2023
  rus: https://zan.gov.kz/client/#!/doc/178895/rus/20.02.2023
