act_code: '109148'
requisite: Решение маслихата Карасуского района Костанайской области от 12 декабря 2016 года № 68. Зарегистрировано Департаментом юстиции Костанайской области 11 января 2017 года № 6800. Утратило силу решением маслихата Карасуского района Костанайской области от 22 мая 2018 года № 234
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Карасускому району
  kaz: Қарасу ауданы бойынша коммуналдық қалдықтардың  түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2016-12-12
approved_by:
- '162011000002'
version_date:
  kaz: 2016-12-12
  rus: 2016-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/109148/kaz/12.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109148/rus/12.12.2016
