act_code: '229449'
requisite: Решение Карабалыкского районного маслихата Костанайской области от 21 августа 2026 года № 285
title:
  rus: «Об утверждении Положения о государственном учреждении «Аппарат Карабалыкского районного маслихата»
  kaz: «Қарабалық аудандық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы»
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-08-21
approved_by:
- '162010000002'
version_date:
  kaz: 2026-08-21
  rus: 2026-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/229449/kaz/21.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229449/rus/21.08.2026
