act_code: '4870'
requisite: Решение акима Костанайской области от 14 октября 1999 года № 229. Зарегистрировано Управлением юстиции Костанайской области 20 ноября 1999 года № 140.  Утратило силу постановлением акимата Костанайской области от 27 сентября 2001 года № 137
title:
  rus: Об утверждении Правил использования средств резерва акима Костанайской области
  kaz: Қостанай облысы әкімі резервінің қаражатын пайдаланудың Ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 1999-10-13
approved_by:
- '162000000003'
version_date:
  kaz: 1999-10-13
  rus: 1999-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/4870/kaz/13.10.1999
  rus: https://zan.gov.kz/client/#!/doc/4870/rus/13.10.1999
