act_code: '41288'
requisite: Решение Костанайского областного маслихата от 11 июля 2008 года № 112. Зарегистрировано Департаментом юстиции Костанайской области 21 августа 2008 года № 3651. Утратило силу решением маслихата Костанайской области от 31 июля 2009 года № 222
title:
  rus: Об утверждении правил забора воды из поверхностных и подземных водных объектов при нецентрализованном питьевом и хозяйственно-бытовом водоснабжении населения
  kaz: Халықты орталықтандырылмаған ауыз сумен және шаруашылық-тұрмыстық сумен жабдықтау кезінде жер үсті және жер асты су объектілерінен су алу ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-07-11
approved_by:
- '162000000002'
version_date:
  kaz: 2008-07-11
  rus: 2008-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/41288/kaz/11.07.2008
  rus: https://zan.gov.kz/client/#!/doc/41288/rus/11.07.2008
