act_code: '110539'
requisite: Решение маслихата Амангельдинского района Костанайской области от 23 февраля 2017 года № 97. Зарегистрировано Департаментом юстиции Костанайской области 16 марта 2017 года № 6915. Утратило силу решением маслихата Амангельдинского района Костанайской области от 21 сентября 2020 года № 402 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-02-23
approved_by:
- '162004000002'
version_date:
  kaz: 2020-02-05
  rus: 2020-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/110539/kaz/05.02.2020
  rus: https://zan.gov.kz/client/#!/doc/110539/rus/05.02.2020
caused_by:
  code: '139365'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 5 февраля 2020 года № 349. Зарегистрировано Департаментом юстиции Костанайской области 6 февраля 2020 года № 8952. Утратило силу решением маслихата Амангельдинского района Костанайской области от 21 сентября 2020 года № 402 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 23 февраля 2017 года № 97 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2017 жылғы 23 ақпандағы № 97 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/139365/rus
