act_code: '127389'
requisite: Решение маслихата Наурзумского района Костанайской области от 26 декабря 2018 года № 243. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8206
title:
  rus: О бюджете Карамендинского сельского округа Наурзумского района на 2019-2021 годы
  kaz: Науырзым ауданы Қарамеңді ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '162014000002'
version_date:
  kaz: 2018-12-26
  rus: 2018-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/127389/kaz/26.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127389/rus/26.12.2018
