act_code: '163602'
requisite: Решение маслихата Сарыкольского района Костанайской области от 10 января 2022 года № 85
title:
  rus: О бюджете поселка Сарыколь Сарыкольского района Костанайской области на 2022-2024 годы
  kaz: Қостанай облысы Сарыкөл ауданы Сарыкөл кентінің 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-10
approved_by:
- '162015000002'
version_date:
  kaz: 2022-03-10
  rus: 2022-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/163602/kaz/10.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163602/rus/10.03.2022
caused_by:
  code: '165347'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 10 марта 2022 года № 124
  title:
    rus: О внесении изменений в решение маслихата от 10 января 2022 года № 85 «О бюджете поселка Сарыколь Сарыкольского района Костанайской области на 2022-2024 годы»
    kaz: Мәслихаттың 2022 жылғы 10 қаңтардағы № 85 «Қостанай облысы Сарыкөл ауданы Сарыкөл кентінің 2022-2024 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165347/rus
