act_code: '85660'
requisite: Решение маслихата города Рудного Костанайской области от 25 декабря 2014 года № 342. Зарегистрировано Департаментом юстиции Костанайской области 31 декабря 2014 года № 5272
title:
  rus: О городском бюджете города Рудного на 2015-2017 годы
  kaz: Рудный қаласының 2015-2017 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '162021000002'
version_date:
  kaz: 2015-09-22
  rus: 2015-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/85660/kaz/22.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85660/rus/22.09.2015
caused_by:
  code: '94040'
  requisite: Решение маслихата города Рудного Костанайской области от 22 сентября 2015 года № 442. Зарегистрировано Департаментом юстиции Костанайской области 29 сентября 2015 года № 5916
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2014 года № 342 "О городском бюджете города Рудного на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 25 желтоқсандағы № 342 "Рудный қаласының 2015-2017 жылдарға арналған қалалық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94040/rus
