act_code: '205877'
requisite: Решение маслихата Наурзумского района Костанайской области от 5 января 2025 года № 171
title:
  rus: О бюджете Дамдинского сельского округа Наурзумского района на 2025-2027 годы
  kaz: Науырзым ауданы Дәмді ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '162014000002'
version_date:
  kaz: 2025-02-17
  rus: 2025-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/205877/kaz/17.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205877/rus/17.02.2025
caused_by:
  code: '207182'
  requisite: Решение маслихата Наурзумского района Костанайской области от 17 февраля 2025 года № 185
  title:
    rus: О внесении изменений в решение Наурзумского районного маслихата от 5 января 2025 года № 171 «О бюджете Дамдинского сельского округа Наурзумского района на 2025-2027 годы»
    kaz: Мәслихаттың 2025 жылғы 5 қаңтардағы № 171 «Науырзым ауданы Дәмді ауылдық оркругінің 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207182/rus
