act_code: '187169'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 13 октября 2023 года № 68
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Михайловского сельского округа Мендыкаринского района Костанайской области
  kaz: Қостанай облысы Меңдіқара ауданы Михайлов ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-13
approved_by:
- '162013000002'
version_date:
  kaz: 2024-05-14
  rus: 2024-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/187169/kaz/14.05.2024
  rus: https://zan.gov.kz/client/#!/doc/187169/rus/14.05.2024
caused_by:
  code: '196663'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 14 мая 2024 года № 116
  title:
    rus: О внесении изменений в решение маслихата от 13 октября 2023 года № 68 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Михайловского сельского округа Мендыкаринского района Костанайской области»
    kaz: Мәслихаттың 2023 жылғы 13 қазандағы № 68 «Қостанай облысы Меңдіқара ауданы Михайлов ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196663/rus
