act_code: '193227'
requisite: Решение акима города Костаная Костанайской области от 12 февраля 2024 года № 1. Утратило силу решением акима города Костаная Костанайской области от 6 ноября 2024 года № 3 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации местного масштаба природного характера на территории города Костаная
  kaz: Қостанай қаласының аумағында табиғи сипаттағы жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-12
approved_by:
- '162002000003'
version_date:
  kaz: 2024-02-12
  rus: 2024-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/193227/kaz/12.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193227/rus/12.02.2024
