act_code: '127403'
requisite: Решение маслихата Аулиекольского района Костанайской области от 21 декабря 2018 года № 250. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2018 года № 8185
title:
  rus: О районном бюджете Аулиекольского района на 2019-2021 годы
  kaz: Әулиекөл ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '162005000002'
version_date:
  kaz: 2019-11-01
  rus: 2019-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/127403/kaz/01.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127403/rus/01.11.2019
caused_by:
  code: '135753'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 1 ноября 2019 года № 343. Зарегистрировано Департаментом юстиции Костанайской области 4 ноября 2019 года № 8740
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 21 декабря 2018 года № 250 «О районном бюджете Аулиекольского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 21 желтоқсандағы № 250 «Әулиекөл ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135753/rus
