act_code: '177730'
requisite: Решение маслихата Карасуского района Костанайской области от 29 декабря 2022 года № 200
title:
  rus: О бюджете села Новопавловка Карасуского района на 2023-2025 годы
  kaz: Қарасу ауданы Новопавлов ауылының 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162011000002'
version_date:
  kaz: 2023-11-29
  rus: 2023-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177730/kaz/29.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177730/rus/29.11.2023
caused_by:
  code: '189459'
  requisite: Решение маслихата Карасуского района Костанайской области от 29 ноября 2023 года № 87
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2022 года № 200 «О бюджете села Новопавловка Карасуского района на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 29 желтоқсандағы № 200 «Қарасу ауданы Новопавлов ауылының 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189459/rus
