act_code: '163906'
requisite: Решение маслихата Сарыкольского района Костанайской области от 13 января 2022 года № 96
title:
  rus: О бюджете села Барвиновка Сарыкольского района Костанайской области на 2022-2024 годы
  kaz: Қостанай облысы Сарыкөл ауданы Барвиновка ауылының 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-13
approved_by:
- '162015000002'
version_date:
  kaz: 2022-01-13
  rus: 2022-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/163906/kaz/13.01.2022
  rus: https://zan.gov.kz/client/#!/doc/163906/rus/13.01.2022
