act_code: '180257'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 25 апреля 2023 года № 15. Отменено решением маслихата района Беимбета Майлина Костанайской области от 29 сентября 2025 года № 197 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования и распространяется на правоотношения, возникшие с 1 июля 2025 года)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата района Беимбета Майлина»
  kaz: «Бейімбет Майлин ауданы мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-04-25
approved_by:
- '162016000002'
version_date:
  kaz: 2023-08-28
  rus: 2023-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/180257/kaz/28.08.2023
  rus: https://zan.gov.kz/client/#!/doc/180257/rus/28.08.2023
caused_by:
  code: '185623'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 28 августа 2023 года № 32. Отменено решением маслихата района Беимбета Майлина Костанайской области от 29 сентября 2025 года № 197 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования и распространяется на правоотношения, возникшие с 1 июля 2025 года)
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 25 апреля 2023 года № 15 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата района Беимбета Майлина»
    kaz: Мәслихаттың «Бейімбет Майлин ауданы мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» 2023 жылғы 25 сәуірдегі № 15 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185623/rus
