act_code: '191746'
requisite: Решение маслихата Аулиекольского района Костанайской области от 27 декабря 2023 года № 127
title:
  rus: О бюджете Диевского сельского округа Аулиекольского района на 2024-2026 годы
  kaz: Әулиекөл ауданы Диев ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162005000002'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/191746/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/191746/rus/20.03.2024
caused_by:
  code: '194738'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 20 марта 2024 года № 162
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2023 года № 127 «О бюджете Диевского сельского округа Аулиекольского района на 2024-2026 годы»
    kaz: Мәслихаттың 2023 жылғы 27 желтоқсандағы № 127 «Әулиекөл ауданы Диев ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194738/rus
