act_code: '114446'
requisite: Решение акима Каиндинского сельского округа города Аркалыка Костанайской области от 15 августа 2017 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 4 сентября 2017 года № 7188. Утратило силу решением акима Каиндинского сельского округа города Аркалыка Костанайской области от 25 сентября 2018 года № 5
title:
  rus: Об установлении ограничительных мероприятий в селе Кызылжулдыз Каиндинского сельского округа города Аркалыка
  kaz: Арқалық қаласы Қайыңды ауылдық округінің Қызылжұлдыз ауылында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- МРП
- РЕШ
approved_on: 2017-08-15
approved_by:
- '162019002002'
version_date:
  kaz: 2017-08-15
  rus: 2017-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/114446/kaz/15.08.2017
  rus: https://zan.gov.kz/client/#!/doc/114446/rus/15.08.2017
