act_code: '84516'
requisite: Решение маслихата Тарановского района Костанайской области от 30 октября 2014 года № 235. Зарегистрировано Департаментом юстиции Костанайской области 21 ноября 2014 года № 5164. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 15 мая 2020 года № 383 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов
  kaz: Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-10-30
approved_by:
- '162016000002'
version_date:
  kaz: 2019-09-23
  rus: 2019-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/84516/kaz/23.09.2019
  rus: https://zan.gov.kz/client/#!/doc/84516/rus/23.09.2019
caused_by:
  code: '134931'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 23 сентября 2019 года № 311. Зарегистрировано Департаментом юстиции Костанайской области 27 сентября 2019 года № 8678. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 15 мая 2020 года № 383 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 30 октября 2014 года № 235 «О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов»
    kaz: Мәслихаттың 2014 жылғы 30 қазандағы № 235 «Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134931/rus
