act_code: '189012'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 27 ноября 2023 года № 74
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Введенского сельского округа Мендыкаринского района Костанайской области
  kaz: Қостанай облысы Меңдіқара ауданы Введен ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-27
approved_by:
- '162013000002'
version_date:
  kaz: 2023-11-27
  rus: 2023-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/189012/kaz/27.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189012/rus/27.11.2023
