act_code: '92643'
requisite: Решение маслихата Амангельдинского района Костанайской области от 23 июля 2015 года № 334. Зарегистрировано Департаментом юстиции Костанайской области 13 августа 2015 года № 5801. Утратило силу решением маслихата Амангельдинского района Костанайской области от 18 января 2016 года № 377
title:
  rus: Об установлении повышенных не менее чем на двадцать пять процентов должностные оклады и тарифные ставки по сравнению с окладами и ставками гражданских служащих, занимающихся этими видами деятельности в городских условиях специалистам в области социального обеспечения, образования, культуры, спорта и ветеринарии являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметші болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария саласындағы мамандарға қызметтің осы түрлерімен қалалық жағдайда айналысатын азаматтық қызметшілердің айлықақыларымен және ставкаларымен салыстырғанда кемінде жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-23
approved_by:
- '162004000002'
version_date:
  kaz: 2015-07-23
  rus: 2015-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/92643/kaz/23.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92643/rus/23.07.2015
