act_code: '123350'
requisite: Решение акима села Пригородное Житикаринского района Костанайской области от 12 июня 2018 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 5 июля 2018 года № 7928
title:
  rus: О переименовании составных частей в селе Пригородное Житикаринского района
  kaz: Жітіқара ауданы Пригородное ауылының құрамдас бөліктеріне қайта атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-12
approved_by:
- '162008009001'
version_date:
  kaz: 2018-06-12
  rus: 2018-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/123350/kaz/12.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123350/rus/12.06.2018
