act_code: '79176'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 28 марта 2014 года № 231. Зарегистрировано Департаментом юстиции Костанайской области 24 апреля 2014 года № 4646. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 12 февраля 2015 года № 289
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Введенского сельского округа Мендыкаринского района Костанайской области
  kaz: Қостанай облысы Меңдіқара ауданы Введен ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-28
approved_by:
- '162013000002'
version_date:
  kaz: 2014-03-28
  rus: 2014-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/79176/kaz/28.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79176/rus/28.03.2014
