act_code: '164125'
requisite: Решение маслихата Житикаринского района Костанайской области от 25 января 2022 года № 111. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 января 2022 года № 26662
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Житикаринскому району
  kaz: Жітіқара ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2022-01-25
approved_by:
- '162008000002'
version_date:
  kaz: 2022-01-25
  rus: 2022-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/164125/kaz/25.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164125/rus/25.01.2022
