act_code: '192961'
requisite: Решение маслихата Джангельдинского района Костанайской области от 27 декабря 2023 года № 48. Зарегистрировано в Департаменте юстиции Костанайской области 31 января 2024 года № 10137-10
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162007000002'
version_date:
  kaz: 2026-04-21
  rus: 2026-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/192961/kaz/21.04.2026
  rus: https://zan.gov.kz/client/#!/doc/192961/rus/21.04.2026
caused_by:
  code: '224431'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 21 апреля 2026 года № 205
  title:
    rus: О внесении изменений в решение маслихата Джангельдинского района от 27 декабря 2023 года № 48 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Жангелдин аудандық мәслихатының 2023 жылғы 27 желтоқсандағы № 48 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224431/rus
