act_code: '55714'
requisite: Решение акима Денисовского района Костанайской области от 29 октября 2010 года № 13. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 2 декабря 2010 года № 9-8-164. Утратило силу в связи с истечением срока действия - письмо акима Денисовского района Костанайской области от 29 апреля 2011 года № 585
title:
  rus: Об организации и обеспечении приписки граждан Республики Казахстан к призывному участку Денисовского района
  kaz: Қазақстан Республикасының азаматтарын Денисов ауданының шақыру учаскесіне тіркеуді ұйымдастыру мен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-29
approved_by:
- '162006000003'
version_date:
  kaz: 2010-10-29
  rus: 2010-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/55714/kaz/29.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55714/rus/29.10.2010
