act_code: '7001'
requisite: Решение акима Костанайской области от 14 сентября 2000 года № 175. Зарегистрировано Управлением юстиции Костанайской области 20 сентября 2000 года № 407.  Прекратил действие в связи с истечением срока применения - письмо аппарата акима Костанайской области от 11 декабря 2006 года № 08-3/3087
title:
  rus: Об изменении сети общеобразовательных школ Костанайской области в 2000-2001 учебном году
  kaz: 2000-2001 оқу жылында Қостанай облысының жалпы білім беретін мектептері жүйесін өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-09-13
approved_by:
- '162000000003'
version_date:
  kaz: 2000-09-13
  rus: 2000-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/7001/kaz/13.09.2000
  rus: https://zan.gov.kz/client/#!/doc/7001/rus/13.09.2000
