act_code: '94989'
requisite: Решение акима сельского округа имени Ильяса Омарова Алтынсаринского района Костанайской области от 29 октября 2015 года № 1
title:
  rus: О снятии ограничительных мероприятий на территории животноводческой фермы товарищества с ограниченной ответственностью "Беляевка" сельского округа имени Ильяса Омарова Алтынсаринского района
  kaz: Алтынсарин ауданы Ілияс Омаров атындағы ауылдық округіндегі "Беляевка" жауапкершілігі шектеулі серіктестігінің мал шаруашылық фермасының аумағында шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-29
approved_by:
- '162003011002'
version_date:
  kaz: 2015-10-29
  rus: 2015-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/94989/kaz/29.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94989/rus/29.10.2015
