act_code: '88472'
requisite: Решение маслихата Тарановского района Костанайской области от 20 марта 2015 года № 263. Зарегистрировано Департаментом юстиции Костанайской области 9 апреля 2015 года № 5510. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 28 марта 2024 года № 90 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в районе Беимбета Майлина
  kaz: Бейімбет Майлин ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2015-03-20
approved_by:
- '162016000002'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/88472/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/88472/rus/12.11.2021
caused_by:
  code: '160839'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 12 ноября 2021 года № 59. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2021 года № 25450. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 28 марта 2024 года № 90 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 20 марта 2015 года № 263 «Об утверждении Правил оказания жилищной помощи»
    kaz: Мәслихаттың 2015 жылғы 20 наурыздағы № 263 «Тұрғын үй көмегін көрсету қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160839/rus
