act_code: '130398'
requisite: Решение маслихата Житикаринского района Костанайской области от 29 марта 2019 года № 285. Зарегистрировано Департаментом юстиции Костанайской области 5 апреля 2019 года № 8325. Утратило силу решением маслихата Житикаринского района Костанайской области от 29 ноября 2019 года № 356 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества села Пригородное Житикаринского района
  kaz: Жітіқара ауданы Пригородный ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '162008000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130398/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/130398/rus/29.03.2019
