act_code: '2756'
requisite: Решение маслихата Костанайской области от 7 апреля  1999 года. Зарегистрировано Управлением юстиции Костанайской области 28 апреля 1999 года № 81. Утратило силу решением маслихата Костанайской области от 14 декабря 2004 года № 139
title:
  rus: Об инвестировании сельского хозяйства
  kaz: Облыстың ауыл шаруашылығын инвестициялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-06
approved_by:
- '162000000002'
version_date:
  kaz: 1999-04-06
  rus: 1999-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/2756/kaz/06.04.1999
  rus: https://zan.gov.kz/client/#!/doc/2756/rus/06.04.1999
