act_code: '103658'
requisite: Решение маслихата Узункольского района Костанайской области от 20 мая 2016 года № 17. Зарегистрировано Департаментом юстиции Костанайской области 24 июня 2016 года № 6493. Утратило силу решением маслихата Узункольского района Костанайской области от 19 августа 2020 года № 400 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил о дополнительном регламентировании проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізуді қосымша реттеу туралы қағидаларын   бекіту   туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-20
approved_by:
- '162017000002'
version_date:
  kaz: 2020-01-17
  rus: 2020-01-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/103658/kaz/17.01.2020
  rus: https://zan.gov.kz/client/#!/doc/103658/rus/17.01.2020
caused_by:
  code: '139402'
  requisite: Решение маслихата Узункольского района Костанайской области от 17 января 2020 года № 342. Зарегистрировано Департаментом юстиции Костанайской области 7 февраля 2020 года № 8957. Утратило силу решением маслихата Узункольского района Костанайской области от 19 августа 2020 года № 400 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 20 мая 2016 года № 17 «Об утверждении Правил о дополнительном регламентировании проведения собраний, митингов, шествий, пикетов и демонстраций»
    kaz: Мәслихаттың 2016 жылғы 20 мамырдағы № 17 «Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізуді қосымша реттеу туралы қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/139402/rus
