act_code: '12341'
requisite: Решение акима Костанайской области от 18 апреля 2002 года № 46. Зарегистрировано Управлением юстиции Костанайской области 14 мая 2002 года № 1482. Утратило силу решением акима Костанайской области от 19 апреля 2004 года № 15
title:
  rus: О делегировании права лицензирования деятельности по организации и проведению тотализаторов и казино
  kaz: Тотализаторлардың және казинолардың қызметін ұйымдастыру және өткізуді лицензиялау құқын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-17
approved_by:
- '162000000003'
version_date:
  kaz: 2002-04-17
  rus: 2002-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/12341/kaz/17.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12341/rus/17.04.2002
