act_code: '197371'
requisite: Решение акима города Житикары Житикаринского района Костанайской области от 5 июня 2024 года № 11
title:
  rus: Об установлении публичного сервитута на земельный участок
  kaz: Жер учаскесіне жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-05
approved_by:
- '162008004001'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/197371/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197371/rus/05.06.2024
