act_code: '221053'
requisite: Решение маслихата Камыстинского района Костанайской области от 30 декабря 2025 года № 412
title:
  rus: О бюджете Аркинского сельского округа Камыстинского района на 2026 – 2028 годы
  kaz: Қамысты ауданы Арқа ауылдық округінің 2026 - 2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-30
approved_by:
- '162009000002'
version_date:
  kaz: 2025-12-30
  rus: 2025-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/221053/kaz/30.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221053/rus/30.12.2025
