act_code: '221024'
requisite: Решение маслихата Житикаринского района Костанайской области от 26 декабря 2025 года № 358
title:
  rus: О бюджете Степного сельского округа Житикаринского района на 2026-2028 годы
  kaz: Жітіқара ауданы Степной ауылдық округінің 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '162008000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/221024/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221024/rus/26.12.2025
