act_code: '139368'
requisite: Решение маслихата Костанайского района Костанайской области от 5 февраля 2020 года № 477. Зарегистрировано Департаментом юстиции Костанайской области 6 февраля 2020 года № 8954
title:
  rus: Об утверждении Регламента собрания местного сообщества города Тобыл Костанайского района
  kaz: Қостанай ауданы Тобыл қаласының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-02-05
approved_by:
- '162012000002'
version_date:
  kaz: 2021-08-20
  rus: 2021-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139368/kaz/20.08.2021
  rus: https://zan.gov.kz/client/#!/doc/139368/rus/20.08.2021
caused_by:
  code: '158305'
  requisite: Решение маслихата Костанайского района Костанайской области от 20 августа 2021 года № 79
  title:
    rus: О внесении изменений в решение маслихата от 5 февраля 2020 года № 477 «Об утверждении Регламента собрания местного сообщества города Тобыл Костанайского района»
    kaz: Мәслихаттың 2020 жылғы 5 ақпандағы № 477 «Қостанай ауданы Тобыл қаласының жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158305/rus
