act_code: '139368'
requisite: Решение маслихата Костанайского района Костанайской области от 5 февраля 2020 года № 477. Зарегистрировано Департаментом юстиции Костанайской области 6 февраля 2020 года № 8954
title:
  rus: Об утверждении Регламента собрания местного сообщества города Тобыл Костанайского района
  kaz: Қостанай ауданы Тобыл қаласының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-02-05
approved_by:
- '162012000002'
version_date:
  kaz: 2020-02-05
  rus: 2020-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/139368/kaz/05.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139368/rus/05.02.2020
