act_code: '204426'
requisite: Решение маслихата города Лисаковска Костанайской области от 18 декабря 2024 года № 135
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Лисаковску
  kaz: Лисаков қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-18
approved_by:
- '162020000002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204426/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204426/rus/18.12.2024
