act_code: '60854'
requisite: Решение маслихата Денисовского района Костанайской области от 23 сентября 2011 года № 64. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 18 октября 2011 года № 9-8-183. Утратило силу решением маслихата Денисовского района Костанайской области от 31 января 2013 года № 4
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-23
approved_by:
- '162006000002'
version_date:
  kaz: 2011-09-23
  rus: 2011-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/60854/kaz/23.09.2011
  rus: https://zan.gov.kz/client/#!/doc/60854/rus/23.09.2011
