act_code: '31012'
requisite: Решение маслихата Костанайской области от 8 декабря 2006 года № 378. Зарегистрировано Департаментом юстиции Костанайской области 11 декабря 2006 года № 3557
title:
  rus: Об областном бюджете Костанайской области на 2007 год
  kaz: Қостанай облысының 2007 жылға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-08
approved_by:
- '162000000002'
version_date:
  kaz: 2007-07-12
  rus: 2007-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/31012/kaz/12.07.2007
  rus: https://zan.gov.kz/client/#!/doc/31012/rus/12.07.2007
caused_by:
  code: '34332'
  requisite: Решение маслихата Костанайской области от 12 июля 2007 года № 457. Зарегистрировано департаментом юстиции Костанайской области 26 июля 2007 года № 3574
  title:
    rus: О внесении изменений и дополнений в решение от 8 декабря 2006 года № 378 "Об областном бюджете Костанайской области на 2007 год"
    kaz: '"Қостанай облысының 2007 жылға арналған облыстық бюджеті туралы" 2006 жылғы 8 желтоқсандағы № 378 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/34332/rus
