act_code: '146457'
requisite: Решение маслихата Наурзумского района Костанайской области от 9 сентября 2020 года № 385. Зарегистрировано Департаментом юстиции Костанайской области 18 сентября 2020 года № 9461
title:
  rus: Об организации и проведении мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-09-09
approved_by:
- '162014000002'
version_date:
  kaz: 2024-04-17
  rus: 2024-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/146457/kaz/17.04.2024
  rus: https://zan.gov.kz/client/#!/doc/146457/rus/17.04.2024
caused_by:
  code: '196183'
  requisite: Решение маслихата Наурзумского района Костанайской области от 17 апреля 2024 года № 102. Зарегистрировано в Департаменте юстиции Костанайской области 29 апреля 2024 года № 10185-10
  title:
    rus: О внесении изменений в решение маслихата от 9 сентября 2020 года № 385 «Об организации и проведении мирных собраний»
    kaz: Мәслихаттың 2020 жылғы 9 қыркүйектегі № 385 «Бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196183/rus
