act_code: '145258'
requisite: Решение акима Карамендинского сельского округа Наурзумского района Костанайской области от 28 июля 2020 года № 7. Зарегистрировано Департаментом юстиции Костанайской области 3 августа 2020 года № 9356
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-28
approved_by:
- '162014001002'
version_date:
  kaz: 2020-07-28
  rus: 2020-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/145258/kaz/28.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145258/rus/28.07.2020
