act_code: '158622'
requisite: Решение маслихата Карабалыкского района Костанайской области от 2 сентября 2021 года № 61. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 сентября 2021 года № 24360
title:
  rus: О признании утратившим силу решения маслихата от 4 декабря 2017 года № 190 «Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по Карабалыкскому району»
  kaz: Мәслихаттың 2017 жылғы 4 желтоқсандағы № 190 «Сот шешімімен Қарабалық ауданы бойынша коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы» шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-02
approved_by:
- '162010000002'
version_date:
  kaz: 2021-09-02
  rus: 2021-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/158622/kaz/02.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158622/rus/02.09.2021
