act_code: '122112'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 4 мая 2018 года № 173. Зарегистрировано Департаментом юстиции Костанайской области 24 мая 2018 года № 7786. Утратило силу решением маслихата Алтынсаринского района Костанайской области от 29 января 2020 года № 288 (вводится в действие для сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества сельского округа имени Мариям Хәкімжановой Алтынсаринского района Костанайской области
  kaz: Костанай облысы Алтынсарин ауданы Мариям Хәкімжанова атындағы ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-04
approved_by:
- '162003000002'
version_date:
  kaz: 2019-10-08
  rus: 2019-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/122112/kaz/08.10.2019
  rus: https://zan.gov.kz/client/#!/doc/122112/rus/08.10.2019
caused_by:
  code: '135179'
  requisite: Решение маслихата Алтынсаринского района Костанайской области от 8 октября 2019 года № 263. Зарегистрировано Департаментом юстиции Костанайской области 10 октября 2019 года № 8694. Утратило силу решением маслихата Алтынсаринского района Костанайской области от 29 января 2020 года № 288 (вводится в действие для сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 4 мая 2018 года № 173 «Об утверждении Регламента собрания местного сообщества сельского округа имени Мариям Хәкімжановой Алтынсаринского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 4 мамырдағы № 173 «Қостанай облысы Алтынсарин ауданы Мариям Хәкімжанова атындағы ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135179/rus
