act_code: '109150'
requisite: Решение маслихата Костанайской области от 8 декабря 2016 года № 96. Зарегистрировано Департаментом юстиции Костанайской области 18 января 2017 года № 6805
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников на 2017 год
  kaz: 2017 жылға арналған жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-08
approved_by:
- '162000000002'
version_date:
  kaz: 2016-12-08
  rus: 2016-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/109150/kaz/08.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109150/rus/08.12.2016
