act_code: '5742'
requisite: Решение акима Костанайской области от 24 января 2000 года № 14. Зарегистрировано Управлением юстиции Костанайской области 31 марта 2000 года № 219.  Утратило силу постановлением акимата Костанайской области от 24 января 2003 года № 13
title:
  rus: Об утверждении Положения о порядке предоставления субъектам малого предпринимательства в аренду или доверительное управление с правом последующей передачи в собственность неиспользуемых объектов коммунальной собственности
  kaz: '"Шағын кәсіпкерлік субъектілеріне пайдаланылмай тұрған коммуналдык меншіктегі объектілерді кейін меншікке беру кұқығымен жалға немесе сенімді басқаруға берудің тәртібі туралы" Ережені бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2000-01-24
approved_by:
- '162000000003'
version_date:
  kaz: 2000-01-24
  rus: 2000-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/5742/kaz/24.01.2000
  rus: https://zan.gov.kz/client/#!/doc/5742/rus/24.01.2000
