act_code: '127980'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 21 декабря 2018 года № 205. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2018 года № 8187
title:
  rus: О районном бюджете Алтынсаринского района на 2019-2021 годы
  kaz: Алтынсарин ауданының 2019–2021 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '162003000002'
version_date:
  kaz: 2018-12-21
  rus: 2018-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/127980/kaz/21.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127980/rus/21.12.2018
