act_code: '185786'
requisite: Решение акима Ильичевского сельского округа Карасуского района Костанайской области от 1 сентября 2023 года № 5
title:
  rus: О переименовании улицы в селе Комсомольское Ильичевского сельского округа Карасуского района
  kaz: Қарасу ауданы Ильичев ауылдық округі Комсомольское ауылындағы көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-01
approved_by:
- '162011006002'
version_date:
  kaz: 2023-09-01
  rus: 2023-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/185786/kaz/01.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185786/rus/01.09.2023
