act_code: '120028'
requisite: Решение маслихата Наурзумского района Костанайской области от 14 марта 2018 года № 179. Зарегистрировано Департаментом юстиции Костанайской области 29 марта 2018 года № 7633
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Наурзумского районного маслихата»
  kaz: «Науырзым аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-14
approved_by:
- '162014000002'
version_date:
  kaz: 2022-02-18
  rus: 2022-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/120028/kaz/18.02.2022
  rus: https://zan.gov.kz/client/#!/doc/120028/rus/18.02.2022
caused_by:
  code: '164647'
  requisite: Решение маслихата Наурзумского района Костанайской области от 18 февраля 2022 года № 107
  title:
    rus: О внесении изменений в решение маслихата от 14 марта 2018 года № 179 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Наурзумского районного маслихата»
    kaz: Мәслихаттың 2018 жылғы 14 наурыздағы № 179 «Науырзым аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164647/rus
