act_code: '79200'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 28 марта 2014 года № 228. Зарегистрировано Департаментом юстиции Костанайской области 24 апреля 2014 года № 4640. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 28 апреля 2022 года № 113 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Алешинского сельского округа Мендыкаринского района Костанайской области
  kaz: Қостанай облысы Меңдіқара ауданы Алешин ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-28
approved_by:
- '162013000002'
version_date:
  kaz: 2020-12-23
  rus: 2020-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79200/kaz/23.12.2020
  rus: https://zan.gov.kz/client/#!/doc/79200/rus/23.12.2020
caused_by:
  code: '150535'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 23 декабря 2020 года № 425. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2020 года № 9654. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 28 апреля 2022 года № 113 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 28 марта 2014 года № 228 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Алешинского сельского округа Мендыкаринского района Костанайской области»
    kaz: Мәслихаттың 2014 жылғы 28 наурыздағы № 228 «Қостанай облысы Меңдіқара ауданы Алешин ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150535/rus
