act_code: '156254'
requisite: Решение маслихата города Аркалыка Костанайской области от 20 мая 2021 года № 34. Отменено решением маслихата города Аркалыка Костанайской области от 5 октября 2023 года № 48 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Молодежного сельского округа города Аркалыка Костанайской области
  kaz: Қостанай облысы Арқалық қаласы Молодежный ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2021-05-20
approved_by:
- '162019000002'
version_date:
  kaz: 2022-02-04
  rus: 2022-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/156254/kaz/04.02.2022
  rus: https://zan.gov.kz/client/#!/doc/156254/rus/04.02.2022
caused_by:
  code: '164638'
  requisite: Решение маслихата города Аркалыка Костанайской области от 4 февраля 2022 года № 95. Отменено решением маслихата города Аркалыка Костанайской области от 5 октября 2023 года № 48 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 20 мая 2021 года № 34 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Молодежного сельского округа города Аркалыка Костанайской области»
    kaz: Мәслихаттың 2021 жылғы 20 мамырдағы № 34 «Қостанай облысы Арқалық қаласының Молодежный ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті  қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164638/rus
