act_code: '206397'
requisite: Решение маслихата города Рудного Костанайской области от 30 декабря 2024 года № 188
title:
  rus: О городском бюджете города Рудного на 2025-2027 годы
  kaz: Рудный қаласының 2025-2027 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162021000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206397/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206397/rus/30.12.2024
