act_code: '206397'
requisite: Решение маслихата города Рудного Костанайской области от 30 декабря 2024 года № 188
title:
  rus: О городском бюджете города Рудного на 2025-2027 годы
  kaz: Рудный қаласының 2025-2027 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '162021000002'
version_date:
  kaz: 2025-12-18
  rus: 2025-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/206397/kaz/18.12.2025
  rus: https://zan.gov.kz/client/#!/doc/206397/rus/18.12.2025
caused_by:
  code: '219884'
  requisite: Решение маслихата города Рудного Костанайской области от 18 декабря 2025 года № 255
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2024 года № 188 «О городском бюджете города Рудного на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 30 желтоқсандағы № 188 «Рудный қаласының 2025-2027 жылдарға арналған қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/219884/rus
