act_code: '186961'
requisite: Решение маслихата города Аркалыка Костанайской области от 5 октября 2023 года № 52
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Ашутастинского сельского округа города Аркалыка Костанайской области
  kaz: Қостанай облысы Арқалық қаласы Ашутасты ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-05
approved_by:
- '162019000002'
version_date:
  kaz: 2023-10-05
  rus: 2023-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/186961/kaz/05.10.2023
  rus: https://zan.gov.kz/client/#!/doc/186961/rus/05.10.2023
