act_code: '176255'
requisite: Решение маслихата Камыстинского района Костанайской области от 26 декабря 2022 года № 199
title:
  rus: О районном бюджете Камыстинского района на 2023-2025 годы
  kaz: Қамысты ауданының 2023 - 2025 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '162009000002'
version_date:
  kaz: 2023-09-18
  rus: 2023-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/176255/kaz/18.09.2023
  rus: https://zan.gov.kz/client/#!/doc/176255/rus/18.09.2023
caused_by:
  code: '186249'
  requisite: Решение маслихата Камыстинского района Костанайской области от 18 сентября 2023 года № 78
  title:
    rus: О внесении изменений в решение маслихата от 26 декабря 2022 года № 199 «О районном бюджете Камыстинского района на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 26 желтоқсандағы № 199 «Қамысты ауданының 2023-2025 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186249/rus
