act_code: '117909'
requisite: Решение маслихата Карасуского района Костанайской области от 21 декабря 2017 года № 181. Зарегистрировано Департаментом юстиции Костанайской области 8 января 2018 года № 7463
title:
  rus: О бюджетах Железнодорожного сельского округа, села Карасу, села Октябрьское Карасуского  района на 2018-2020  годы
  kaz: 2018-2020 жылдарға арналған Қарасу ауданының Железнодорожный ауылдық округінің, Қарасу ауылының, Октябрь ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '162011000002'
version_date:
  kaz: 2018-10-11
  rus: 2018-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/117909/kaz/11.10.2018
  rus: https://zan.gov.kz/client/#!/doc/117909/rus/11.10.2018
caused_by:
  code: '125530'
  requisite: Решение маслихата Карасуского района Костанайской области от 11 октября 2018 года № 266. Зарегистрировано Департаментом юстиции Костанайской области 26 октября 2018 года № 8070
  title:
    rus: О внесении изменений в решение маслихата от 21 декабря 2017 года № 181 «О бюджетах Железнодорожного сельского округа, села Карасу, села Октябрьское Карасуского района на 2018-2020 годы»
    kaz: Мәслихаттың 2017 жылғы 21 желтоқсандағы № 181 «2018 – 2020 жылдарға арналған Қарасу ауданының Железнодорожный ауылдық округінің, Қарасу ауылының, Октябрь ауылының бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125530/rus
