act_code: '189444'
requisite: Решение маслихата Карабалыкского района Костанайской области от 29 ноября 2023 года № 63. Зарегистрировано в Департаменте юстиции Костанайской области 4 декабря 2023 года № 10104-10
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки поселка Карабалык и населенных пунктов Карабалыкского района
  kaz: Қарабалық кентінің және Қарабалық ауданының елді мекендерінің жерді аймақтарға бөлу жобаларын (схемаларын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2023-11-29
approved_by:
- '162010000002'
version_date:
  kaz: 2023-11-29
  rus: 2023-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/189444/kaz/29.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189444/rus/29.11.2023
