act_code: '69734'
requisite: Решение маслихата Жангельдинского района Костанайской области от 21 декабря 2012 года № 64. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2012 года № 3961
title:
  rus: О районном бюджете Жангельдинского района на 2013-2015 годы
  kaz: Жангелдин ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '162007000002'
version_date:
  kaz: 2013-02-18
  rus: 2013-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/69734/kaz/18.02.2013
  rus: https://zan.gov.kz/client/#!/doc/69734/rus/18.02.2013
caused_by:
  code: '71072'
  requisite: Решение маслихата Жангельдинского района Костанайской области от 18 февраля 2013 года № 72. Зарегистрировано Департаментом юстиции Костанайской области 21 февраля 2013 года № 4027
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 21 декабря 2012 года № 64 "О районном бюджете Жангельдинского района на 2013-2015 годы"
    kaz: Мәслихаттың 2012 жылғы 21 желтоқсандағы № 64 "Жангелдин ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/71072/rus
