act_code: '230223'
requisite: Решение Карасуского районного маслихата Костанайской области от 22 сентября 2026 года № 352
title:
  rus: Об утверждении ставок туристского взноса для иностранных граждан на 2026 год по Карасускому району
  kaz: Қарасу ауданы бойынша шетел азаматтары үшін 2026 жылға арналған туристік жарна ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-22
approved_by:
- '162011000002'
version_date:
  kaz: 2026-09-22
  rus: 2026-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/230223/kaz/22.09.2026
  rus: https://zan.gov.kz/client/#!/doc/230223/rus/22.09.2026
