act_code: '121224'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 4 апреля 2018 года № 169. Зарегистрировано Департаментом юстиции Костанайской области 28 апреля 2018 года № 7729. Утратило силу решением маслихата Алтынсаринского района Костанайской области от 19 мая 2023 года № 21 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Алтынсаринского районного маслихата»
  kaz: «Алтынсарин аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-04-04
approved_by:
- '162003000002'
version_date:
  kaz: 2018-04-04
  rus: 2018-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/121224/kaz/04.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121224/rus/04.04.2018
