act_code: '188803'
requisite: Решение маслихата Федоровского района Костанайской области от 22 ноября 2023 года № 83. Зарегистрировано в Департаменте юстиции Костанайской области 23 ноября 2023 года № 10089
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Федоровка и населенных пунктов Федоровского района
  kaz: Федоров ауылы және Федоров ауданы елді мекендерінің жерлерін аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2023-11-22
approved_by:
- '162018000002'
version_date:
  kaz: 2023-11-22
  rus: 2023-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/188803/kaz/22.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188803/rus/22.11.2023
