act_code: '74106'
requisite: Решение акима Денисовского района Костанайской области от 20 августа 2013 года № 13. Зарегистрировано Департаментом юстиции Костанайской области 26 августа 2013 года № 4217. Утратило силу - Решением акима Денисовского района Костанайской области от 17 января 2014 года № 1
title:
  rus: Об образовании избирательных участков на территории Денисовского района
  kaz: Денисов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-20
approved_by:
- '162006000003'
version_date:
  kaz: 2013-08-20
  rus: 2013-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/74106/kaz/20.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74106/rus/20.08.2013
