act_code: '50751'
requisite: Решение маслихата Костанайского района Костанайской области от 15 января 2010 года № 262. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 17 февраля 2010 года № 9-14-120. Утратило силу решением маслихата Костанайского района Костанайской области от 1 апреля 2016 года № 18
title:
  rus: О повышении базовых ставок земельного налога на 50 процентов
  kaz: Жер салығының базалық ставкасын 50 пайызға көтеру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-15
approved_by:
- '162012000002'
version_date:
  kaz: 2010-12-21
  rus: 2010-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50751/kaz/21.12.2010
  rus: https://zan.gov.kz/client/#!/doc/50751/rus/21.12.2010
caused_by:
  code: '56305'
  requisite: Решение маслихата Костанайского района Костанайской области от 21 декабря 2010 года № 390. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 29 декабря 2010 года № 9-14-142. Утратило силу решением маслихата Костанайского района Костанайской области от 1 апреля 2016 года № 18
  title:
    rus: О внесении изменения в решение маслихата от 15 января 2010 года № 262 "О повышении базовых ставок земельного налога на 50 процентов"
    kaz: Мәслихаттың 2010 жылғы 15 қаңтардағы № 262 "Жер салығының базалық ставкасын 50 пайызға көтеру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56305/rus
