act_code: '121913'
requisite: Решение маслихата Карасуского района Костанайской области от 27 апреля 2018 года № 224. Зарегистрировано Департаментом юстиции Костанайской области 17 мая 2018 года № 7767. Утратило силу решением маслихата Карасуского района Костанайской области от 5 февраля 2020 года № 369 (вводится в действие для сел, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Железнодорожного сельского округа Карасуского района Костанайской области
  kaz: Қостанай облысы Қарасу ауданы Железнодорожный ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-27
approved_by:
- '162011000002'
version_date:
  kaz: 2019-10-18
  rus: 2019-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/121913/kaz/18.10.2019
  rus: https://zan.gov.kz/client/#!/doc/121913/rus/18.10.2019
caused_by:
  code: '135461'
  requisite: Решение маслихата Карасуского района Костанайской области от 18 октября 2019 года № 347. Зарегистрировано Департаментом юстиции Костанайской области 23 октября 2019 года № 8715. Утратило силу решением маслихата Карасуского района Костанайской области от 5 февраля 2020 года № 369 (вводится в действие для сел, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 27 апреля 2018 года № 224 «Об утверждении Регламента собрания местного сообщества Железнодорожного сельского округа Карасуского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 27 сәуірдегі № 224 «Қостанай облысы Қарасу ауданы Железнодорожный ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135461/rus
