act_code: '127689'
requisite: Решение маслихата Сарыкольского района Костанайской области от 26 декабря 2018 года № 221. Зарегистрировано Департаментом юстиции Костанайской области 27 декабря 2018 года № 8203
title:
  rus: О районном бюджете Сарыкольского района на 2019-2021 годы
  kaz: Сарыкөл ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '162015000002'
version_date:
  kaz: 2019-05-20
  rus: 2019-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/127689/kaz/20.05.2019
  rus: https://zan.gov.kz/client/#!/doc/127689/rus/20.05.2019
caused_by:
  code: '131755'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 20 мая 2019 года № 260. Зарегистрировано Департаментом юстиции Костанайской области 24 мая 2019 года № 8476
  title:
    rus: О внесении изменений в решение маслихата от 26 декабря 2018 года № 221 «О районном бюджете Сарыкольского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 26 желтоқсандағы № 221 «Сарыкөл ауданының 2019-2021 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131755/rus
