act_code: '162748'
requisite: Решение маслихата города Рудного Костанайской области от 29 декабря 2021 года № 92. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2021 года № 26234
title:
  rus: О городском бюджете города Рудного на 2022-2024 годы
  kaz: Рудный қаласының 2022-2024 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '162021000002'
version_date:
  kaz: 2022-02-25
  rus: 2022-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/162748/kaz/25.02.2022
  rus: https://zan.gov.kz/client/#!/doc/162748/rus/25.02.2022
caused_by:
  code: '165318'
  requisite: Решение маслихата города Рудного Костанайской области от 25 февраля 2022 года № 106
  title:
    rus: О внесении изменений в решение Рудненского городского маслихата от 29 декабря 2021 года № 92 «О городском бюджете города Рудного на 2022-2024 годы»
    kaz: Рудный қалалық мәслихатының 2021 жылғы 29 желтоқсандағы № 92 «Рудный қаласының 2022-2024 жылдарға арналған қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165318/rus
