act_code: '162398'
requisite: Решение маслихата Карабалыкского района Костанайской области от 27 декабря 2021 года № 83. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26156
title:
  rus: О районном бюджете Карабалыкского района на 2022-2024 годы
  kaz: Қарабалық ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '162010000002'
version_date:
  kaz: 2022-07-28
  rus: 2022-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162398/kaz/28.07.2022
  rus: https://zan.gov.kz/client/#!/doc/162398/rus/28.07.2022
caused_by:
  code: '170186'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 28 июля 2022 года № 151
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2021 года № 83 «О районном бюджете Карабалыкского района на 2022-2024 годы»
    kaz: Мәслихаттың 2021 жылғы 27 желтоқсандағы № 83 «Қарабалық ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170186/rus
