act_code: '62760'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 21 декабря 2011 года № 506. Зарегистрировано Управлением юстиции Мендыкаринского района Костанайской области 13 января 2012 года № 9-15-164
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты района на 2012 год
  kaz: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2012 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '162013000002'
version_date:
  kaz: 2012-07-27
  rus: 2012-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/62760/kaz/27.07.2012
  rus: https://zan.gov.kz/client/#!/doc/62760/rus/27.07.2012
caused_by:
  code: '67120'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 27 июля 2012 года № 88. Зарегистрировано Департаментом юстиции Костанайской области 17 августа 2012 года № 9-15-181
  title:
    rus: О внесении изменений в решение маслихата от 21 декабря 2011 года № 506 "О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты района на 2012 год"
    kaz: Мәслихаттың 2011 жылғы 21 желтоқсандағы № 506 "Ауданның ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2012 жылға әлеуметтік қолдау шараларын ұсыну туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67120/rus
