act_code: '146187'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 27 августа 2020 года № 321. Зарегистрировано Департаментом юстиции Костанайской области 10 сентября 2020 года № 9441
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Алтынсаринскому району на 2020-2021 годы
  kaz: Алтынсарин ауданы бойынша 2020–2021 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2020-08-27
approved_by:
- '162003000002'
version_date:
  kaz: 2020-08-27
  rus: 2020-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/146187/kaz/27.08.2020
  rus: https://zan.gov.kz/client/#!/doc/146187/rus/27.08.2020
