act_code: '43161'
requisite: Решениие маслихата Сарыкольского района Костанайской области от 26 декабря 2008 года № 92. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 3 января 2009 года № 9-17-72
title:
  rus: О районном бюджете Сарыкольского района на 2009 год
  kaz: Сарыкөл ауданының 2009 жылға арналған аудандақ бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '162015000002'
version_date:
  kaz: 2009-04-28
  rus: 2009-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/43161/kaz/28.04.2009
  rus: https://zan.gov.kz/client/#!/doc/43161/rus/28.04.2009
caused_by:
  code: '45488'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 28 апреля 2009 года № 113. Зарегистрировано управлением юстиции Сарыкольского района Костанайской области 28 апреля 2009 года № 9-17-76
  title:
    rus: О внесении изменений в решение Сарыкольского районного маслихата от 26 декабря 2008 года № 92 "О районном бюджете Сарыкольского района на 2009 год"
    kaz: '"Сарыкөл ауданының 2009 жылға арналған аудандық бюджеті туралы" мәслихаттың 2008 жылғы 26 желтоқсандағы № 92 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45488/rus
