act_code: '150912'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 28 декабря 2020 года № 340. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2020 года № 9682
title:
  rus: О районном бюджете Алтынсаринского района на 2021-2023 годы
  kaz: Алтынсарин ауданының 2021–2023 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '162003000002'
version_date:
  kaz: 2020-12-28
  rus: 2020-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/150912/kaz/28.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150912/rus/28.12.2020
