act_code: '117667'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 20 декабря 2017 года № 134. Зарегистрировано Департаментом юстиции Костанайской области 4 января 2018 года № 7447
title:
  rus: О районном бюджете Алтынсаринского района на 2018-2020 годы
  kaz: Алтынсарин ауданының 2018–2020 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '162003000002'
version_date:
  kaz: 2018-02-13
  rus: 2018-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117667/kaz/13.02.2018
  rus: https://zan.gov.kz/client/#!/doc/117667/rus/13.02.2018
caused_by:
  code: '119020'
  requisite: Решение маслихата Алтынсаринского района Костанайской области от 13 февраля 2018 года № 153. Зарегистрировано Департаментом юстиции Костанайской области 27 февраля 2018 года № 7550
  title:
    rus: О внесении изменений в решение маслихата от 20 декабря 2017 года № 134 «О районном бюджете Алтынсаринского района на 2018-2020 годы»
    kaz: Мәслихаттың 2017 жылғы 20 желтоқсандағы № 134 «Алтынсарин ауданының 2018-2020 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119020/rus
