act_code: '221338'
requisite: Решение акима поселка Качар города Рудного Костанайской области от 15 января 2026 года № 3-р
title:
  rus: Об установлении публичного сервитута
  kaz: Жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-15
approved_by:
- '162021001001'
version_date:
  kaz: 2026-01-15
  rus: 2026-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/221338/kaz/15.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221338/rus/15.01.2026
