act_code: '78375'
requisite: Решение акима Костанайского района Костанайской области от 12 марта 2014 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 27 марта 2014 года № 4525. Утратило силу решением акима Костанайского района Костанайской области от 13 марта 2020 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков в Костанайском районе
  kaz: Қостанай ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-12
approved_by:
- '162012000001'
version_date:
  kaz: 2018-06-28
  rus: 2018-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/78375/kaz/28.06.2018
  rus: https://zan.gov.kz/client/#!/doc/78375/rus/28.06.2018
caused_by:
  code: '123610'
  requisite: Решение акима Костанайского района Костанайской области от 28 июня 2018 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 12 июля 2018 года № 7950. Утратило силу решением акима Костанайского района Костанайской области от 13 марта 2020 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима Костанайского района от 12 марта 2014 года № 1 «Об образовании избирательных участков в Костанайском районе»
    kaz: Қостанай ауданы әкімінің 2014 жылғы 12 наурыздағы № 1 «Қостанай ауданында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123610/rus
