act_code: '109904'
requisite: Решение маслихата Узункольского района Костанайской области от 2 февраля 2017 года № 76. Зарегистрировано Департаментом юстиции Костанайской области 17 февраля 2017 года № 6831. Утратило силу решением маслихата Узункольского района Костанайской области от 17 апреля 2024 года № 86 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Узункольском районе
  kaz: Ұзынкөл ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-02-02
approved_by:
- '162017000002'
version_date:
  kaz: 2019-02-27
  rus: 2019-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/109904/kaz/27.02.2019
  rus: https://zan.gov.kz/client/#!/doc/109904/rus/27.02.2019
caused_by:
  code: '129649'
  requisite: Решение маслихата Узункольского района Костанайской области от 27 февраля 2019 года № 260. Зарегистрировано Департаментом юстиции Костанайской области 15 марта 2019 года № 8300. Утратило силу решением маслихата Узункольского района Костанайской области от 17 апреля 2024 года № 86 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 2 февраля 2017 года № 76 «Об утверждении Правил оказания жилищной помощи»
    kaz: Мәслихаттың 2017 жылғы 2 ақпандағы № 76 «Тұрғын үй көмегін көрсету қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129649/rus
