act_code: '38754'
requisite: Решение маслихата города Рудного Костанайской области от 29 февраля 2008 года № 59. Зарегистрировано Управлением юстиции города Рудного Костанайской области 4 апреля 2008 года № 9-2-101. Утратило силу решением маслихата города Рудного Костанайской области от 28 июля 2009 года № 237
title:
  rus: Об установлении стоимости разовых талонов за право реализации товаров на рынках и на отдельные виды предпринимательской деятельности, носящей эпизодический характер
  kaz: Об установлении стоимости разовых талонов за право реализации товаров на рынках и на отдельные виды предпринимательской деятельности, носящей эпизодический характер
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-29
approved_by:
- '162021000002'
version_date:
  rus: 2008-02-29
source:
  rus: https://zan.gov.kz/client/#!/doc/38754/rus/29.02.2008
