act_code: '146090'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 27 августа 2020 года № 322. Зарегистрировано Департаментом юстиции Костанайской области 7 сентября 2020 года № 9434
title:
  rus: Об организации и проведении мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-08-27
approved_by:
- '162003000002'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/146090/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/146090/rus/05.06.2024
caused_by:
  code: '197574'
  requisite: Решение маслихата Алтынсаринского района Костанайской области от 5 июня 2024 года № 82. Зарегистрировано в Департаменте юстиции Костанайской области 12 июня 2024 года № 10231-10
  title:
    rus: О внесении изменений в решение маслихата Алтынсаринского района от 27 августа 2020 года № 322 «Об организации и проведении мирных собраний»
    kaz: «Бейбіт жиналыстарды ұйымдастыру және өткізу туралы» Алтынсарин аудандық мәслихатының 2020 жылғы 27 тамыздағы № 322 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197574/rus
