act_code: '16641'
requisite: Решение маслихата Карасуского района Костанайской области от 30 июля 2003 года № 141. Зарегистрировано Департаментом юстиции Костанайской области 18 августа 2003 года № 2432. Утратило силу решением маслихата Карасуского района Костанайской области от 1 сентября 2004 года № 56
title:
  rus: Об утверждении Правил содержания кошек, собак и других животных на территории Карасуского района
  kaz: Қарасу ауданының аумағында мысықтарды, иттердi және басқа жануарларды күтiп ұстау ережесiн бекiту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-29
approved_by:
- '162011000002'
version_date:
  kaz: 2003-07-29
  rus: 2003-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/16641/kaz/29.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16641/rus/29.07.2003
