act_code: '117451'
requisite: Решение маслихата Житикаринского района Костанайской области от 20 декабря 2017 года № 164. Зарегистрировано Департаментом юстиции Костанайской области 4 января 2018 года № 7446
title:
  rus: О районном бюджете Житикаринского района на 2018-2020 годы
  kaz: Жітіқара ауданының 2018-2020 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '162008000002'
version_date:
  kaz: 2018-11-28
  rus: 2018-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/117451/kaz/28.11.2018
  rus: https://zan.gov.kz/client/#!/doc/117451/rus/28.11.2018
caused_by:
  code: '127184'
  requisite: Решение маслихата Житикаринского района Костанайской области от 28 ноября 2018 года № 247. Зарегистрировано Департаментом юстиции Костанайской области 7 декабря 2018 года № 8150
  title:
    rus: О внесении изменений в решение маслихата от 20 декабря 2017 года № 164 «О районном бюджете Житикаринского района на 2018-2020 годы»
    kaz: Мәслихаттың 2017 жылғы 20 желтоқсандағы № 164 «Жітіқара ауданының 2018-2020 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127184/rus
