act_code: '137129'
requisite: Решение маслихата Костанайской области от 18 декабря 2019 года № 454. Зарегистрировано Департаментом юстиции Костанайской области 19 декабря 2019 года № 8827
title:
  rus: Об областном бюджете Костанайской области на 2020-2022 годы
  kaz: Қостанай облысының 2020-2022 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-18
approved_by:
- '162000000002'
version_date:
  kaz: 2019-12-18
  rus: 2019-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/137129/kaz/18.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137129/rus/18.12.2019
