act_code: '189283'
requisite: Решение маслихата Федоровского района Костанайской области от 22 ноября 2023 года № 82. Зарегистрировано в Департаменте юстиции Костанайской области 30 ноября 2023 года № 10099-10
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-22
approved_by:
- '162018000002'
version_date:
  kaz: 2023-11-22
  rus: 2023-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/189283/kaz/22.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189283/rus/22.11.2023
