act_code: '196373'
requisite: Решение маслихата города Костаная Костанайской области от 25 апреля 2024 года № 92. Зарегистрировано в Департаменте юстиции Костанайской области 3 мая 2024 года № 10191-10
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по городу Костанай
  kaz: Қостанай қаласы бойынша шетелдіктер үшін 2024 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-25
approved_by:
- '162002000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/196373/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196373/rus/25.04.2024
