act_code: '229836'
requisite: Решение Карасуского районного маслихата Костанайской области от 8 сентября 2026 года № 349
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат Карасуского районного маслихата»
  kaz: «Қарасу аудандық мәслихатының аппараты» мемлекеттік мекемесінің ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-09-08
approved_by:
- '162011000002'
version_date:
  kaz: 2026-09-08
  rus: 2026-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/229836/kaz/08.09.2026
  rus: https://zan.gov.kz/client/#!/doc/229836/rus/08.09.2026
