act_code: '43001'
requisite: Решение маслихата Узункольского района Костанайской области от 19 декабря 2008 года № 111. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 26 декабря 2008 года № 9-19-87
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '162017000002'
version_date:
  kaz: 2008-12-19
  rus: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43001/kaz/19.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43001/rus/19.12.2008
