act_code: '563'
requisite: Решение акима Костанайской области от 24 апреля 1998 года № 69. Зарегистрировано Управлением юстиции Костанайской области 8 мая 1998 года № 10
title:
  rus: О закреплении охотничьих угодий за охотпользователями
  kaz: Аң аулаушыларға аң аулайтын жерлерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-23
approved_by:
- '162000000003'
version_date:
  kaz: 1998-04-23
  rus: 1998-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/563/kaz/23.04.1998
  rus: https://zan.gov.kz/client/#!/doc/563/rus/23.04.1998
