act_code: '195228'
requisite: Решение маслихата города Лисаковска Костанайской области от 15 марта 2024 года № 87. Зарегистрировано в Департаменте юстиции Костанайской области 3 апреля 2024 года № 10168-10
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в городе Лисаковске
  kaz: Лисаков қаласында тұрғын үй көмегін көрсетудің мөлшері мен Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-15
approved_by:
- '162020000002'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/195228/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/195228/rus/20.11.2025
caused_by:
  code: '217455'
  requisite: Решение маслихата города Лисаковска Костанайской области от 20 ноября 2025 года № 199. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 ноября 2025 года № 37474
  title:
    rus: О внесении изменений в решение Лисаковского городского маслихата от 15 марта 2024 года № 87 «Об определении размера и порядка оказания жилищной помощи в городе Лисаковске»
    kaz: Лисаков қалалық мәслихатының 2024 жылғы 15 наурыздағы № 87 «Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217455/rus
