act_code: '228327'
requisite: Решение акима Архангельского сельского округа Денисовского района Костанайской области от 30 июля 2026 года № 3
title:
  rus: Об установлении публичного сервитута частной компании «Bataly Minerals Ltd.»
  kaz: «Bataly Minerals Ltd.» жеке компаниясына жария сервитуті белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-30
approved_by:
- '162006001002'
version_date:
  kaz: 2026-07-30
  rus: 2026-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/228327/kaz/30.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228327/rus/30.07.2026
