act_code: '85719'
requisite: Решение маслихата города Аркалыка Костанайской области от 24 декабря 2014 года № 205. Зарегистрировано Департаментом юстиции Костанайской области 12 января 2015 года № 5289
title:
  rus: О бюджете города Аркалыка на 2015-2017 годы
  kaz: Арқалық қаласының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162019000002'
version_date:
  kaz: 2015-10-19
  rus: 2015-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85719/kaz/19.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85719/rus/19.10.2015
caused_by:
  code: '94771'
  requisite: Решение маслихата города Аркалыка Костанайской области от 19 октября 2015 года № 268. Зарегистрировано Департаментом юстиции Костанайской области 23 октября 2015 года № 5953
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2014 года № 205 "О бюджете города Аркалыка на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 205 "Арқалық қаласының 2015-2017 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94771/rus
