act_code: '216700'
requisite: Решение маслихата Карабалыкского района Костанайской области от 31 октября 2025 года № 218
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Карабалыкского районного маслихата»
  kaz: «Қарабалық аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2025-10-31
approved_by:
- '162010000002'
version_date:
  kaz: 2025-10-31
  rus: 2025-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/216700/kaz/31.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216700/rus/31.10.2025
