act_code: '4005'
requisite: Решение маслихата Костанайской области от 2 июля 1999 года. Зарегистрировано Управлением юстиции Костанайской области 26 августа 1999 года № 108. Утратило силу решением маслихата Костанайской области от 14 декабря 2004 года № 139
title:
  rus: Об укреплении самостоятельности органов управления сельских округов, сел, поселков в решении задач социально-экономического развития соответствующей  территории
  kaz: Тиісті аумақтардағы әлеуметтік-экономикалық даму міндеттерін шешудегі селолық округ, село, поселкелердің басқару органдарының дербестігін нығайту жайында
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-07-01
approved_by:
- '162000000002'
version_date:
  kaz: 1999-07-01
  rus: 1999-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/4005/kaz/01.07.1999
  rus: https://zan.gov.kz/client/#!/doc/4005/rus/01.07.1999
