act_code: '80315'
requisite: Решение маслихата Карабалыкского района Костанайской области от 29 апреля 2014 года № 230. Зарегистрировано Департаментом юстиции Костанайской области 27 мая 2014 года № 4759. Утратило силу решением маслихата Карабалыкского района Костанайской области от 4 марта 2022 года № 104 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Бурлинского сельского округа Карабалыкского района Костанайской области
  kaz: Қостанай облысы Қарабалық ауданы Бөрлі ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-04-29
approved_by:
- '162010000002'
version_date:
  kaz: 2016-12-22
  rus: 2016-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/80315/kaz/22.12.2016
  rus: https://zan.gov.kz/client/#!/doc/80315/rus/22.12.2016
caused_by:
  code: '109535'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 22 декабря 2016 года № 100. Зарегистрировано Департаментом юстиции Костанайской области 27 января 2017 года № 6816. Утратило силу решением маслихата Карабалыкского района Костанайской области от 4 марта 2022 года № 104 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 29 апреля  2014 года № 230  «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Бурлинского сельского округа Карабалыкского района Костанайской области»
    kaz: Мәслихаттың 2014 жылғы 29 сәуірдегі № 230 «Қостанай облысы Қарабалық ауданы Бөрлі ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109535/rus
