act_code: '146015'
requisite: Решение маслихата Карасуского района Костанайской области от 2 сентября 2020 года № 425. Зарегистрировано Департаментом юстиции Костанайской области 4 сентября 2020 года № 9431. Утратило силу решением маслихата Карасуского района Костанайской области от 16 августа 2023 года № 54 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және  мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-09-02
approved_by:
- '162011000002'
version_date:
  kaz: 2020-12-08
  rus: 2020-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/146015/kaz/08.12.2020
  rus: https://zan.gov.kz/client/#!/doc/146015/rus/08.12.2020
caused_by:
  code: '149741'
  requisite: Решение маслихата Карасуского района Костанайской области от 8 декабря 2020 года № 450. Зарегистрировано Департаментом юстиции Костанайской области 14 декабря 2020 года № 9631. Утратило силу решением маслихата Карасуского района Костанайской области от 16 августа 2023 года № 54 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 2 сентября 2020 года № 425 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2020 жылғы 2 қыркүйектегі № 425 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149741/rus
