act_code: '185999'
requisite: Решение маслихата Карабалыкского района Костанайской области от 8 сентября 2023 года № 47
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Карабалыкскому району на 2023 год
  kaz: Қарабалық ауданы бойынша 2023 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-08
approved_by:
- '162010000002'
version_date:
  kaz: 2023-09-08
  rus: 2023-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/185999/kaz/08.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185999/rus/08.09.2023
