act_code: '37072'
requisite: Решение акима Костанайского района Костанайской области от 24 декабря 2007 года № 21. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 19 января 2008 года № 9-14-66. Утратило силу решением акима Костанайского района Костанайской области от 22 января 2009 года № 3
title:
  rus: О проведении приписки граждан Республики Казахстан 1991 года рождения к призывному участку объединенного отдела по делам обороны Костанайского района
  kaz: Қостанай ауданының қорғаныс істері жөніндегі біріктірілген бөлімінің шақыру учаскесіне 1991 жылы туған Қазақстан Республикасы азаматтарының тіркеуін өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '162012000003'
version_date:
  kaz: 2007-12-24
  rus: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37072/kaz/24.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37072/rus/24.12.2007
