act_code: '76448'
requisite: Решение маслихата Жангельдинского района Костанайской области от 28 декабря 2013 года № 136. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2013 года № 4380
title:
  rus: О районном бюджете Джангельдинского района на 2014-2016 годы
  kaz: Жангелдин ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-28
approved_by:
- '162007000002'
version_date:
  kaz: 2014-02-21
  rus: 2014-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/76448/kaz/21.02.2014
  rus: https://zan.gov.kz/client/#!/doc/76448/rus/21.02.2014
caused_by:
  code: '77700'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 21 февраля 2014 года № 142. Зарегистрировано Департаментом юстиции Костанайской области 25 февраля 2014 года № 4449
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 28 декабря 2013 года № 136 "О районном бюджете Жангельдинского района на 2014-2016 годы"
    kaz: Мәслихаттың 2013 жылғы 28 желтоқсандағы № 136 "Жангелдин ауданының 2014-2016 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/77700/rus
