act_code: '117077'
requisite: Решение маслихата Карабалыкского района Костанайской области от 4 декабря 2017 года № 190. Зарегистрировано Департаментом юстиции Костанайской области 22 декабря 2017 года № 7412. Утратило силу решением маслихата Карабалыкского района Костанайской области от 2 сентября 2021 года № 61 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по Карабалыкскому району
  kaz: Сот шешімімен Қарабалық ауданы бойынша коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-04
approved_by:
- '162010000002'
version_date:
  kaz: 2017-12-04
  rus: 2017-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/117077/kaz/04.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117077/rus/04.12.2017
