act_code: '3577'
requisite: Решение акима Костанайской области от 5 апреля 1999 года № 85. Зарегистрировано Управлением юстиции Костанайской области 8 июля 1999 года № 95.  Утратило силу решением акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: О мерах по обеспечению выпуска продукции гарантированного качества
  kaz: Кепілдік сапасы бар өнімдерді шығаруды қамтамасыз ету жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-04
approved_by:
- '162000000003'
version_date:
  kaz: 1999-04-04
  rus: 1999-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/3577/kaz/04.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3577/rus/04.04.1999
