act_code: '85657'
requisite: Решение маслихата Карабалыкского района Костанайской области от 24 декабря 2014 года № 312. Зарегистрировано Департаментом юстиции Костанайской области 9 января 2015 года № 5284
title:
  rus: О районном бюджете Карабалыкского района на 2015-2017 годы
  kaz: Қарабалық ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162010000002'
version_date:
  kaz: 2015-03-20
  rus: 2015-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/85657/kaz/20.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85657/rus/20.03.2015
caused_by:
  code: '87833'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 20 марта 2015 года № 340. Зарегистрировано Департаментом юстиции Костанайской области 26 марта 2015 года № 5461
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2014 года № 312 "О районном бюджете Карабалыкского района на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 312 "Қарабалық ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87833/rus
