act_code: '177685'
requisite: Решение маслихата Федоровского района Костанайской области от 28 декабря 2022 года № 176
title:
  rus: О бюджетах села, сельских округов Федоровского района на 2023-2025 годы
  kaz: Федоров ауданы ауылының, ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '162018000002'
version_date:
  kaz: 2023-09-14
  rus: 2023-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/177685/kaz/14.09.2023
  rus: https://zan.gov.kz/client/#!/doc/177685/rus/14.09.2023
caused_by:
  code: '186243'
  requisite: Решение маслихата Федоровского района Костанайской области от 14 сентября 2023 года № 52
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2022 года № 176 «О бюджетах села, сельских округов Федоровского района на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 28 желтоқсандағы № 176 «Федоров ауданы ауылының, ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186243/rus
