act_code: '31043'
requisite: Решение маслихата города Лисаковска Костанайской области от 14 декабря 2006 года № 323. Зарегистрировано Управлением юстиции Костанайской области 29 декабря 2006 года № 9-4-69. Срок действия решения - до 1 января 2008 года
title:
  rus: Об утверждении Правил оказания жилищной помощи на 2007 год в городе Лисаковске
  kaz: Лисаков қаласындағы 2007 жылға арналған тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-12-14
approved_by:
- '162020000002'
version_date:
  kaz: 2006-12-14
  rus: 2006-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/31043/kaz/14.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31043/rus/14.12.2006
