act_code: '25349'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 18 июля 2005 года № 164. Зарегистрировано Управлением юстиции Мендыкаринского района Костанайской области 18 августа 2005 года № 9-15-15
title:
  rus: Об утверждении Правил содержания собак и кошек на территории Мендыкаринского района
  kaz: Меңдіқара ауданының аумағында иттерді және мысықтарды күтіп-ұстау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-07-18
approved_by:
- '162013000002'
version_date:
  kaz: 2005-07-18
  rus: 2005-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/25349/kaz/18.07.2005
  rus: https://zan.gov.kz/client/#!/doc/25349/rus/18.07.2005
