act_code: '31609'
requisite: Решение Костанайского областного маслихата от 9 января 2007 года № 390. Зарегистрировано Департаментом юстиции Костанайской области 22 января 2007 года № 3562. Утратило силу решением маслихата Костанайской области от 16 февраля 2008 года № 60
title:
  rus: Об утверждении ставок платы за загрязнение окружающей среды на 2007 год
  kaz: Қоршаған ортаны ластағаны үшін 2007 жылға арналған төлем ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-09
approved_by:
- '162000000002'
version_date:
  kaz: 2007-01-09
  rus: 2007-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/31609/kaz/09.01.2007
  rus: https://zan.gov.kz/client/#!/doc/31609/rus/09.01.2007
