act_code: '153570'
requisite: Решение маслихата города Рудного Костанайской области от 15 марта 2021 года № 22. Зарегистрировано Департаментом юстиции Костанайской области 18 марта 2021 года № 9822
title:
  rus: Об установлении повышенных должностных окладов и тарифных ставок специалистам в области здравоохранения, являющихся гражданскими служащими и работающим в селе Перцевка города Рудного
  kaz: Азаматтық қызметшілер болып табылатын және Рудный қаласының Перцев ауылында жұмыс істейтін денсаулық сақтау саласындағы мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-15
approved_by:
- '162021000002'
version_date:
  kaz: 2021-03-15
  rus: 2021-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/153570/kaz/15.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153570/rus/15.03.2021
