act_code: '176390'
requisite: Решение маслихата Карабалыкского района Костанайской области от 29 декабря 2022 года № 187
title:
  rus: О бюджетах сел, поселка, сельских округов Карабалыкского района на 2023-2025 годы
  kaz: Қарабалық ауданы ауылдарының, кентінің, ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162010000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/176390/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176390/rus/29.12.2022
