act_code: '54009'
requisite: Қостанай облысы Аманкелді ауданы мәслихатының 2010 жылғы 13 шілдедегі № 188 шешімі. Қостанай облысы Аманкелді ауданының Әділет басқармасында 2010 жылғы 12 тамызда № 9-6-114 тіркелді
title:
  rus: 2010 жылға ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну туралы
  kaz: 2010 жылға ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-13
approved_by:
- '162004000002'
version_date:
  kaz: 2010-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/54009/kaz/13.07.2010
