act_code: '26524'
requisite: Решение Костанайского областного маслихата от 23 декабря 2005 года № 266. Зарегистрировано Департаментом юстиции Костанайской области 24 января 2006 года за № 3534. Утратило силу решением маслихата Костанайской области от 23 июля 2007 года № 484
title:
  rus: Об утверждении региональной программы реабилитации инвалидов в Костанайской области на 2006 - 2008 годы
  kaz: Қостанай облысында мүгедектерді оңалтудың 2006-2008 жылдарға арналған өңірлік бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2005-12-23
approved_by:
- '162000000002'
version_date:
  rus: 2005-12-23
source:
  rus: https://zan.gov.kz/client/#!/doc/26524/rus/23.12.2005
