act_code: '124238'
requisite: Решение акима поселка Октябрьский города Лисаковска Костанайской области от 10 августа 2018 года № 6. Зарегистрировано Департаментом юстиции Костанайской области 22 августа 2018 года № 8011
title:
  rus: О переименовании составной части поселка Октябрьский города Лисаковска
  kaz: Лисаков қаласы Октябрь кентінің құрамдас бөлігін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-10
approved_by:
- '162020001001'
version_date:
  kaz: 2018-08-10
  rus: 2018-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/124238/kaz/10.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124238/rus/10.08.2018
