act_code: '26227'
requisite: Решение Костанайского областного маслихата от 6 декабря 2005 года № 255. Зарегистрировано Департаментом юстиции Костанайской области 15 декабря 2005 года № 3528. Срок действия решения до 1 января 2007 года
title:
  rus: Об утверждении ставок платы за загрязнение окружающей среды на 2006 год
  kaz: Қоршаған ортаны ластағаны үшін 2006 жылға арналған төлем ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-06
approved_by:
- '162000000002'
version_date:
  kaz: 2005-12-06
  rus: 2005-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/26227/kaz/06.12.2005
  rus: https://zan.gov.kz/client/#!/doc/26227/rus/06.12.2005
