act_code: '29237'
requisite: Решение маслихата Карабалыкского района Костанайской области от 20 июля 2006 года № 242. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 4 августа 2006 года № 9-12-19. Утратило силу решением маслихата Карабалыкского района Костанайской области от 15 апреля 2009 года № 155
title:
  rus: Об утверждении стоимости разовых талонов на рынках Карабалыкского района (за день торговли)
  kaz: Қарабалық ауданының базарларында (бір күнгі сауда үшін) біржолғы талонның құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-07-20
approved_by:
- '162010000002'
version_date:
  kaz: 2006-07-20
  rus: 2006-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/29237/kaz/20.07.2006
  rus: https://zan.gov.kz/client/#!/doc/29237/rus/20.07.2006
