act_code: '50572'
requisite: Қостанай облысы Аманкелді ауданы әкімінің 2010 жылғы 18 қаңтардағы № 2 шешімі. Қостанай облысы Аманкелді ауданының Әділет басқармасында 2010 жылғы 3 ақпанда № 9-6-105 тіркелді
title:
  rus: Қазақстан Республикасының тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды Аманкелді ауданының шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
  kaz: Қазақстан Республикасының тіркелетін жылы он жеті жасқа толатын еркек жынысты азаматтарды Аманкелді ауданының шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-18
approved_by:
- '162004000001'
version_date:
  kaz: 2010-01-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/50572/kaz/18.01.2010
