act_code: '79619'
requisite: Решение маслихата Аулиекольского района Костанайской области от 19 марта 2014 года № 145. Зарегистрировано Департаментом юстиции Костанайской области 29 апреля 2014 года № 4659. Утратило силу решением маслихата Аулиекольского района Костанайской области от 19 сентября 2023 года № 67 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей для участия в сходе местного сообщества села Коктал Аулиекольского района Костанайской области
  kaz: Қостанай облысы Әулиекөл ауданы Көктал ауылының  жергілікті  қоғамдастықтың бөлек жиындарын өткізудің  қағидаларын және жергілікті қоғамдастық  жиынына қатысу үшін  тұрғындар өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-19
approved_by:
- '162005000002'
version_date:
  kaz: 2022-02-09
  rus: 2022-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/79619/kaz/09.02.2022
  rus: https://zan.gov.kz/client/#!/doc/79619/rus/09.02.2022
caused_by:
  code: '164649'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 9 февраля 2022 года № 95. Отменено решением маслихата Аулиекольского района Костанайской области от 4 сентября 2023 года № 62 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 19 марта 2014 года № 145 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сёл для участия в сходе местного сообщества села Коктал Аулиекольского района Костанайской области»
    kaz: Мәслихаттың «Қостанай облысы Әулиекөл ауданы Көктал ауылының  жергілікті қоғамдастықтың жиынына  қатысу үшін бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын және ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы» 2014 жылғы 19 наурыздағы № 145 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164649/rus
