act_code: '178390'
requisite: Решение акима Айсаринского сельского округа Костанайского района Костанайской области от 30 января 2023 года № 1
title:
  rus: Об установлении акционерному обществу «Казахтелеком» публичного сервитута на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-30
approved_by:
- '162012004002'
version_date:
  kaz: 2023-01-30
  rus: 2023-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/178390/kaz/30.01.2023
  rus: https://zan.gov.kz/client/#!/doc/178390/rus/30.01.2023
