act_code: '76160'
requisite: Решение маслихата Сарыкольского района Костанайской области от 6 декабря 2013 года № 126. Зарегистрировано Департаментом юстиции Костанайской области 23 декабря 2013 года № 4367.  Утратило силу решением маслихата Сарыкольского района Костанайской области от 12 мая 2016 года № 24
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-06
approved_by:
- '162015000002'
version_date:
  kaz: 2014-05-30
  rus: 2014-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/76160/kaz/30.05.2014
  rus: https://zan.gov.kz/client/#!/doc/76160/rus/30.05.2014
caused_by:
  code: '80931'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 30 мая 2014 года № 171. Зарегистрировано Департаментом юстиции Костанайской области 24 июня 2014 года № 4876.  Утратило силу решением маслихата Сарыкольского района Костанайской области от 12 мая 2016 года № 24
  title:
    rus: О внесении изменения в решение маслихата от 6 декабря 2013 года № 126 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: Мәслихаттың 2013 жылғы 6 желтоқсандағы № 126 "Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/80931/rus
