act_code: '33508'
requisite: Қостанай облысы Меңдіқара ауданы мәслихатының 2007 жылғы 25 сәуірдегі № 359 шешімі. Қостанай облысы Меңдіқара ауданының Әділет басқармасында 2007 жылғы 2 маусымда № 9-15-63 болып тіркелді
title:
  rus: Меңдіқара ауданы елді мекендерінің құрамдас бөліктеріне атау беру, олардың атауларының транскрипцияларын өзгерту, жер телімдеріне, ғимараттар мен орын-жайларға реттік нөмірлер беру, көрсеткіштерді орнату және пайдалану Ережесі және Қазақстан Республикасының Мекен-жай тіркеліміндегі адрестер құрылымы мен тіркеу тәртібі туралы Ережесі туралы
  kaz: Меңдіқара ауданы елді мекендерінің құрамдас бөліктеріне атау беру, олардың атауларының транскрипцияларын өзгерту, жер телімдеріне, ғимараттар мен орын-жайларға реттік нөмірлер беру, көрсеткіштерді орнату және пайдалану Ережесі және Қазақстан Республикасының Мекен-жай тіркеліміндегі адрестер құрылымы мен тіркеу тәртібі туралы Ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-04-25
approved_by:
- '162013000002'
version_date:
  kaz: 2007-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/33508/kaz/25.04.2007
