act_code: '50642'
requisite: Решение акима Денисовского района Костанайской области от 6 января 2010 года № 1. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 10 февраля 2010 года № 9-8-143. Утратило силу решением акима Денисовского района Костанайской области от 12 апреля 2010 года № 4
title:
  rus: Об организации и обеспечении приписки граждан к призывному участку Денисовского района
  kaz: Азаматтарды Денисов ауданының шақыру учаскесіне тіркеуді ұйымдастыру мен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-06
approved_by:
- '162006000003'
version_date:
  kaz: 2010-01-06
  rus: 2010-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/50642/kaz/06.01.2010
  rus: https://zan.gov.kz/client/#!/doc/50642/rus/06.01.2010
