act_code: '122155'
requisite: Решение маслихата города Лисаковска Костанайской области от 25 мая 2018 года № 253. Зарегистрировано Департаментом юстиции Костанайской области 31 мая 2018 года № 7807. Утратило силу решением маслихата города Лисаковска Костанайской области от 13 февраля 2026 года № 223 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О корректировке базовых ставок земельного налога в городе Лисаковске
  kaz: Лисаков қаласында жер салығының базалық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-25
approved_by:
- '162020000002'
version_date:
  kaz: 2018-05-25
  rus: 2018-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/122155/kaz/25.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122155/rus/25.05.2018
