act_code: '55325'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 21 октября 2010 года № 374. Зарегистрировано Управлением юстиции Мендыкаринского района Костанайской области 9 ноября 2010 года № 9-15-137. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 22 апреля 2014 года № 252
title:
  rus: О правилах назначения жилищной помощи
  kaz: Тұрғын үй көмегін тағайындау ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-10-21
approved_by:
- '162013000002'
version_date:
  kaz: 2010-10-21
  rus: 2010-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/55325/kaz/21.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55325/rus/21.10.2010
