act_code: '55325'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 21 октября 2010 года № 374. Зарегистрировано Управлением юстиции Мендыкаринского района Костанайской области 9 ноября 2010 года № 9-15-137. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 22 апреля 2014 года № 252
title:
  rus: О правилах назначения жилищной помощи
  kaz: Тұрғын үй көмегін тағайындау ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-10-21
approved_by:
- '162013000002'
version_date:
  kaz: 2012-07-24
  rus: 2012-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/55325/kaz/24.07.2012
  rus: https://zan.gov.kz/client/#!/doc/55325/rus/24.07.2012
caused_by:
  code: '67091'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 24 июля 2012 года № 72. Зарегистрировано Департаментом юстиции Костанайской области 13 августа 2012 года № 9-15-180. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 22 апреля 2014 года № 252
  title:
    rus: О внесении изменений в решение маслихата от 21 октября 2010 года № 374 "О правилах назначения жилищной помощи"
    kaz: Мәслихаттың 2010 жылғы 21 қазандағы № 374 шешіміне "Тұрғын үй көмегін тағайындау Ережесі туралы" өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67091/rus
