act_code: '220561'
requisite: Решение маслихата Сарыкольского района Костанайской области от 29 декабря 2025 года № 387
title:
  rus: О бюджете села Тимирязевка Сарыкольского района Костанайской области на 2026-2028 годы
  kaz: Қостанай облысы Сарыкөл ауданы Тимирязев ауылының 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-29
approved_by:
- '162015000002'
version_date:
  kaz: 2026-02-24
  rus: 2026-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/220561/kaz/24.02.2026
  rus: https://zan.gov.kz/client/#!/doc/220561/rus/24.02.2026
caused_by:
  code: '222675'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 24 февраля 2026 года № 409
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2025 года № 387 «О бюджете села Тимирязевка Сарыкольского района Костанайской области на 2026-2028 годы»
    kaz: Мәслихаттың 2025 жылғы 29 желтоқсандағы № 387 «Қостанай облысы Сарыкөл ауданы Тимирязев ауылының 2026-2028 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222675/rus
