act_code: '2754'
requisite: Решение акима Костанайской области от 25 марта 1999 года № 77. Зарегистрировано Управлением юстиции Костанайской области 7 апреля 1999 года № 75.  Утратило силу решением акима Костанайской области от 19 ноября 2004 года № 50
title:
  rus: О мерах по упорядочению деятельности и обеспечению безопасности при размещении в полосе отвода автомобильных дорог области объектов передвижных автозаправочных станций
  kaz: Жылжымалы автоматты май құю стансаларының объектілерін облыстың автомобиль жолдарының бұрылыстарында орналастырғанда олардың қызметтерін ретке келтіру және қауіпсіздігін қамтамасыз ету жөніндегі шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-25
approved_by:
- '162000000003'
version_date:
  kaz: 1999-03-25
  rus: 1999-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/2754/kaz/25.03.1999
  rus: https://zan.gov.kz/client/#!/doc/2754/rus/25.03.1999
