act_code: '189682'
requisite: Решение акима Мичуринского сельского округа Костанайского района Костанайской области от 7 декабря 2023 года № 12
title:
  rus: Об установлении Акционерному обществу «Казахтелеком» право ограниченного целевого землепользования (публичный сервитут) на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне шектеулі нысаналы құқық жер пайдалану (қоғамдық сервитут) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-07
approved_by:
- '162012009002'
version_date:
  kaz: 2024-04-02
  rus: 2024-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/189682/kaz/02.04.2024
  rus: https://zan.gov.kz/client/#!/doc/189682/rus/02.04.2024
caused_by:
  code: '195143'
  requisite: Решение акима Мичуринского сельского округа Костанайского района Костанайской области от 2 апреля 2024 года № 5-р
  title:
    rus: О внесении изменений в решение акима Мичуринского сельского округа Костанайского района от 07 декабря 2023 года № 12-р «Об установлении акционерному обществу «Казахтелеком» право ограниченного целевого землепользования (публичного сервитута) на земельный участок»
    kaz: Қостанай ауданының Мичурин ауылдық округі әкімінің «Қазақтелеком» акционерлік қоғамына жер учаскесіне қауымдық сервитут белгілеу туралы» 2023 жылғы 7 желтоқсандағы № 12-ш шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195143/rus
