act_code: '191744'
requisite: Решение маслихата Аулиекольского района Костанайской области от 27 декабря 2023 года № 128
title:
  rus: О бюджете Новонежинского сельского округа Аулиекольского района на 2024-2026 годы
  kaz: Әулиекөл ауданы Новонежин ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162005000002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/191744/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191744/rus/18.12.2024
caused_by:
  code: '204338'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 18 декабря 2024 года № 243
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2023 года № 128 «О бюджете Новонежинского сельского округа Аулиекольского района на 2024-2026 годы»
    kaz: Мәслихаттың 2023 жылғы 27 желтоқсандағы № 128 «Әулиекөл ауданы Новонежин ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204338/rus
