act_code: '229907'
requisite: Решение акима Диевского сельского округа Аулиекольского района Костанайской области от 9 сентября 2026 года № 4
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-09
approved_by:
- '162005002002'
version_date:
  kaz: 2026-09-09
  rus: 2026-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/229907/kaz/09.09.2026
  rus: https://zan.gov.kz/client/#!/doc/229907/rus/09.09.2026
