act_code: '150848'
requisite: Решение маслихата Сарыкольского района Костанайской области от 28 декабря 2020 года № 398. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2020 года № 9672
title:
  rus: О районном бюджете Сарыкольского района на 2021-2023 годы
  kaz: Сарыкөл ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '162015000002'
version_date:
  kaz: 2021-08-27
  rus: 2021-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/150848/kaz/27.08.2021
  rus: https://zan.gov.kz/client/#!/doc/150848/rus/27.08.2021
caused_by:
  code: '158485'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 27 августа 2021 года № 51. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 сентября 2021 года № 24317
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2020 года № 398 «О районном бюджете Сарыкольского района на 2021-2023 годы»
    kaz: Мәслихаттың 2020 жылғы 28 желтоқсандағы № 398 «Сарыкөл ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158485/rus
