act_code: '140087'
requisite: Решение акима района Беимбета Майлина Костанайской области от 5 марта 2020 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 10 марта 2020 года № 9010
title:
  rus: Об образовании избирательных участков на территории района Беимбета Майлина
  kaz: Бейімбет Майлин ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-05
approved_by:
- '162016000003'
version_date:
  kaz: 2023-11-09
  rus: 2023-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/140087/kaz/09.11.2023
  rus: https://zan.gov.kz/client/#!/doc/140087/rus/09.11.2023
caused_by:
  code: '188166'
  requisite: Решение акима района Беимбета Майлина Костанайской области от 9 ноября 2023 года № 4. Зарегистрировано в Департаменте юстиции Костанайской области 10 ноября 2023 года № 10078
  title:
    rus: О внесении изменения в решение акима района Беимбета Майлина от 5 марта 2020 года № 1 «Об образовании избирательных участков на территории района Беимбета Майлина»
    kaz: Бейімбет Майлин ауданы әкімінің 2020 жылғы 5 наурыздағы № 1 «Бейімбет Майлин ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188166/rus
