act_code: '130828'
requisite: Решение акима села Пригородное Житикаринского района Костанайской области от 12 апреля 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 18 апреля 2019 года № 8360
title:
  rus: Об установлении публичного сервитута на земельный участок
  kaz: Жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-12
approved_by:
- '162008009001'
version_date:
  kaz: 2019-04-12
  rus: 2019-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/130828/kaz/12.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130828/rus/12.04.2019
