act_code: '162527'
requisite: Решение маслихата Аулиекольского района Костанайской области от 27 декабря 2021 года № 77. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26211
title:
  rus: О районном бюджете Аулиекольского района Костанайской области на 2022-2024 годы
  kaz: Қостанай облысы Әулиекөл ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '162005000002'
version_date:
  kaz: 2022-02-25
  rus: 2022-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/162527/kaz/25.02.2022
  rus: https://zan.gov.kz/client/#!/doc/162527/rus/25.02.2022
caused_by:
  code: '164914'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 25 февраля 2022 года № 105
  title:
    rus: О внесении изменений в решение Аулиекольского районного маслихата Костанайской области от 27 декабря 2021 года № 77 «О районном бюджете Аулиекольского района Костанайской области на 2022-2024 годы»
    kaz: Қостанай облысы Әулиекөл аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 77 «Қостанай облысы Әулиекөл ауданының 2022-2024 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164914/rus
