act_code: '187403'
requisite: Решение маслихата Федоровского района Костанайской области от 19 октября 2023 года № 73
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определении количества представителей жителей сел для участия в сходе местного сообщества Вишневого сельского округа Федоровского района
  kaz: Федоров ауданы Вишневый ауылдық округі жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің санын айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-19
approved_by:
- '162018000002'
version_date:
  kaz: 2023-10-19
  rus: 2023-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/187403/kaz/19.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187403/rus/19.10.2023
