act_code: '37699'
requisite: Решение маслихата Сарыкольского района Костанайской области от 4 февраля 2008 года № 38. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 18 февраля 2008 года № 9-17-53. Утратило силу решением маслихата Сарыкольского района Костанайской области от 28 апреля 2009 года № 114
title:
  rus: О базовых ставках земельного налога в Сарыкольском районе на 2008-2010 годы
  kaz: 2008-2010 жылдарға арналған Сарыкөл ауданында жер салығының базалық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-04
approved_by:
- '162015000002'
version_date:
  kaz: 2008-02-04
  rus: 2008-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/37699/kaz/04.02.2008
  rus: https://zan.gov.kz/client/#!/doc/37699/rus/04.02.2008
