act_code: '227100'
requisite: Решение акима Октябрьского сельского округа Карасуского района Костанайской области от 1 июля 2026 года № 3
title:
  rus: Об установлении публичного сервитута частной компании «Kazakhstan JinijangCo., Ltd»
  kaz: «Kazakhstan JinijangCo., Ltd» жеке компаниясына жария сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-01
approved_by:
- '162011019001'
version_date:
  kaz: 2026-07-01
  rus: 2026-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/227100/kaz/01.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227100/rus/01.07.2026
