act_code: '63597'
requisite: Решение маслихата Костанайского района Костанайской области от 13 февраля 2012 года № 15. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 23 февраля 2012 года № 9-14-169
title:
  rus: О предоставлении в 2012 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты района
  kaz: Ауданның ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын 2012 жылы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-13
approved_by:
- '162012000002'
version_date:
  kaz: 2012-05-22
  rus: 2012-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/63597/kaz/22.05.2012
  rus: https://zan.gov.kz/client/#!/doc/63597/rus/22.05.2012
caused_by:
  code: '66077'
  requisite: Решение маслихата Костанайского района Костанайской области от 22 мая 2012 года № 39. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 14 июня 2012 года № 9-14-178
  title:
    rus: О внесении изменений в решение маслихата от 13 февраля 2012 года № 15 "О предоставлении в 2012 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты района"
    kaz: Мәслихаттың 2012 жылғы 13 ақпандағы № 15 "Ауданның ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын 2012 жылы ұсыну туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66077/rus
