act_code: '104345'
requisite: Решение маслихата Карабалыкского района Костанайской области от 3 июня 2016 года № 33. Зарегистрировано Департаментом юстиции Костанайской области 12 июля 2016 года № 6538. Утратило силу решением маслихата Карабалыкского района Костанайской области от 27 июня 2018 года № 265
title:
  rus: О повышении базовых ставок  земельного налога и ставок единого земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-03
approved_by:
- '162010000002'
version_date:
  kaz: 2016-06-03
  rus: 2016-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/104345/kaz/03.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104345/rus/03.06.2016
