act_code: '38040'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 21 января 2008 года № 41. Зарегистрировано Управлением юстиции Алтынсаринского района Костанайской области 23 февраля 2008 года № 9-5-58
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам сфер социального обеспечения, образования, культуры работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет саласы мамандарына жиырма бес процентке жоғары лауазымдық жалақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-21
approved_by:
- '162003000002'
version_date:
  kaz: 2008-01-21
  rus: 2008-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/38040/kaz/21.01.2008
  rus: https://zan.gov.kz/client/#!/doc/38040/rus/21.01.2008
