act_code: '44206'
requisite: Решение акима Карасуского района Костанайской области от 19 января 2009 года № 2. Зарегистрировано Управлением юстиции Карасуского района Костанайской области 16 февраля 2009 года № 9-13-75
title:
  rus: Об организации и обеспечении приписки граждан мужского пола 1992 года рождения к призывному участку в 2009 году
  kaz: 2009 жылы шақыру учаскесіне 1992 жылғы туған еркек жынысты азаматтардың тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-19
approved_by:
- '162011000003'
version_date:
  kaz: 2009-01-19
  rus: 2009-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44206/kaz/19.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44206/rus/19.01.2009
