act_code: '138524'
requisite: Решение маслихата Костанайского района Костанайской области от 13 января 2020 года № 466. Зарегистрировано Департаментом юстиции Костанайской области 15 января 2020 года № 8895
title:
  rus: О бюджетах города Тобыл, сельских округов Костанайского района на 2020-2022 годы
  kaz: Қостанай ауданы Тобыл қаласының, ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '162012000002'
version_date:
  kaz: 2020-01-13
  rus: 2020-01-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/138524/kaz/13.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138524/rus/13.01.2020
