act_code: '119616'
requisite: Решение акима Буденновского сельского округа Мендыкаринского района Костанайской области от 27 февраля 2018 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 16 марта 2018 года № 7601
title:
  rus: О переименовании составной части села Буденновка Буденновского сельского округа Мендыкаринского района
  kaz: Меңдіқара ауданы Буденный ауылдық округінің Буденновка ауылының құрамдас бөлігін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-27
approved_by:
- '162013003002'
version_date:
  kaz: 2018-02-27
  rus: 2018-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/119616/kaz/27.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119616/rus/27.02.2018
