act_code: '6080'
requisite: Решение акима Костанайской области от 18 мая 2000 года № 110. Зарегистрировано Управлением юстиции Костанайской области 24 мая 2000 года № 265.  Утратило силу решением акима Костанайской области от 12 ноября 2009 года № 27
title:
  rus: О публикации в средствах массовой информации решений и распоряжений акима Костанайской области
  kaz: Қостанай облысы әкімінің шешімдері мен өкімдерін бұқаралық ақпарат құралдарында жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-05-17
approved_by:
- '162000000003'
version_date:
  kaz: 2000-05-17
  rus: 2000-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/6080/kaz/17.05.2000
  rus: https://zan.gov.kz/client/#!/doc/6080/rus/17.05.2000
