act_code: '89017'
requisite: Решение маслихата Узункольского района Костанайской области от 20 марта 2015 года № 283. Зарегистрировано Департаментом юстиции Костанайской области 24 апреля 2015 года № 5539. Утратило силу решением маслихата Узункольского района Костанайской области от 3 марта 2020 года № 348 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Пресногорьковского сельского округа Узункольского района Костанайской области
  kaz: Қостанай облысы Ұзынкөл ауданы Пресногорьков ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-20
approved_by:
- '162017000002'
version_date:
  kaz: 2015-03-20
  rus: 2015-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/89017/kaz/20.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89017/rus/20.03.2015
