act_code: '48378'
requisite: Решение акима Тарановского сельского округа Тарановского района Костанайской области от 26 октября 2009 года № 10. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 30 октября 2009 года № 9-18-99
title:
  rus: О присвоении наименования составным частям населенных пунктов сельского округа Әйет
  kaz: Әйет ауылдық округі елді мекендерінің құрамдас бөлектеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-26
approved_by:
- '162016001002'
version_date:
  rus: 2014-05-05
source:
  rus: https://zan.gov.kz/client/#!/doc/48378/rus/05.05.2014
