act_code: '208792'
requisite: Решение акима Денисовского сельского округа Денисовского района Костанайской области от 2 апреля 2025 года № 4
title:
  rus: Об установлении публичного сервитута государственному учреждению «Отдел архитектуры, градостроительства и строительства акимата Денисовского района»
  kaz: «Денисов ауданы әкімдігінің сәулет, қала құрылысы және құрылыс бөлімі» мемлекеттік мекемесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-02
approved_by:
- '162006008002'
version_date:
  kaz: 2025-04-02
  rus: 2025-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/208792/kaz/02.04.2025
  rus: https://zan.gov.kz/client/#!/doc/208792/rus/02.04.2025
