act_code: '120554'
requisite: Решение маслихата Узункольского района Костанайской области от 19 марта 2018 года № 190. Зарегистрировано Департаментом юстиции Костанайской области 10 апреля 2018 года № 7685. Утратило силу решением маслихата Узункольского района Костанайской области от 24 июня 2026 года № 234 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Узункольского районного маслихата»
  kaz: «Ұзынкөл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттiк әкiмшiлiк қызметшiлерiнiң қызметiн бағалау әдiстемесiн бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-19
approved_by:
- '162017000002'
version_date:
  kaz: 2022-03-04
  rus: 2022-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/120554/kaz/04.03.2022
  rus: https://zan.gov.kz/client/#!/doc/120554/rus/04.03.2022
caused_by:
  code: '165040'
  requisite: Решение маслихата Узункольского района Костанайской области от 4 марта 2022 года № 127. Отменено решением маслихата Узункольского района Костанайской области от 19 мая 2026 года № 231 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 19 марта 2018 года № 190 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Узункольского районного маслихата»
    kaz: Мәслихаттың 2018 жылғы 19 наурыздағы № 190 «Ұзынкөл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165040/rus
