act_code: '227263'
requisite: Решение маслихата города Рудного Костанайской области от 30 июня 2026 года № 292
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-06-30
approved_by:
- '162021000002'
version_date:
  kaz: 2026-08-19
  rus: 2026-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/227263/kaz/19.08.2026
  rus: https://zan.gov.kz/client/#!/doc/227263/rus/19.08.2026
caused_by:
  code: '229293'
  requisite: Решение Рудненского городского маслихата Костанайской области от 19 августа 2026 года № 306
  title:
    rus: О внесении изменения в решение маслихата от 30 июня 2026 года № 292 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2026 жылғы 30 маусымдағы № 292 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229293/rus
