act_code: '221226'
requisite: Решение маслихата Наурзумского района Костанайской области от 8 января 2026 года № 273
title:
  rus: О бюджете села Шили Наурзумского района на 2026-2028 годы
  kaz: Науырзым ауданы Шилі ауылының 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-08
approved_by:
- '162014000002'
version_date:
  kaz: 2026-03-30
  rus: 2026-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/221226/kaz/30.03.2026
  rus: https://zan.gov.kz/client/#!/doc/221226/rus/30.03.2026
caused_by:
  code: '223403'
  requisite: Решение маслихата Наурзумского района Костанайской области от 30 марта 2026 года № 285
  title:
    rus: О внесении изменений в решение Наурзумского районного маслихата от 08 января 2026 года № 273 «О бюджете села Шили Наурзумского района на 2026-2028 годы»
    kaz: Мәслихаттың 2026 жылғы 8 қаңтардағы № 273 «Науырзым ауданы Шилі ауылының 2026-2028 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223403/rus
