act_code: '170907'
requisite: Решение маслихата Карабалыкского района Костанайской области от 18 августа 2022 года № 163. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 августа 2022 года № 29246
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Карабалыкскому району
  kaz: Қарабалық ауданы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-18
approved_by:
- '162010000002'
version_date:
  kaz: 2022-08-18
  rus: 2022-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/170907/kaz/18.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170907/rus/18.08.2022
