act_code: '191753'
requisite: Решение маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 93. Зарегистрировано в Департаменте юстиции Костанайской области 5 января 2024 года № 10125-10. Утратило силу решением Житикаринского районного маслихата Костанайской области от 4 сентября 2026 года № 462 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162008000002'
version_date:
  kaz: 2024-09-18
  rus: 2024-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/191753/kaz/18.09.2024
  rus: https://zan.gov.kz/client/#!/doc/191753/rus/18.09.2024
caused_by:
  code: '201032'
  requisite: Решение маслихата Житикаринского района Костанайской области от 18 сентября 2024 года № 211. Зарегистрировано в Департаменте юстиции Костанайской области 27 сентября 2024 года № 10270-10. Утратило силу решением Житикаринского районного маслихата Костанайской области от 4 сентября 2026 года № 462 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 27 декабря 2023 года № 93 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2023 жылғы 27 желтоқсандағы № 93 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201032/rus
