act_code: '215530'
requisite: Решение акима Новоильиновского сельского округа района Беимбета Майлина Костанайской области от 13 октября 2025 года № 6
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-13
approved_by:
- '162016010002'
version_date:
  kaz: 2025-10-13
  rus: 2025-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/215530/kaz/13.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215530/rus/13.10.2025
