act_code: '123228'
requisite: Решение акима Большечураковского сельского округа Алтынсаринского района Костанайской области от 27 июня 2018 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 3 июля 2018 года № 7920
title:
  rus: О снятии ограничительных мероприятий по бруцеллезу крупного рогатого скота в селе Большая Чураковка Большечураковского сельского округа Алтынсаринского района
  kaz: Алтынсарин ауданы Большая чураковка ауылдық округіндегі Большая Чураковка ауылында ірі қара малдың бруцеллезы бойынша шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-27
approved_by:
- '162003001002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/123228/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123228/rus/27.06.2018
