act_code: '162859'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 28 декабря 2021 года № 67. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2021 года № 26286
title:
  rus: О бюджете Мендыкаринского района на 2022 - 2024 годы
  kaz: Меңдіқара ауданының 2022 - 2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '162013000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/162859/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/162859/rus/15.12.2022
caused_by:
  code: '175424'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 15 декабря 2022 года № 172
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2021 года № 67 «О бюджете Мендыкаринского района на 2022 - 2024 годы»
    kaz: Мәслихаттың 2021 жылғы 28 желтоқсандағы № 67 «Меңдіқара ауданының 2022 - 2024 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175424/rus
