act_code: '103833'
requisite: Решение маслихата города Костаная Костанайской области от 3 июня 2016 года № 41. Зарегистрировано Департаментом юстиции Костанайской области 29 июня 2016 года № 6509. Утратило силу решением маслихата города Костаная Костанайской области от 28 августа 2020 года № 511 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-06-03
approved_by:
- '162002000002'
version_date:
  kaz: 2019-11-11
  rus: 2019-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/103833/kaz/11.11.2019
  rus: https://zan.gov.kz/client/#!/doc/103833/rus/11.11.2019
caused_by:
  code: '136008'
  requisite: Решение маслихата города Костаная Костанайской области от 11 ноября 2019 года № 415. Зарегистрировано Департаментом юстиции Костанайской области 15 ноября 2019 года № 8752. Утратило силу решением маслихата города Костаная Костанайской области от 28 августа 2020 года № 511 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 3 июня 2016 года № 41 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихатының 2016 жылғы 3 маусымдағы № 41 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136008/rus
