act_code: '189270'
requisite: Решение маслихата Житикаринского района Костанайской области от 30 ноября 2023 года № 85. Утратило силу решением маслихата Житикаринского района Костанайской области от 15 марта 2024 года № 144 (вводится в действие со дня его официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей для участия в сходе местного сообщества на территории населенных пунктов Житикаринского района
  kaz: Жітіқара ауданының елді мекендері аумағындағы бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін тұрғындар өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2023-11-30
approved_by:
- '162008000002'
version_date:
  kaz: 2023-11-30
  rus: 2023-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/189270/kaz/30.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189270/rus/30.11.2023
