act_code: '62457'
requisite: Решение акима Денисовского района Костанайской области от 5 декабря 2011 года № 13. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 30 декабря 2011 года № 9-8-190. Прекратило действие в связи с истечением срока действия - письмо акима Денисовского района Костанайской области от 5 апреля 2012 года № 2044
title:
  rus: Об организации и обеспечении приписки граждан Республики Казахстан к призывному участку Денисовского района
  kaz: Қазақстан Республикасының азаматтарын Денисов ауданының шақыру учаскесіне тіркеуді ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-05
approved_by:
- '162006000003'
version_date:
  kaz: 2011-12-05
  rus: 2011-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62457/kaz/05.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62457/rus/05.12.2011
