act_code: '222125'
requisite: Решение маслихата Денисовского района Костанайской области от 12 февраля 2026 года № 6
title:
  rus: Об утверждении ставок туристского взноса для иностранцев по Денисовскому району на 2026 год
  kaz: Денисов ауданы бойынша 2026 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-12
approved_by:
- '162006000002'
version_date:
  kaz: 2026-02-12
  rus: 2026-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/222125/kaz/12.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222125/rus/12.02.2026
