act_code: '220004'
requisite: Решение маслихата города Аркалыка Костанайской области от 23 декабря 2025 года № 202
title:
  rus: О бюджетах сел и сельских округов города Аркалыка на 2026-2028 годы
  kaz: Арқалық қаласы ауылдарының және ауылдық округтерінің 2026-2028 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '162019000002'
version_date:
  kaz: 2025-12-23
  rus: 2025-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/220004/kaz/23.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220004/rus/23.12.2025
