act_code: '217129'
requisite: Решение маслихата города Лисаковска Костанайской области от 20 ноября 2025 года № 202
title:
  rus: Об отмене некоторых решений Лисаковского городского маслихата
  kaz: Лисаков қалалық мәслихатының кейбір шешімдерін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-20
approved_by:
- '162020000002'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/217129/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217129/rus/20.11.2025
