act_code: '49617'
requisite: Решение маслихата Тарановского района Костанайской области от 25 декабря 2009 года № 233. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 29 декабря 2009 года № 9-18-106
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '162016000002'
version_date:
  kaz: 2010-04-20
  rus: 2010-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/49617/kaz/20.04.2010
  rus: https://zan.gov.kz/client/#!/doc/49617/rus/20.04.2010
caused_by:
  code: '51991'
  requisite: Решение маслихата Тарановского района Костанайской области от 20 апреля 2010 года № 258. Зарегистрировано Управлением юстиции Тарановского района Костанайской области 27 апреля 2010 года № 9-18-122
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 25 декабря 2009 года № 233 "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджеті туралы" мәслихаттың 2009 жылғы 25 желтоқсандағы № 233 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/51991/rus
