act_code: '204859'
requisite: Решение и.о. акима поселка Карабалык Карабалыкского района Костанайской области от 25 декабря 2024 года № 25-р
title:
  rus: Об установлении публичного сервитута государственному учреждению «Управление строительства, архитектуры и градостроительства акимата Костанайской области»
  kaz: «Қостанай облысы әкімдігінің құрылыс, сәулет және қала құрылысы басқармасы» мемлекеттік мекемесіне қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '162010014001'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204859/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204859/rus/25.12.2024
