act_code: '88743'
requisite: Решение маслихата Джангельдинского района Костанайской области от 3 апреля 2015 года № 219. Зарегистрировано Департаментом юстиции Костанайской области 15 апреля 2015 года № 5527. Утратило силу решением маслихата Жангельдинского района Костанайской области от 18 января 2016 года № 253
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-04-03
approved_by:
- '162007000002'
version_date:
  kaz: 2015-04-03
  rus: 2015-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/88743/kaz/03.04.2015
  rus: https://zan.gov.kz/client/#!/doc/88743/rus/03.04.2015
