act_code: '170545'
requisite: Решение маслихата Денисовского района Костанайской области от 10 августа 2022 года № 72. Отменено решением маслихата Денисовского района Костанайской области от 8 ноября 2023 года № 68 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села для участия в сходе местного сообщества села Перелески Денисовского района Костанайской области
  kaz: Қостанай облысы Денисов ауданы Перелески ауылының бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылы тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-08-10
approved_by:
- '162006000002'
version_date:
  kaz: 2022-08-10
  rus: 2022-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/170545/kaz/10.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170545/rus/10.08.2022
