act_code: '122985'
requisite: Решение маслихата Костанайского района Костанайской области от 30 мая 2018 года № 268. Зарегистрировано Департаментом юстиции Костанайской области 21 июня 2018 года № 7891. Утратило силу решением маслихата Костанайского района Костанайской области от 9 апреля 2019 года № 383 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества села Озерное Костанайского района Костанайской области
  kaz: Қостанай облысы Қостанай ауданы Озерный ауылының жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-30
approved_by:
- '162012000002'
version_date:
  kaz: 2018-05-30
  rus: 2018-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/122985/kaz/30.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122985/rus/30.05.2018
