act_code: '36508'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 21 декабря 2007 года № 31. Зарегистрировано Управлением юстиции Алтынсаринского района Костанайской области 3 января 2008 года № 9-5-55. Утратило силу решением маслихата Алтынсаринского района Костанайской области от 20 февраля 2008 года № 57
title:
  rus: Об определении перечня должностей специалистов сфер социального обеспечения, образования, культуры, работающих в аульной (сельской) местности и имеющих право на повышенные не менее чем на двадцать пять процентов должностные оклады и тарифные ставки, за счет средств районного бюджета на 2008 год
  kaz: 2008 жылға арналған аудандық бюджет қаражаттары есебінен, ауылдық (селолық) жерде жұмыс істейтін және лауазымдық жалақылары мен тарифтік ставкаларын кемінде жиырма бес пайызға көтеруге құқығы бар, әлеуметтік қамсыздандыру, білім беру, мәдениет салаларының мамандары лауазымдарының тізбесін белгілеу туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2007-12-21
approved_by:
- '162003000002'
version_date:
  kaz: 2007-12-21
  rus: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/36508/kaz/21.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36508/rus/21.12.2007
