act_code: '221077'
requisite: Решение акима Тогузакского сельского округа Карабалыкского района Костанайской области от 26 декабря 2025 года № 15
title:
  rus: О предоставлении товариществу с ограниченной ответственностью «ЭПК-forfait» права ограниченного целевого землепользования (публичный сервитут) для обслуживания и эксплуатации воздушных линии электропередач
  kaz: «ЭПК-forfait» жауапкершілігі шектеулі серіктестігіне әуе электр беру желілеріне қызмет көрсету және пайдалану үшін шектеулі нысаналы жер пайдалану құқығын (қоғамдық сервитут) беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '162010006002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/221077/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221077/rus/26.12.2025
