act_code: '106523'
requisite: Решение маслихата города Рудного Костанайской области от 29 августа 2016 года № 49. Зарегистрировано Департаментом юстиции Костанайской области 26 сентября 2016 года № 6626. Утратило силу решением маслихата города Рудного Костанайской области от 4 декабря 2017 года № 183
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-29
approved_by:
- '162021000002'
version_date:
  kaz: 2016-08-29
  rus: 2016-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/106523/kaz/29.08.2016
  rus: https://zan.gov.kz/client/#!/doc/106523/rus/29.08.2016
