act_code: '201340'
requisite: Решение акима Тохтаровского сельского округа Житикаринского района Костанайской области от 30 сентября 2024 года № 8
title:
  rus: Об установлении публичного сервитута на земельные участки
  kaz: Жер учаскелеріне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-30
approved_by:
- '162008003002'
version_date:
  kaz: 2024-09-30
  rus: 2024-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/201340/kaz/30.09.2024
  rus: https://zan.gov.kz/client/#!/doc/201340/rus/30.09.2024
