act_code: '227164'
requisite: Решение маслихата Узункольского района Костанайской области от 24 июня 2026 года № 234. Зарегистрировано в Министерстве юстиции Республики Казахстан 2 июля 2026 года № 39188
title:
  rus: О признании утратившим силу решения маслихата Узункольского района Костанайской области от 19 марта 2018 года № 190 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Узункольского районного маслихата»
  kaz: «Ұзынкөл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» Қостанай облысы Ұзынкөл ауданы мәслихатының 2018 жылғы 19 наурыздағы № 190 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-24
approved_by:
- '162017000002'
version_date:
  kaz: 2026-06-24
  rus: 2026-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/227164/kaz/24.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227164/rus/24.06.2026
