act_code: '31984'
requisite: Решение маслихата Узункольского района Костанайской области от 19 января 2007 года № 321. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 19 февраля 2007 года № 9-19-38. Утратило силу решением маслихата Узункольского района Костанайской области от 23 мая 2007 года № 360
title:
  rus: Об установлении единой ставки акциза на объекты игорного бизнеса для налогоплательщиков, оказывающих услуги игровых автоматов с денежным выигрышем
  kaz: Ақшалай ұтысы бар ойын автоматтар бойынша қызмет көрсететін, салық төлеушілер үшін ойын бизнес объектілеріне белгіленген бірынғай акциз ставкасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-19
approved_by:
- '162017000002'
version_date:
  kaz: 2007-01-19
  rus: 2007-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/31984/kaz/19.01.2007
  rus: https://zan.gov.kz/client/#!/doc/31984/rus/19.01.2007
