act_code: '190999'
requisite: Решение маслихата Камыстинского района Костанайской области от 25 декабря 2023 года № 123
title:
  rus: О районном бюджете Камыстинского района на 2024 – 2026 годы
  kaz: Қамысты ауданының 2024 - 2026 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '162009000002'
version_date:
  kaz: 2023-12-25
  rus: 2023-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/190999/kaz/25.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190999/rus/25.12.2023
