act_code: '190999'
requisite: Решение маслихата Камыстинского района Костанайской области от 25 декабря 2023 года № 123
title:
  rus: О районном бюджете Камыстинского района на 2024 – 2026 годы
  kaz: Қамысты ауданының 2024 - 2026 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '162009000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/190999/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/190999/rus/22.02.2024
caused_by:
  code: '193581'
  requisite: Решение маслихата Камыстинского района Костанайской области от 22 февраля 2024 года № 149
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2023 года № 123 «О районном бюджете Камыстинского района на 2024-2026 годы»
    kaz: Мәслихаттың 2023 жылғы 25 желтоқсандағы № 123 «Қамысты ауданының 2024-2026 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193581/rus
