act_code: '127406'
requisite: Решение маслихата Денисовского района Костанайской области от 26 декабря 2018 года № 245. Зарегистрировано Департаментом юстиции Костанайской области 27 декабря 2018 года № 8201
title:
  rus: О бюджете Денисовского района на 2019-2021 годы
  kaz: Денисов ауданының 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-26
approved_by:
- '162006000002'
version_date:
  kaz: 2019-11-29
  rus: 2019-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127406/kaz/29.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127406/rus/29.11.2019
caused_by:
  code: '136614'
  requisite: Решение маслихата Денисовского района Костанайской области от 29 ноября 2019 года № 81. Зарегистрировано Департаментом юстиции Костанайской области 4 декабря 2019 года № 8807
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 26 декабря 2018 года № 245 «О бюджете Денисовского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 26 желтоқсандағы № 245 «Денисов ауданының 2019-2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136614/rus
