act_code: '85605'
requisite: Решение маслихата Наурзумского района Костанайской области от 24 декабря 2014 года № 263. Зарегистрировано Департаментом юстици Костанайской области 8 января 2015 года № 5276
title:
  rus: О районном бюджете Наурзумского района на 2015-2017 годы
  kaz: Науырзым ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162014000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85605/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85605/rus/24.12.2014
