act_code: '120761'
requisite: Решение акима Ушаковского сельского округа Карасуского района Костанайской области от 19 марта 2018 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 12 апреля 2018 года № 7701
title:
  rus: О переименовании составной части села Ушаково Ушаковского сельского округа
  kaz: Ушаков ауылдық округі Ушаков ауылының құрамдас бөлігін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-19
approved_by:
- '162011011002'
version_date:
  kaz: 2018-03-19
  rus: 2018-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/120761/kaz/19.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120761/rus/19.03.2018
