act_code: '5872'
requisite: Решение акима Костанайской области от 10 декабря 1999 года № 256. Зарегистрировано Управлением юстиции Костанайской области 17 апреля 2000 года № 231. Утратило силу решением акима Костанайской области от 24 декабря 2004 года № 59
title:
  rus: О запрещении сбора (заготовки) лома и отходов цветных металлов
  kaz: Түсті металлдардың сынықтары мен қалдықтарын қабылдауға тыйым салу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-10
approved_by:
- '162000000003'
version_date:
  kaz: 1999-12-10
  rus: 1999-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/5872/kaz/10.12.1999
  rus: https://zan.gov.kz/client/#!/doc/5872/rus/10.12.1999
