act_code: '131070'
requisite: Решение акима села Троебратское Узункольского района Костанайской области от 23 апреля 2019 года № 01-р. Зарегистрировано Департаментом юстиции Костанайской области 23 апреля 2019 года № 8372
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «SilkNetCom»
  kaz: «SilkNetCom» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-23
approved_by:
- '162017016001'
version_date:
  kaz: 2019-04-23
  rus: 2019-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/131070/kaz/23.04.2019
  rus: https://zan.gov.kz/client/#!/doc/131070/rus/23.04.2019
