act_code: '106421'
requisite: Решение маслихата Федоровского района Костанайской области от 31 августа 2016 года № 61. Зарегистрировано Департаментом юстиции Костанайской области 21 сентября 2016 года № 6625. Утратило силу решением маслихата Федоровского района Костанайской области от 7 сентября 2020 года № 465 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-08-31
approved_by:
- '162018000002'
version_date:
  kaz: 2019-06-17
  rus: 2019-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/106421/kaz/17.06.2019
  rus: https://zan.gov.kz/client/#!/doc/106421/rus/17.06.2019
caused_by:
  code: '132567'
  requisite: Решение маслихата Федоровского района Костанайской области от 17 июня 2019 года № 349. Зарегистрировано Департаментом юстиции Костанайской области 20 июня 2019 года № 8548. Утратило силу решением маслихата Федоровского района Костанайской области от 7 сентября 2020 года № 465 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 31 августа 2016 года № 61 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2016 жылғы 31 тамыздағы № 61 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132567/rus
