act_code: '32785'
requisite: Решение маслихата Карабалыкского района Костанайской области от 30 марта 2007 года № 308. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 16 апреля 2007 года № 9-12-43
title:
  rus: Об утверждении Правил оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-03-30
approved_by:
- '162010000002'
version_date:
  kaz: 2007-03-30
  rus: 2007-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/32785/kaz/30.03.2007
  rus: https://zan.gov.kz/client/#!/doc/32785/rus/30.03.2007
