act_code: '108683'
requisite: Решение маслихата города Рудного Костанайской области от 21 декабря 2016 года № 66. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2016 года № 6772
title:
  rus: О городском бюджете города Рудного на 2017-2019 годы
  kaz: Рудный қаласының 2017-2019 жылдарға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-21
approved_by:
- '162021000002'
version_date:
  kaz: 2016-12-21
  rus: 2016-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/108683/kaz/21.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108683/rus/21.12.2016
