act_code: '42928'
requisite: Решение акима Банновского сельского округа Федоровского района Костанайской области от 18 ноября 2008 года № 30. Зарегистрировано Управлением юстиции Федоровского района Костанайской области 22 декабря 2008 года № 9-20-133
title:
  rus: О наименовании составных частей населенного пункта села Каракопа Банновского сельского округа
  kaz: Баннов ауылдық округінің Каракопа ауылының құрамдас бөлігін атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-18
approved_by:
- '162018001002'
version_date:
  kaz: 2008-11-18
  rus: 2008-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/42928/kaz/18.11.2008
  rus: https://zan.gov.kz/client/#!/doc/42928/rus/18.11.2008
