act_code: '194358'
requisite: Решение маслихата Костанайского района Костанайской области от 5 марта 2024 года № 146. Зарегистрировано в Департаменте юстиции Костанайской области 14 марта 2024 года № 10159-10
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки города Тобыл и населенных пунктов Костанайского района
  kaz: Қостанай ауданының Тобыл қаласы мен елді мекендерінің жер учаскелері үшін төлемақының базалық ставкаларына жерді аймақтарға бөлу жобасын (схемасын), бағалау аймақтарының шекараларын және түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2024-03-05
approved_by:
- '162012000002'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/194358/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194358/rus/05.03.2024
