act_code: '190893'
requisite: Решение акима Костанайского района Костанайской области от 27 декабря 2023 года № 5. Утратило силу решением акима Костанайского района Костанайской области от 26 марта 2024 года № 3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации местного масштаба природного характера на территории Костанайского района
  kaz: Қостанай ауданының аумағында табиғи сипаттағы жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162012000003'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/190893/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190893/rus/27.12.2023
