act_code: '176542'
requisite: Решение маслихата Наурзумского района Костанайской области от 30 декабря 2022 года № 189
title:
  rus: О бюджете Карамендинского сельского округа Наурзумского района на 2023-2025 годы
  kaz: Науырзым ауданының Қарамеңді ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '162014000002'
version_date:
  kaz: 2023-11-23
  rus: 2023-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/176542/kaz/23.11.2023
  rus: https://zan.gov.kz/client/#!/doc/176542/rus/23.11.2023
caused_by:
  code: '188942'
  requisite: Решение маслихата Наурзумского района Костанайской области от 23 ноября 2023 года № 52
  title:
    rus: О внесении изменений в решение Наурзумского районного маслихата от 30 декабря 2022 года № 189 «О бюджете Карамендинского сельского округа Наурзумского района на 2023-2025 годы»
    kaz: «Науырзым ауданының Қарамеңді ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы» Науырзым аудандық мәслихаттың 2022 жылғы 30 желтоқсандағы № 189 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188942/rus
