act_code: '95717'
requisite: Решение маслихата Костанайской области от 14 октября 2015 года № 442. Зарегистрировано Департаментом юстиции Костанайской области 20 ноября 2015 года № 6011. Утратило силу решением маслихата Костанайской области от 15 марта 2017 года № 130
title:
  rus: Об утверждении Правил содержания и защиты зелёных насаждений, благоустройства  территорий городов и населённых пунктов Костанайской области
  kaz: Қостанай облысы қалалары мен елді мекендерінің жасыл екпелерін күтіп-ұстау және қорғау, аумақтарын абаттандыру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-10-14
approved_by:
- '162000000002'
version_date:
  kaz: 2015-10-14
  rus: 2015-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/95717/kaz/14.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95717/rus/14.10.2015
