act_code: '90957'
requisite: Решение маслихата Джангельдинского района Костанайской области от 27 мая 2015 года № 224. Зарегистрировано Департаментом юстиции Костанайской области 24 июня 2015 года № 5683. Утратило силу решением маслихата Жангельдинского района Костанайской области от 17 мая 2016 года № 24
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Джангельдинского районного маслихата"
  kaz: '"Жангелдин аудандық мәслихатының аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-05-27
approved_by:
- '162007000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/90957/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90957/rus/27.05.2015
