act_code: '202858'
requisite: Решение акима Калининского сельского округа района Беимбета Майлина Костанайской области от 18 ноября 2024 года № 7
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Трэйд Петролеум»
  kaz: «Трэйд Петролеум» жауапкершілігі шектеулі серіктестігіне қоғамдық сервитут орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-18
approved_by:
- '162016005002'
version_date:
  kaz: 2024-11-18
  rus: 2024-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/202858/kaz/18.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202858/rus/18.11.2024
