act_code: '196471'
requisite: Решение маслихата Житикаринского района Костанайской области от 29 апреля 2024 года № 158. Зарегистрировано в Департаменте юстиции Костанайской области 4 мая 2024 года № 10198-10
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Житикаринском районе
  kaz: Жітіқара ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-29
approved_by:
- '162008000002'
version_date:
  kaz: 2025-02-13
  rus: 2025-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/196471/kaz/13.02.2025
  rus: https://zan.gov.kz/client/#!/doc/196471/rus/13.02.2025
caused_by:
  code: '207324'
  requisite: Решение маслихата Житикаринского района Костанайской области от 13 февраля 2025 года № 259. Зарегистрировано в Департаменте юстиции Костанайской области 24 февраля 2025 года № 10388-10
  title:
    rus: О внесении изменения в решение маслихата от 29 апреля 2024 года № 158 «Об определении размера и порядка оказания жилищной помощи в Житикаринском районе»
    kaz: Мәслихаттың 2024 жылғы 29 сәуірдегі № 158 «Жітіқара ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207324/rus
