act_code: '76446'
requisite: Решение маслихата Аулиекольского района Костанайской области от 27 декабря 2013 года № 122. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2013 года № 4378
title:
  rus: О бюджете Аулиекольского района на 2014-2016 годы
  kaz: Әулиекөл ауданының 2014-2016 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-27
approved_by:
- '162005000002'
version_date:
  kaz: 2014-08-01
  rus: 2014-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/76446/kaz/01.08.2014
  rus: https://zan.gov.kz/client/#!/doc/76446/rus/01.08.2014
caused_by:
  code: '81856'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 1 августа 2014 года № 185. Зарегистрировано Департаментом юстиции Костанайской области 7 августа 2014 года № 4976
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 27 декабря 2013 года № 122 "О бюджете Аулиекольского района на 2014-2016 годы"
    kaz: Мәслихаттың 2013 жылғы 27 желтоқсандағы № 122 "Әулиекөл ауданының 2014-2016 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81856/rus
