act_code: '19444'
requisite: Решение маслихата города Лисаковска Костанайской области от 16 марта 2004 года № 44. Зарегистрировано Департаментом юстиции Костанайской области 6 апреля 2004 года № 2864. Утратило силу решением маслихата города Лисаковска Костанайской области от 10 июля 2008 года № 89
title:
  rus: Об утверждении Правил содержания собак и кошек на территории города Лисаковска, поселка Октябрьский, села Красногорское
  kaz: Лисаков қаласының, Октябрь поселкесінің, Красногор селосының аумағындағы иттерді және мысықтарды күтіп-ұстау ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-03-16
approved_by:
- '162020000002'
version_date:
  kaz: 2004-03-16
  rus: 2004-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/19444/kaz/16.03.2004
  rus: https://zan.gov.kz/client/#!/doc/19444/rus/16.03.2004
