act_code: '101528'
requisite: Решение маслихата Федоровского района Костанайской области от 1 апреля 2016 года № 12. Зарегистрировано в Департаменте юстиции Костанайской области 15 апреля 2016 года № 6289. Утратило силу решением маслихата Федоровского района Костанайской области от 26 апреля 2019 года № 340 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-01
approved_by:
- '162018000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/101528/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/101528/rus/01.04.2016
