act_code: '145549'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 10 августа 2020 года № 403. Зарегистрировано Департаментом юстиции Костанайской области 18 августа 2020 года № 9382. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 15 сентября 2023 года № 41 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-08-10
approved_by:
- '162016000002'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/145549/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/145549/rus/28.10.2020
caused_by:
  code: '147937'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 28 октября 2020 года № 418. Зарегистрировано Департаментом юстиции Костанайской области 30 октября 2020 года № 9529. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 15 сентября 2023 года № 41 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 10 августа 2020 года № 403 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2020 жылғы 10 тамыздағы № 403 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147937/rus
