act_code: '56561'
requisite: Решение маслихата Карабалыкского района Костанайской области от 23 декабря 2010 года № 313. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 30 декабря 2010 года № 9-12-148
title:
  rus: О районном бюджете Карабалыкского района на 2011-2013 годы
  kaz: Қарабалық ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '162010000002'
version_date:
  kaz: 2011-10-26
  rus: 2011-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/56561/kaz/26.10.2011
  rus: https://zan.gov.kz/client/#!/doc/56561/rus/26.10.2011
caused_by:
  code: '61156'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 26 октября 2011 года № 403. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 2 ноября 2011 года № 9-12-165
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 23 декабря 2010 года № 313 "О районном бюджете Карабалыкского района на 2011-2013 годы"
    kaz: Мәслихаттың 2010 жылғы 2 желтоқсандағы № 313 "Қарабалық ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61156/rus
