act_code: '124189'
requisite: Решение акима Костряковского сельского округа Федоровского района Костанайской области от 3 августа 2018 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 17 августа 2018 года № 8008
title:
  rus: О переименовании составных частей села Костряковка Костряковского сельского округа Федоровского района
  kaz: Федоров ауданы Костряков ауылдық округінің Костряков ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-03
approved_by:
- '162018008002'
version_date:
  kaz: 2018-08-03
  rus: 2018-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/124189/kaz/03.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124189/rus/03.08.2018
