act_code: '145498'
requisite: Решение маслихата Федоровского района Костанайской области от 11 августа 2020 года № 461. Зарегистрировано Департаментом юстиции Костанайской области 14 августа 2020 года № 9375
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Федоровскому району на 2020-2021 годы
  kaz: Федоров ауданы бойынша 2020-2021 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
- СХЕМ
approved_on: 2020-08-11
approved_by:
- '162018000002'
version_date:
  kaz: 2020-08-11
  rus: 2020-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/145498/kaz/11.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145498/rus/11.08.2020
