act_code: '1106'
requisite: Решение акима Костанайской области от 20 июля 1998 года № 115. Зарегистрировано Управлением юстиции Костанайской области 18 августа 1998 года № 24. Утратило силу решением акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: Об усилении мер пожарной безопасности в период заготовки грубых кормов и уборки урожая 1998 года
  kaz: 1998 жылғы табиғи жем-шөп дайындау және егін орағы кезеңінде өрт қауіпсіздігі шараларын күшейту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-07-19
approved_by:
- '162000000003'
version_date:
  kaz: 1998-07-19
  rus: 1998-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/1106/kaz/19.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1106/rus/19.07.1998
