act_code: '45692'
requisite: Решение маслихата Камыстинского района Костанайской области от 22 апреля 2009 года № 137. Зарегистрировано Управлением юстиции Камыстинского района Костанайской области 6 мая 2009 года № 9-11-91. Утратило силу решением маслихата Камыстинского района Костанайской области от 4 января 2013 года № 97 (вступает в силу со дня принятия)
title:
  rus: Об установлении стоимости разовых талонов для граждан Республики Казахстан, оралманов, деятельность, которых носит эпизодический характер, а так же для граждан Республики Казахстан, оралманов, индивидуальных предпринимателей и юридических лиц, осуществляющих деятельность по реализации товаров, выполнению работ, оказанию услуг на рынках
  kaz: Қызметі дүркін-дүркін сипатта болатын Қазақстан Республикасының азаматтары, оралмандар үшін, сондай-ақ базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары, оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '162009000002'
version_date:
  kaz: 2009-04-22
  rus: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/45692/kaz/22.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45692/rus/22.04.2009
repealed_on: 2013-01-04
repealed_by:
  code: '45692'
  requisite: Решение маслихата Камыстинского района Костанайской области от 22 апреля 2009 года № 137. Зарегистрировано Управлением юстиции Камыстинского района Костанайской области 6 мая 2009 года № 9-11-91. Утратило силу решением маслихата Камыстинского района Костанайской области от 4 января 2013 года № 97 (вступает в силу со дня принятия)
  title:
    rus: Об установлении стоимости разовых талонов для граждан Республики Казахстан, оралманов, деятельность, которых носит эпизодический характер, а так же для граждан Республики Казахстан, оралманов, индивидуальных предпринимателей и юридических лиц, осуществляющих деятельность по реализации товаров, выполнению работ, оказанию услуг на рынках
    kaz: Қызметі дүркін-дүркін сипатта болатын Қазақстан Республикасының азаматтары, оралмандар үшін, сондай-ақ базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары, оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін біржолғы талондардың құнын белгілеу туралы
  link: https://zan.gov.kz/client/#!/doc/45692/rus
