act_code: '43883'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 21 января 2009 года № 157. Зарегистрировано Управлением юстиции Мендыкаринского района Костанайской области 29 января 2009 года № 9-15-98
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам образования, культуры, социального обеспечения, работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына жиырма бес процентке жоғары лауазымдық жалақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-21
approved_by:
- '162013000002'
version_date:
  kaz: 2009-01-21
  rus: 2009-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/43883/kaz/21.01.2009
  rus: https://zan.gov.kz/client/#!/doc/43883/rus/21.01.2009
