act_code: '38514'
requisite: Решение маслихата Сарыкольского района Костанайской области от 29 февраля 2008 года № 45. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 19 марта 2008 года № 9-17-57
title:
  rus: О повышении на двадцать пять процентов должностных окладов и тарифных ставок специалистам социального обеспечения, образования, культуры, работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерде жұмыс істейтін әлеуметтік қамсыздандыру, білім беру және мәдениет мамандарына лауазымдық жалақылар мен тарифтік ставкаларды жиырма бес процентке жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-29
approved_by:
- '162015000002'
version_date:
  kaz: 2008-02-29
  rus: 2008-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/38514/kaz/29.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38514/rus/29.02.2008
