act_code: '51092'
requisite: Решение маслихата Денисовского района Костанайской области от 2 февраля 2010 года № 190. Зарегистрировано Управлением юстиции Денисовского района Костанайской области 5 марта 2010 года № 9-8-147. Утратило силу решением маслихата Денисовского района Костанайской области от 20 февраля 2015 года № 14
title:
  rus: О корректировке базовых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-02
approved_by:
- '162006000002'
version_date:
  kaz: 2010-02-02
  rus: 2010-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/51092/kaz/02.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51092/rus/02.02.2010
