act_code: '131489'
requisite: Решение акима села Новопавловка Карасуского района Костанайской области от 6 мая 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 13 мая 2019 года № 8422
title:
  rus: Об установлении публичного сервитута на земельный участок
  kaz: Жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-06
approved_by:
- '162011018001'
version_date:
  kaz: 2019-05-06
  rus: 2019-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/131489/kaz/06.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131489/rus/06.05.2019
