act_code: '11821'
requisite: Решение акима Костанайской области от 14 марта 2002 года № 31. Зарегистрировано Управлением юстиции Костанайской области 4 апреля 2002 года № 1343. Прекратил действие в связи с истечением срока применения - письмо руководителя аппарата акима Костанайской области от 24 апреля 2007 года № 08-3/1038
title:
  rus: Об утверждении Правил конкурсного отбора и назначения руководителей государственных коммунальных предприятий Костанайской области
  kaz: Қостанай облысының мемлекеттік коммуналдық кәсіпорындары басшыларын конкурстық іріктеу және тағайындау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2002-03-14
approved_by:
- '162000000003'
version_date:
  kaz: 2002-03-14
  rus: 2002-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/11821/kaz/14.03.2002
  rus: https://zan.gov.kz/client/#!/doc/11821/rus/14.03.2002
