act_code: '121948'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 4 мая 2018 года № 202. Зарегистрировано Департаментом юстиции Костанайской области 18 мая 2018 года № 7771. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 24 января 2020 года № 339 (вводится в действие для села, сельских округов с численностью населения более двух тысяч человек с 1 января 2018 года и для сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Первомайского сельского округа Мендыкаринского района
  kaz: Меңдіқара ауданы Первомай ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-04
approved_by:
- '162013000002'
version_date:
  kaz: 2019-11-15
  rus: 2019-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/121948/kaz/15.11.2019
  rus: https://zan.gov.kz/client/#!/doc/121948/rus/15.11.2019
caused_by:
  code: '136252'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 15 ноября 2019 года № 323. Зарегистрировано Департаментом юстиции Костанайской области 25 ноября 2019 года № 8774. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 24 января 2020 года № 339 (вводится в действие для села, сельских округов с численностью населения более двух тысяч человек с 1 января 2018 года и для сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 4 мая 2018 года № 202 «Об утверждении Регламента собрания местного сообщества Первомайского сельского округа Мендыкаринского района»
    kaz: Мәслихаттың 2018 жылғы 4 мамырдағы № 202 «Меңдіқара ауданы Первомай ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136252/rus
