act_code: '85602'
requisite: Решение маслихата Федоровского района Костанайской области от 27 ноября 2014 года № 276. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2014 года № 5248. Утратило силу решением маслихата Федоровского района Костанайской области от 11 октября 2021 года № 58 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов
  kaz: Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-27
approved_by:
- '162018000002'
version_date:
  kaz: 2018-02-27
  rus: 2018-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85602/kaz/27.02.2018
  rus: https://zan.gov.kz/client/#!/doc/85602/rus/27.02.2018
caused_by:
  code: '119839'
  requisite: Решение маслихата Федоровского района Костанайской области от 27 февраля 2018 года № 212. Зарегистрировано Департаментом юстиции Костанайской области 20 марта 2018 года № 7611. Утратило силу решением маслихата Федоровского района Костанайской области от 11 октября 2021 года № 58 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 27 ноября 2014 года № 276 «О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов»
    kaz: Мәслихаттың 2014 жылғы 27 қарашадағы № 276 «Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119839/rus
