act_code: '97050'
requisite: Решение маслихата Джангельдинского района Костанайской области от 21 декабря 2015 года № 246. Зарегистрировано Департаментом юстиции Костанайской области 30 декабря 2015 года № 6103
title:
  rus: О районном бюджете Джангельдинского района на 2016-2018 годы
  kaz: Жангелдин ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '162007000002'
version_date:
  kaz: 2016-08-12
  rus: 2016-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/97050/kaz/12.08.2016
  rus: https://zan.gov.kz/client/#!/doc/97050/rus/12.08.2016
caused_by:
  code: '105676'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 12 августа 2016 года № 44. Зарегистрировано Департаментом юстиции Костанайской области 24 августа 2016 года № 6600
  title:
    rus: О внесении изменений в решение маслихата от 21 декабря 2015 года № 246 «Об районном бюджете Джангельдинского района на  2016-2018 годы»
    kaz: Мәслихаттың 2015 жылғы 21  желтоқсандағы № 246 «Жангелдин ауданының 2016-2018 жылдарға арналған аудандық бюджеті туралы» шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105676/rus
