act_code: '41878'
requisite: Решение маслихата Сарыкольского района Костанайской области от 26 сентября 2008 года № 81. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 14 октября 2008 года № 9-17-69. Утратило силу решением маслихата Сарыкольского района Костанайской области от 28 апреля 2009 года № 114
title:
  rus: Об утверждении размеров стоимости разовых талонов и ставок фиксированного суммарного налога с единицы налогообложении для отдельных видов предпринимательской деятельности
  kaz: Кәсіпкерлік қызметтің жекелеген түрлері үшін біржолғы талондар құнының мөлшерін және тіркелген жиынтық салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-26
approved_by:
- '162015000002'
version_date:
  kaz: 2008-09-26
  rus: 2008-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/41878/kaz/26.09.2008
  rus: https://zan.gov.kz/client/#!/doc/41878/rus/26.09.2008
