act_code: '5855'
requisite: Решение акима Костанайской области от 29 марта 2000 года № 75. Зарегистрировано Управлением юстиции Костанайской области 18 апреля 2000 года № 232.  Утратило силу решением акима Костанайской области от 13 декабря 2004 года № 55
title:
  rus: О реализации Указа Президента Республики Казахстан «О мерах по предупреждению и пресечению проявлений терроризма и экстремизма»
  kaz: «Терроризмнің және экстремизмнің пайда болуының алдын алу және болдырмау жөніндегі шаралар туралы» Қазақстан Республикасы Президентінің Жарлығын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-28
approved_by:
- '162000000003'
version_date:
  kaz: 2000-03-28
  rus: 2000-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/5855/kaz/28.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5855/rus/28.03.2000
