act_code: '31241'
requisite: Решение маслихата Карабалыкского района Костанайской области от 21 декабря 2006 года № 277. Зарегистрировано Управлением юстиции Карабалыкского района Костанайской области 8 января 2007 года № 9-12-27. Утратило силу решением маслихата Карабалыкского района Костанайской области от 15 апреля 2009 года № 147
title:
  rus: Об утверждении размеров единых ставок фиксированного суммарного налога
  kaz: Тіркелген жиынтық салықтық бірыңғай ставкаларының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '162010000002'
version_date:
  kaz: 2006-12-21
  rus: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/31241/kaz/21.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31241/rus/21.12.2006
