act_code: '31080'
requisite: Решение маслихата города Рудного Костанайской области от 22 декабря 2006 года № 388. Зарегистрировано Управлением юстиции города Рудного Костанайской области 5 января 2007 года № 9-2-67. Срок действия решения - до 1 января 2008 года
title:
  rus: Об установлении ставки платы за размещение наружной (визуальной) рекламы на 2007 год
  kaz: Сыртқы (көрнекі) жарнаманы орналастырғаны үшін 2007 жылға арналған төлем ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-22
approved_by:
- '162021000002'
version_date:
  kaz: 2006-12-22
  rus: 2006-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/31080/kaz/22.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31080/rus/22.12.2006
