act_code: '227979'
requisite: Решение акима Белинского сельского округа района Беимбета Майлина Костанайской области от 20 июля 2026 года № 2ДСП
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу шараларын жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-20
approved_by:
- '162016003002'
version_date:
  kaz: 2026-07-20
  rus: 2026-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/227979/kaz/20.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227979/rus/20.07.2026
