act_code: '36708'
requisite: Решение маслихата Костанайской области от 12 декабря 2007 года № 30. Зарегистрировано департаментом юстиции Костанайской области 8 января 2008 года № 3584. Утратило силу в связи с истечением срока действия - письмо маслихата Костанайской области от 13 января 2011 года № 10
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам здравоохранения, социального обеспечения, образования, культуры и спорта, работающим в аульной (сельской) местности
  kaz: Ауылдық (селолық) жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт мамандарына жиырма бес процентке жоғары лауазымдық жалақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '162000000002'
version_date:
  kaz: 2007-12-12
  rus: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/36708/kaz/12.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36708/rus/12.12.2007
