act_code: '49643'
requisite: Қостанай облысы Жангелдин ауданы мәслихатының 2009 жылғы 23 желтоқсандағы № 147 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда № 9-9-111 тіркелді
title:
  rus: Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '162007000002'
version_date:
  kaz: 2010-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/49643/kaz/15.07.2010
caused_by:
  code: '53726'
  requisite: Қостанай облысы Жангелдин ауданы мәслихатының 2010 жылғы 15 шілдедегі № 186 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2010 жылғы 26 шілдеде № 9-9-123 тіркелді
  title:
    rus: '"Жангельдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" 2009 жылғы 23 желтоқсандағы № 147 мәслихат шешіміне өзгерістер енгізу туралы'
    kaz: '"Жангельдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" 2009 жылғы 23 желтоқсандағы № 147 мәслихат шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53726/rus
