act_code: '49643'
requisite: Қостанай облысы Жангелдин ауданы мәслихатының 2009 жылғы 23 желтоқсандағы № 147 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда № 9-9-111 тіркелді
title:
  rus: Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
  kaz: Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '162007000002'
version_date:
  kaz: 2010-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49643/kaz/22.10.2010
caused_by:
  code: '55190'
  requisite: Қостанай облысы Жангелдин ауданы мәслихатының 2010 жылғы 22 қазандағы № 196 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2010 жылғы 29 қазанда № 9-9-124 тіркелді
  title:
    rus: Мәслихаттың 2009 жылғы 23 желтоқсандағы № 147 "Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Мәслихаттың 2009 жылғы 23 желтоқсандағы № 147 "Жангелдин ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55190/rus
