act_code: '138434'
requisite: Решение маслихата Джангельдинского района Костанайской области от 13 января 2020 года № 277. Зарегистрировано Департаментом юстиции Костанайской области 15 января 2020 года № 8896
title:
  rus: О бюджетах сел, сельских округов Джангельдинского района на 2020 - 2022 годы
  kaz: Жангелдин ауданы ауылдарының, ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-13
approved_by:
- '162007000002'
version_date:
  kaz: 2020-09-04
  rus: 2020-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/138434/kaz/04.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138434/rus/04.09.2020
caused_by:
  code: '146064'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 4 сентября 2020 года № 321. Зарегистрировано Департаментом юстиции Костанайской области 7 сентября 2020 года № 9432
  title:
    rus: О внесении изменений в решение маслихата от 13 января 2020 года № 277 «О бюджетах сел, сельских округов Джангельдинского района на 2020 - 2022 годы»
    kaz: Мәслихаттың 2020 жылғы 13 қаңтардағы № 277 «Жангелдин ауданы ауылдарының, ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146064/rus
