act_code: '132459'
requisite: Решение акима Надеждинского сельского округа Костанайского района Костанайской области от 7 июня 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 10 июня 2019 года № 8516
title:
  rus: Об установлении акционерному обществу «Казахтелеком» публичного сервитута на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-07
approved_by:
- '162012011002'
version_date:
  kaz: 2019-06-07
  rus: 2019-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/132459/kaz/07.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132459/rus/07.06.2019
