act_code: '94410'
requisite: Решение акима города Аркалыка Костанайской области от 5 октября 2015 года № 10. Зарегистрировано Департаментом юстиции Костанайской области 14 октября 2015 года № 5930. Утратило силу решением акима города Аркалыка Костанайской области от 1 апреля 2020 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории города Аркалыка
  kaz: Арқалық қаласы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-05
approved_by:
- '162019000003'
version_date:
  kaz: 2015-10-05
  rus: 2015-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/94410/kaz/05.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94410/rus/05.10.2015
