act_code: '160257'
requisite: Решение маслихата Узункольского района Костанайской области от 1 ноября 2021 года № 70. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 ноября 2021 года № 25179
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Узункольском районе
  kaz: Ұзынкөл ауданында мүгедектігі бар балаларды қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-11-01
approved_by:
- '162017000002'
version_date:
  kaz: 2022-07-14
  rus: 2022-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/160257/kaz/14.07.2022
  rus: https://zan.gov.kz/client/#!/doc/160257/rus/14.07.2022
caused_by:
  code: '169870'
  requisite: Решение маслихата Узункольского района Костанайской области от 14 июля 2022 года № 161. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 июля 2022 года № 28815
  title:
    rus: О внесении изменения в решение Узункольского районного маслихата от 1 ноября 2021 года № 70 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Узункольском районе»
    kaz: Ұзынкөл аудандық мәслихаттың 2021 жылғы 1 қарашадағы № 70 «Ұзынкөл ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарын өндіріп алу мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169870/rus
