act_code: '43998'
requisite: Решение акима Сарыкольского района Костанайской области от 23 января 2009 года № 1. Зарегистрировано Управлением юстиции Сарыкольского района Костанайской области 2 февраля 2009 года № 9-17-74
title:
  rus: Об организации и обеспечении приписки граждан Республики Казахстан мужского пола, 1992 года рождения к призывному участку в 2009 году
  kaz: Қазақстан Республикасының 1992 жылы туған еркек жынысты азаматтарын 2009 жылы әскерге шақыру учаскесіне тіркеудi ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-23
approved_by:
- '162015000003'
version_date:
  kaz: 2009-01-23
  rus: 2009-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/43998/kaz/23.01.2009
  rus: https://zan.gov.kz/client/#!/doc/43998/rus/23.01.2009
