act_code: '65937'
requisite: Решение акима Костанайской области от 7 июня 2012 года № 9. Зарегистрировано Департаментом юстиции Костанайской области 8 июня 2012 года № 3812. Утратило силу - Решением акима Костанайской области от 3 декабря 2013 года № 6
title:
  rus: Об утверждении форм документов по субсидированию повышения продуктивности и качества продукции животноводства
  kaz: Мал шаруашылығы өнімдерінің өнімділігін және сапасын арттыруды субсидиялау жөніндегі құжаттардың нысандарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-07
approved_by:
- '162000000003'
version_date:
  kaz: 2012-06-07
  rus: 2012-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/65937/kaz/07.06.2012
  rus: https://zan.gov.kz/client/#!/doc/65937/rus/07.06.2012
