act_code: '8677'
requisite: Решение акима Костанайской области от 27 февраля 2001 года № 48. Зарегистрировано Управлением юстиции Костанайской области 27 марта 2001 года № 683.  Утратило силу решением акима Костанайской области от 7 января 2003 года № 1
title:
  rus: Об утверждении дополнительного перечня видов заболеваний, препаратов и увеличении норм отпуска лекарственных средств отдельным категориям населения
  kaz: Препараттардың, ауру түрлерінің қосымша тізбесін бекіту және халықтың жекелеген санаттарына дәрі-дәрмектер босату нормаларын ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-02-27
approved_by:
- '162000000003'
version_date:
  kaz: 2001-02-27
  rus: 2001-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/8677/kaz/27.02.2001
  rus: https://zan.gov.kz/client/#!/doc/8677/rus/27.02.2001
