act_code: '205945'
requisite: Решение маслихата Наурзумского района Костанайской области от 5 января 2025 года № 172
title:
  rus: О бюджете Карамендинского сельского округа Наурзумского района на 2025-2027 годы
  kaz: Науырзым ауданы Қарамеңді ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '162014000002'
version_date:
  kaz: 2025-01-05
  rus: 2025-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/205945/kaz/05.01.2025
  rus: https://zan.gov.kz/client/#!/doc/205945/rus/05.01.2025
