act_code: '80064'
requisite: Решение маслихата города Аркалыка Костанайской области от 9 апреля 2014 года № 166. Зарегистрировано Департаментом юстиции Костанайской области 14 мая 2014 года № 4703. Утратило силу решением маслихата города Аркалыка Костанайской области от 19 мая 2017 года № 110
title:
  rus: Об утверждении Регламента Аркалыкского городского маслихата
  kaz: Арқалық қалалық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-04-09
approved_by:
- '162019000002'
version_date:
  kaz: 2015-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/80064/kaz/28.05.2015
caused_by:
  code: '90620'
  requisite: Решение маслихата города Аркалыка Костанайской области от 28 мая 2015 года № 248. Зарегистрировано Департаментом юстиции Костанайской области 17 июня 2015 года № 5667. Утратило силу решением маслихата города Аркалыка Костанайской области от 19 мая 2017 года № 110
  title:
    rus: О внесении изменения в решение маслихата от 9 апреля 2014 года № 166 "Об утверждении Регламента Аркалыкского городского маслихата"
    kaz: Мәслихаттың 2014 жылғы 9 сәуірдегі № 166 "Арқалық қалалық мәслихатының Регламентін бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90620/rus
