act_code: '49623'
requisite: Решение маслихата Житикаринского района Костанайской области от 25 декабря 2009 года № 226. Зарегистрировано Управлением юстиции Житикаринского района Костанайской области 29 декабря 2009 года № 9-10-130
title:
  rus: О бюджете Житикаринского района на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған Жітіқара ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '162008000002'
version_date:
  kaz: 2010-07-12
  rus: 2010-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49623/kaz/12.07.2010
  rus: https://zan.gov.kz/client/#!/doc/49623/rus/12.07.2010
caused_by:
  code: '53591'
  requisite: Решение маслихата Житикаринского района Костанайской области от 12 июля 2010 года № 258. Зарегистрировано Управлением юстиции Житикаринского района Костанайской области 17 июля 2010 года № 9-10-145
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2009 года № 226 "О бюджете Житикаринского района на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған Жітіқара ауданының бюджеті туралы" 2009 жылғы 25 желтоқсандағы № 226 мәслихат шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53591/rus
