act_code: '53829'
requisite: Решение маслихата Аулиекольского района Костанайской области от 7 июля 2010 года № 189. Зарегистрировано Управлением юстиции Аулиекольского района Костанайской области 3 августа 2010 года № 9-7-121. Утратило силу решением маслихата Аулиекольского района Костанайской области от 14 февраля 2018 года № 175
title:
  rus: Об установлении единых ставок фиксированного налога для налогоплательщиков, осуществляющих деятельность на территории Аулиекольского района
  kaz: Қызметін Әулиекөл ауданының аумағында жүзеге асыратын салық төлеушілер үшін бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-07
approved_by:
- '162005000002'
version_date:
  kaz: 2010-07-07
  rus: 2010-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/53829/kaz/07.07.2010
  rus: https://zan.gov.kz/client/#!/doc/53829/rus/07.07.2010
