act_code: '128050'
requisite: Решение маслихата Костанайского района Костанайской области от 29 декабря 2018 года № 344. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2018 года № 8233
title:
  rus: О бюджетах поселка, сельских округов Костанайского района на 2019-2021 годы
  kaz: Қостанай ауданының кент, ауылдық округтерінің 2019-2021 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '162012000002'
version_date:
  kaz: 2019-06-07
  rus: 2019-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/128050/kaz/07.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128050/rus/07.06.2019
caused_by:
  code: '132597'
  requisite: Решение маслихата Костанайского района Костанайской области от 7 июня 2019 года № 410. Зарегистрировано Департаментом юстиции Костанайской области 17 июня 2019 года № 8532
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2018 года № 344 «О бюджетах села, поселка, сельских округов Костанайского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 29 желтоқсандағы № 344 «Қостанай ауданының ауыл, кент, ауылдық округтерінің 2019-2021 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132597/rus
