act_code: '185625'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 1 сентября 2023 года № 35
title:
  rus: Об отмене некоторых решений маслихата района Беимбета Майлина
  kaz: Бейімбет Майлин аудан мәслихатының кейбір шешімдерін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-01
approved_by:
- '162016000002'
version_date:
  kaz: 2023-09-01
  rus: 2023-09-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/185625/kaz/01.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185625/rus/01.09.2023
