act_code: '43368'
requisite: Решение маслихата города Рудного Костанайской области от 23 декабря 2008 года № 151. Зарегистрировано Управлением юстиции города Рудного Костанайской области 9 января 2009 года № 9-2-118
title:
  rus: О городском бюджете города Рудного
  kaz: Рудный қаласының 2009 жылға арналған қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '162021000002'
version_date:
  kaz: 2009-08-03
  rus: 2009-08-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/43368/kaz/03.08.2009
  rus: https://zan.gov.kz/client/#!/doc/43368/rus/03.08.2009
caused_by:
  code: '47342'
  requisite: Решение маслихата города Рудного Костанайской области от 3 августа 2009 года № 238. Зарегистрировано управлением юстиции города Рудного Костанайской области 12 августа 2009 года № 9-2-141
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 23 декабря 2008 года № 151 "О городском бюджете города Рудного на 2009 год"
    kaz: Мәслихаттың 2008 жылғы 23 желтоқсандағы № 151 "Рудный қаласының 2009 жылға арналған қалалық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47342/rus
