act_code: '178646'
requisite: Решение маслихата Костанайской области от 2 февраля 2018 года № 232
title:
  rus: Об утверждении Регламента Костанайского областного маслихата
  kaz: Қостанай облыстық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-02-02
approved_by:
- '162000000002'
version_date:
  kaz: 2018-02-02
  rus: 2018-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/178646/kaz/02.02.2018
  rus: https://zan.gov.kz/client/#!/doc/178646/rus/02.02.2018
