act_code: '104659'
requisite: Решение маслихата Костанайской области от 27 июня 2016 года № 38 и постановление акимата Костанайской области от 27 июня 2016 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 19 июля 2016 года № 6547
title:
  rus: Об изменениях в административно-территориальном устройстве Костанайской области
  kaz: Қостанай облысының әкімшілік-аумақтық құрылысындағы өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-27
approved_by:
- '162000000002'
version_date:
  kaz: 2016-06-27
  rus: 2016-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/104659/kaz/27.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104659/rus/27.06.2016
