act_code: '71919'
requisite: Решение маслихата города Лисаковска Костанайской области от 15 марта 2013 года № 102. Зарегистрировано Департаментом юстиции Костанайской области 3 апреля 2013 года № 4083. Утратило силу решением маслихата города Лисаковска Костанайской области от 2 сентября 2013 года № 145
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-15
approved_by:
- '162020000002'
version_date:
  kaz: 2013-04-23
  rus: 2013-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/71919/kaz/23.04.2013
  rus: https://zan.gov.kz/client/#!/doc/71919/rus/23.04.2013
caused_by:
  code: '72240'
  requisite: Решение маслихата города Лисаковска Костанайской области от 23 апреля 2013 года № 107. Зарегистрировано Департаментом юстиции Костанайской области 25 апреля 2013 года № 4109. Утратило силу решением маслихата города Лисаковска Костанайской области от 2 сентября 2013 года № 145
  title:
    rus: О внесении изменений в решение маслихата от 15 марта 2013 года № 102 «Об оказании социальной помощи отдельным категориям нуждающихся граждан»
    kaz: Мәслихаттың 2013 жылғы 15 наурыздағы № 102 "Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72240/rus
