act_code: '187242'
requisite: Решение маслихата Карасуского района Костанайской области от 12 октября 2023 года № 63
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села для участия в сходе местного сообщества села Жалгыскан Карасуского района Костанайской области
  kaz: Қостанай облысы Қарасу ауданы Жалғысқан ауылы жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-12
approved_by:
- '162011000002'
version_date:
  kaz: 2023-10-12
  rus: 2023-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/187242/kaz/12.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187242/rus/12.10.2023
