act_code: '36734'
requisite: Решение маслихата города Лисаковска Костанайской области от 24 декабря 2007 года № 41. Зарегистрировано Управлением юстиции Костанайской области 8 января 2008 года № 9-4-101. Срок действия решения - до 1 января 2009 года
title:
  rus: Об утверждении Правил оказания жилищной помощи на 2008 год в городе Лисаковске
  kaz: Лисаков қаласындағы 2008 жылға арналған тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-12-24
approved_by:
- '162020000002'
version_date:
  kaz: 2007-12-24
  rus: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36734/kaz/24.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36734/rus/24.12.2007
