act_code: '206284'
requisite: Решение маслихата Костанайского района Костанайской области от 27 декабря 2024 года № 243
title:
  rus: О бюджетах города Тобыл, сельских округов Костанайского района на 2025-2027 годы
  kaz: Қостанай ауданы Тобыл қаласының, ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '162012000002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/206284/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206284/rus/09.07.2025
caused_by:
  code: '212452'
  requisite: Решение маслихата Костанайского района Костанайской области от 9 июля 2025 года № 291
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2024 года № 243 «О бюджетах города Тобыл, сельских округов Костанайского района на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 27 желтоқсандағы № 243 «Қостанай ауданы Тобыл қаласының, ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212452/rus
