act_code: '38239'
requisite: Решение маслихата Карасуского района Костанайской области от 4 февраля 2008 года № 39. Зарегистрировано Управлением юстиции Карасуского района Костанайской области 11 марта 2008 года № 9-13-61. Утратило силу решением маслихата Карасуского района Костанайской области от 30 января 2009 года № 123
title:
  rus: Об изменениях базовых ставок земельного налога
  kaz: Жер салығы базалық ставкаларының өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-04
approved_by:
- '162011000002'
version_date:
  kaz: 2008-02-04
  rus: 2008-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/38239/kaz/04.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38239/rus/04.02.2008
