act_code: '172202'
requisite: Решение акима Родинского сельского округа города Аркалыка Костанайской области от 22 сентября 2022 года № 6. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 сентября 2022 года № 29881
title:
  rus: О переименовании улицы в селе Родина Родинского сельского округа города Аркалыка
  kaz: Арқалық қаласының Родина ауылдық округінің Родина ауылындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-22
approved_by:
- '162019003001'
version_date:
  kaz: 2022-09-22
  rus: 2022-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/172202/kaz/22.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172202/rus/22.09.2022
