act_code: '78672'
requisite: Решение маслихата Федоровского района Костанайской области от 27 февраля 2014 года № 210. Зарегистрировано Департаментом юстиции Костанайской области 8 апреля 2014 года № 4562. Утратило силу решением маслихата Федоровского района Костанайской области от 22 декабря 2016 года № 82
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Новошумного сельского округа Федоровского района Костанайской области
  kaz: Қостанай облысы Федоров ауданы Новошумный ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын  бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-27
approved_by:
- '162018000002'
version_date:
  kaz: 2014-02-27
  rus: 2014-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/78672/kaz/27.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78672/rus/27.02.2014
