act_code: '131618'
requisite: Решение акима Смирновского сельского округа Карабалыкского района Костанайской области от 15 мая 2019 года № 1-р. Зарегистрировано Департаментом юстиции Костанайской области 16 мая 2019 года № 8448
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «SilkNetCom»
  kaz: «SilkNetCom» жауапкершілігі шектеулі серіктестігіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-15
approved_by:
- '162010011002'
version_date:
  kaz: 2019-05-15
  rus: 2019-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/131618/kaz/15.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131618/rus/15.05.2019
