act_code: '55251'
requisite: Решение маслихата Федоровского района Костанайской области от 22 октября 2010 года № 380. Зарегистрировано Управлением юстиции Федоровского района Костанайской области 3 ноября 2010 года № 9-20-183. Утратило силу решением маслихата Федоровского района Костанайской области от 27 ноября 2014 года № 279
title:
  rus: О правилах оказания жилищной помощи
  kaz: Тұрғын үй көмегін көрсету ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-22
approved_by:
- '162018000002'
version_date:
  kaz: 2010-10-22
  rus: 2010-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/55251/kaz/22.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55251/rus/22.10.2010
