act_code: '139103'
requisite: Решение маслихата Сарыкольского района Костанайской области от 27 января 2020 года № 317. Зарегистрировано Департаментом юстиции Костанайской области 28 января 2020 года № 8923
title:
  rus: О бюджетах поселка, сел и сельских округов Сарыкольского района Костанайской области на 2020-2022 годы
  kaz: Қостанай облысы Сарыкөл ауданы кентінің, ауылдары мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-27
approved_by:
- '162015000002'
version_date:
  kaz: 2020-11-30
  rus: 2020-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/139103/kaz/30.11.2020
  rus: https://zan.gov.kz/client/#!/doc/139103/rus/30.11.2020
caused_by:
  code: '149285'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 30 ноября 2020 года № 379. Зарегистрировано Департаментом юстиции Костанайской области 4 декабря 2020 года № 9607
  title:
    rus: О внесении изменений в решение маслихата от 27 января 2020 года № 317 «О бюджетах поселка, сел и сельских округов Сарыкольского района Костанайской области на 2020-2022 годы»
    kaz: Мәслихаттың 2020 жылғы 27 қаңтардағы № 317 «Қостанай облысы Сарыкөл ауданы кентінің, ауылдары мен ауылдық округтерінің 2020-2022 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149285/rus
