act_code: '124560'
requisite: Решение акима Глазуновского сельского округа Костанайского района Костанайской области от 24 августа 2018 года № 6. Зарегистрировано Департаментом юстиции Костанайской области 12 сентября 2018 года № 8038
title:
  rus: О переименовании составных частей села Айсары Айсаринского сельского округа Костанайского района
  kaz: Қостанай ауданы Айсары ауылдық округінің Айсары ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-24
approved_by:
- '162012004002'
version_date:
  kaz: 2019-12-19
  rus: 2019-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/124560/kaz/19.12.2019
  rus: https://zan.gov.kz/client/#!/doc/124560/rus/19.12.2019
caused_by:
  code: '137261'
  requisite: Решение акима Айсаринского сельского округа Костанайского района Костанайской области от 19 декабря 2019 года № 7. Зарегистрировано Департаментом юстиции Костанайской области 23 декабря 2019 года № 8832
  title:
    rus: О внесении изменений в решение акима от 24 августа 2018 года № 6 «О переименовании составных частей села Глазуновка Глазуновского сельского округа Костанайского района»
    kaz: Әкімнің 2018 жылғы 24 тамыздағы № 6 «Қостанай ауданы Глазунов ауылдық округінің Глазунов ауылының құрамдас бөліктерін қайта атау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137261/rus
