act_code: '177203'
requisite: Решение маслихата Сарыкольского района Костанайской области от 30 декабря 2022 года № 256
title:
  rus: О бюджете Комсомольского сельского округа Сарыкольского района Костанайской области на 2023-2025 годы
  kaz: Қостанай облысы Сарыкөл ауданы Комсомол ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '162015000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/177203/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177203/rus/13.12.2023
caused_by:
  code: '190160'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 13 декабря 2023 года № 106
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2022 года № 256 «О бюджете Комсомольского сельского округа Сарыкольского района Костанайской области на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 30 желтоқсандағы № 256 «Қостанай облысы Сарыкөл ауданы Комсомол ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190160/rus
