act_code: '1312'
requisite: Решение акима Костанайской области от 9 сентября 1998 года № 17. Зарегистрировано Управлением юстиции Костанайской области 16 сентября 1998 года № 27. Утратило силу решением акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: Об утверждении комплексной программы профилактики правонарушений среди несовершеннолетних в Костанайской области на 1998-2000 годы
  kaz: Қостанай  облысындағы кәмелетке жасы толмағандар арасыңда құқық бұзушылықтың  алдын алудың 1998-2000 жылдарға арналған кешенді бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 1998-09-08
approved_by:
- '162000000003'
version_date:
  kaz: 1998-09-08
  rus: 1998-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/1312/kaz/08.09.1998
  rus: https://zan.gov.kz/client/#!/doc/1312/rus/08.09.1998
