act_code: '158626'
requisite: Решение маслихата города Рудного Костанайской области от 10 сентября 2021 года № 65. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 сентября 2021 года № 24362
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-09-10
approved_by:
- '162021000002'
version_date:
  kaz: 2021-09-10
  rus: 2021-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/158626/kaz/10.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158626/rus/10.09.2021
