act_code: '158626'
requisite: Решение маслихата города Рудного Костанайской области от 10 сентября 2021 года № 65. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 сентября 2021 года № 24362
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-09-10
approved_by:
- '162021000002'
version_date:
  kaz: 2022-09-23
  rus: 2022-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/158626/kaz/23.09.2022
  rus: https://zan.gov.kz/client/#!/doc/158626/rus/23.09.2022
caused_by:
  code: '172053'
  requisite: Решение маслихата города Рудного Костанайской области от 23 сентября 2022 года № 149. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 сентября 2022 года № 29807
  title:
    rus: О внесении изменений в решение маслихата от 10 сентября 2021 года № 65 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану»
    kaz: Мәслихаттың 2021 жылғы 10 қыркүйектегі № 65 «Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172053/rus
