act_code: '130453'
requisite: Решение маслихата Костанайского района Костанайской области от 9 апреля 2019 года № 379. Зарегистрировано Департаментом юстиции Костанайской области 12 апреля 2019 года № 8346. Утратило силу решением маслихата Костанайского района Костанайской области от 13 апреля 2020 года № 512 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта, ветеринарии, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-09
approved_by:
- '162012000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/130453/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130453/rus/09.04.2019
