act_code: '205859'
requisite: Решение маслихата Федоровского района Костанайской области от 26 декабря 2024 года № 154
title:
  rus: О районном бюджете Федоровского района на 2025-2027 годы
  kaz: Федоров ауданының 2025-2027 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '162018000002'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/205859/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205859/rus/05.12.2025
caused_by:
  code: '218560'
  requisite: Решение маслихата Федоровского района Костанайской области от 5 декабря 2025 года № 216
  title:
    rus: О внесении изменений в решение маслихата от 26 декабря 2024 года № 154 «О районном бюджете Федоровского района на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 26 желтоқсандағы № 154 «Федоров ауданының 2025-2027 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218560/rus
