act_code: '44755'
requisite: Решение маслихата города Костаная Костанайской области от 2 февраля 2009 года № 162. Зарегистрировано Управлением юстиции города Костаная Костанайской области 12 марта 2009 года № 9-1-122. Утратило силу решением маслихата города Костаная Костанайской области от 28 марта 2018 года № 233
title:
  rus: Об утверждении размеров ставок фиксированного налога на единицу налогообложения, расположенную в городе Костанае
  kaz: Қостанай қаласында орналасқан салық салу объектісі бірлігінен тіркелген салық мөлшерлемелерінің мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-02
approved_by:
- '162002000002'
version_date:
  kaz: 2015-08-13
  rus: 2015-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44755/kaz/13.08.2015
  rus: https://zan.gov.kz/client/#!/doc/44755/rus/13.08.2015
caused_by:
  code: '93703'
  requisite: Решение маслихата города Костаная Костанайской области от 13 августа 2015 года № 347. Зарегистрировано Департаментом юстиции Костанайской области 16 сентября 2015 года № 5877. Утратило силу решением маслихата города Костаная Костанайской области от 28 марта 2018 года № 233
  title:
    rus: О внесении изменений в решение маслихата от 2 февраля  2009 года №162 "Об утверждении размеров ставок фиксированного налога на единицу налогообложения, расположенную в городе Костанае"
    kaz: Мәслихаттың 2009 жылғы 2 ақпандағы №162 «Қостанай қаласында орналасқан салық салу объектісі бірлігінен тіркелген салық ставкаларының мөлшерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93703/rus
