act_code: '44755'
requisite: Решение маслихата города Костаная Костанайской области от 2 февраля 2009 года № 162. Зарегистрировано Управлением юстиции города Костаная Костанайской области 12 марта 2009 года № 9-1-122. Утратило силу решением маслихата города Костаная Костанайской области от 28 марта 2018 года № 233
title:
  rus: Об утверждении размеров ставок фиксированного налога на единицу налогообложения, расположенную в городе Костанае
  kaz: Қостанай қаласында орналасқан салық салу объектісі бірлігінен тіркелген салық мөлшерлемелерінің мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-02
approved_by:
- '162002000002'
version_date:
  kaz: 2009-02-02
  rus: 2009-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/44755/kaz/02.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44755/rus/02.02.2009
