act_code: '199391'
requisite: Решение акима Свердловского сельского округа Денисовского района Костанайской области от 2 августа 2024 года № 9. Утратило силу решением акима Свердловского сельского округа Денисовского района Костанайской области от 27 августа 2024 года № 11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-02
approved_by:
- '162006011002'
version_date:
  kaz: 2024-08-02
  rus: 2024-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/199391/kaz/02.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199391/rus/02.08.2024
