act_code: '56590'
requisite: Қостанай облысы Жангелдин ауданы мәслихатының 2010 жылғы 22 желтоқсандағы № 199 шешімі. Қостанай облысы Жангелдин ауданының Әділет басқармасында 2010 жылғы 30 желтоқсанда № 9-9-126 тіркелді
title:
  rus: Жангелдин ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Жангелдин ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '162007000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56590/kaz/22.12.2010
