act_code: '102235'
requisite: Решение маслихата города Аркалыка Костанайской области от 1 апреля 2016 года № 13. Зарегистрировано Департаментом юстиции Костанайской области 6 мая 2016 года № 6328. Утратило силу решением маслихата города Аркалыка Костанайской области от 23 февраля 2017 года № 89
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "Аппарат Аркалыкского городского маслихата"
  kaz: '"Арқалық қалалық мәслихатының аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-04-01
approved_by:
- '162019000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/102235/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102235/rus/01.04.2016
