act_code: '155872'
requisite: Решение акима Аулиекольского района Костанайской области от 13 мая 2021 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 14 мая 2021 года № 9914
title:
  rus: Об образовании избирательных участков на территории Аулиекольского района
  kaz: Әулиекөл ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-05-13
approved_by:
- '162005000003'
version_date:
  kaz: 2024-09-10
  rus: 2024-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/155872/kaz/10.09.2024
  rus: https://zan.gov.kz/client/#!/doc/155872/rus/10.09.2024
caused_by:
  code: '200592'
  requisite: Решение акима Аулиекольского района Костанайской области от 10 сентября 2024 года № 1. Зарегистрировано в Департаменте юстиции Костанайской области 12 сентября 2024 года № 10265-10
  title:
    rus: О внесении изменений в решение акима Аулиекольского района от 13 мая 2021 года № 3 «Об образовании избирательных участков на территории Аулиекольского района»
    kaz: Әулиекөл ауданы әкімінің 2021 жылғы 13 мамырдағы № 3 «Әулиекөл ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200592/rus
