act_code: '105927'
requisite: Решение маслихата Джангельдинского района Костанайской области от 12 августа 2016 года № 45. Зарегистрировано Департаментом юстиции Костанайской области 5 сентября 2016 года № 6609. Утратило силу решением маслихата Джангельдинского района Костанайской области от 28 октября 2020 года № 327 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-08-12
approved_by:
- '162007000002'
version_date:
  kaz: 2019-03-19
  rus: 2019-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/105927/kaz/19.03.2019
  rus: https://zan.gov.kz/client/#!/doc/105927/rus/19.03.2019
caused_by:
  code: '129774'
  requisite: Решение маслихата Джангельдинского района Костанайской области от 19 марта 2019 года № 223. Зарегистрировано Департаментом юстиции Костанайской области 26 марта 2019 года № 8310. Утратило силу решением маслихата Джангельдинского района Костанайской области от 28 октября 2020 года № 327 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение маслихата от 12 августа 2016 года № 45 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: Мәслихаттың 2016 жылғы 12 тамыздағы № 45 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129774/rus
