act_code: '119671'
requisite: Решение акима Бурлинского сельского округа Карабалыкского района Костанайской области от 23 февраля 2018 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 16 марта 2018 года № 7602
title:
  rus: О переименовании составных частей села Бурли Бурлинского сельского округа Карабалыкского района
  kaz: Қарабалық ауданы Бөрлі ауылдық округі Бөрлі ауылының құрамдас бөліктерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-23
approved_by:
- '162010003002'
version_date:
  kaz: 2018-02-23
  rus: 2018-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/119671/kaz/23.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119671/rus/23.02.2018
