act_code: '93208'
requisite: Решение маслихата Костанайской области от 31 июля 2015 года № 422. Зарегистрировано Департаментом юстиции Костанайской области 28 августа 2015 года № 5850. Утратило силу решением маслихата Костанайской области от 17 февраля 2016 года № 502
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования и культуры, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшi болып табылатын және ауылдық жерде жұмыс iстейтiн денсаулық сақтау, әлеуметтiк қамсыздандыру, бiлiм беру және мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтiк ставкаларды белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-31
approved_by:
- '162000000002'
version_date:
  kaz: 2015-07-31
  rus: 2015-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/93208/kaz/31.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93208/rus/31.07.2015
