act_code: '193930'
requisite: Решение маслихата Алтынсаринского района Костанайской области от 29 февраля 2024 года № 66. Зарегистрировано в Департаменте юстиции Костанайской области 4 марта 2024 года № 10155-10
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Убаганское и населенных пунктов Алтынсаринского района
  kaz: Обаған ауылы және Алтынсарин ауданының елді мекендерінің жерлерін аймақтарға бөлу жобасың (схемасын), бағалау аймактарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2024-02-29
approved_by:
- '162003000002'
version_date:
  kaz: 2024-02-29
  rus: 2024-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/193930/kaz/29.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193930/rus/29.02.2024
