act_code: '127823'
requisite: Решение маслихата Узункольского района Костанайской области от 27 декабря 2018 года № 251. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2018 года № 8224
title:
  rus: О бюджете Узункольского сельского округа Узункольского района на 2019-2021 годы
  kaz: Ұзынкөл ауданының Ұзынкөл ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '162017000002'
version_date:
  kaz: 2019-11-15
  rus: 2019-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/127823/kaz/15.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127823/rus/15.11.2019
caused_by:
  code: '136102'
  requisite: Решение маслихата Узункольского района Костанайской области от 15 ноября 2019 года № 319. Зарегистрировано Департаментом юстиции Костанайской области 19 ноября 2019 года № 8757
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2018 года № 251 «О бюджете Узункольского сельского округа Узункольского района на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 27 желтоқсандағы № 251 «Ұзынкөл ауданының Ұзынкөл ауылдық округінің 2019-2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136102/rus
