act_code: '122085'
requisite: Решение маслихата Карабалыкского района Костанайской области от 17 мая 2018 года № 257. Зарегистрировано Департаментом юстиции Костанайской области 25 мая 2018 года № 7790. Утратило силу решением маслихата Карабалыкского района Костанайской области от 17 января 2020 года № 471 (вводится в действие для поселка, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Кустанайского сельского округа Карабалыкского района Костанайской области
  kaz: Қостанай облысы Қарабалық ауданы Қостанай ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-05-17
approved_by:
- '162010000002'
version_date:
  kaz: 2019-11-18
  rus: 2019-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/122085/kaz/18.11.2019
  rus: https://zan.gov.kz/client/#!/doc/122085/rus/18.11.2019
caused_by:
  code: '136406'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 18 ноября 2019 года № 442. Зарегистрировано Департаментом юстиции Костанайской области 27 ноября 2019 года № 8787. Утратило силу решением маслихата Карабалыкского района Костанайской области от 17 января 2020 года № 471 (вводится в действие для поселка, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 17 мая 2018 года № 257 «Об утверждении Регламента собрания местного сообщества Кустанайского сельского округа Карабалыкского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 17 мамырдағы № 257 «Қостанай облысы Қарабалық ауданы Қостанай ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136406/rus
