act_code: '228037'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 23 июля 2026 года № 259
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по району Беимбета Майлина
  kaz: Бейімбет Майлин ауданы бойынша шетелдіктер үшін 2026 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-23
approved_by:
- '162016000002'
version_date:
  kaz: 2026-07-23
  rus: 2026-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/228037/kaz/23.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228037/rus/23.07.2026
