act_code: '180224'
requisite: Решение маслихата города Аркалыка Костанайской области от 21 апреля 2023 года № 16
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат Аркалыкского городского маслихата»
  kaz: «Арқалық қалалық мәслихатының аппараты» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-04-21
approved_by:
- '162019000002'
version_date:
  kaz: 2023-04-21
  rus: 2023-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/180224/kaz/21.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180224/rus/21.04.2023
