act_code: '127693'
requisite: Решение маслихата города Рудного Костанайской области от 28 декабря 2018 года № 322. Зарегистрировано Департаментом юстиции Костанайской области 28 декабря 2018 года № 8223
title:
  rus: О бюджете посёлка Качар на 2019-2021 годы
  kaz: Қашар кентінің 2019-2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '162021000002'
version_date:
  kaz: 2019-04-09
  rus: 2019-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/127693/kaz/09.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127693/rus/09.04.2019
caused_by:
  code: '130651'
  requisite: Решение маслихата города Рудного Костанайской области от 9 апреля 2019 года № 360. Зарегистрировано Департаментом юстиции Костанайской области 12 апреля 2019 года № 8343
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2018 года № 322 «О бюджете поселка Качар на 2019-2021 годы»
    kaz: Мәслихаттың 2018 жылғы 28 желтоқсандағы № 322 «Қашар кентінің 2019 – 2021 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130651/rus
