act_code: '5114'
requisite: Решение Акима Костанайской области от 6 апреля 1999 года № 95. Зарегистрировано Управлением юстиции Костанайской области 24 июня 1999 года за № 85. Утратило силу - решением Акима Костанайской области от 9 декабря 2004 года № 53
title:
  rus: О проведении санитарной очистки, благоустройства и озеленения городов и сел области
  kaz: Облыстың қалалары мен селоларында санитарлық тазарту, көркейту және көгалдандыру жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-05
approved_by:
- '162000000003'
version_date:
  kaz: 1999-04-05
  rus: 1999-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/5114/kaz/05.04.1999
  rus: https://zan.gov.kz/client/#!/doc/5114/rus/05.04.1999
