act_code: '131071'
requisite: Решение маслихата Камыстинского района Костанайской области от 24 апреля 2019 года № 247. Зарегистрировано Департаментом юстиции Костанайской области 2 мая 2019 года № 8384
title:
  rus: О повышении ставок единого земельного налога
  kaz: Бірыңғай жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-24
approved_by:
- '162009000002'
version_date:
  kaz: 2019-04-24
  rus: 2019-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/131071/kaz/24.04.2019
  rus: https://zan.gov.kz/client/#!/doc/131071/rus/24.04.2019
