act_code: '177814'
requisite: Решение маслихата Денисовского района Костанайской области от 29 декабря 2022 года № 115
title:
  rus: О бюджетах сел и сельских округов Денисовского района на 2023-2025 годы
  kaz: Денисов ауданы ауылдарының және ауылдық округтерінің 2023 - 2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162006000002'
version_date:
  kaz: 2023-09-05
  rus: 2023-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/177814/kaz/05.09.2023
  rus: https://zan.gov.kz/client/#!/doc/177814/rus/05.09.2023
caused_by:
  code: '185922'
  requisite: Решение маслихата Денисовского района Костанайской области от 5 сентября 2023 года № 57
  title:
    rus: О внесении изменений в решение Денисовского районного маслихата Костанайской области от 29 декабря 2022 года № 115 «О бюджетах сел и сельских округов Денисовского района на 2023-2025 годы»
    kaz: Қостанай облысы Денисов аудандық мәслихатының 2022 жылғы 29 желтоқсандағы № 115 «Денисов ауданы ауылдарының және ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185922/rus
