act_code: '85654'
requisite: Решение маслихата Узункольского района Костанайской области от 24 декабря 2014 года № 251. Зарегистрировано Департаментом юстиции Костанайской области 31 декабря 2014 года № 5271
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162017000002'
version_date:
  kaz: 2015-10-21
  rus: 2015-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/85654/kaz/21.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85654/rus/21.10.2015
caused_by:
  code: '94690'
  requisite: Решение маслихата Узункольского района Костанайской области от 21 октября 2015 года № 359. Зарегистрировано Департаментом юстиции Костанайской области 23 октября 2015 года № 5957
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2014 года № 251 "О районном бюджете на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 251 "2015-2017 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94690/rus
