act_code: '153524'
requisite: Решение акима Дамдинского сельского округа Наурзумского района Костанайской области от 12 марта 2021 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 17 марта 2021 года № 9819
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-12
approved_by:
- '162014003002'
version_date:
  kaz: 2021-03-12
  rus: 2021-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/153524/kaz/12.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153524/rus/12.03.2021
