act_code: '132160'
requisite: Решение маслихата Карасуского района Костанайской области от 31 мая 2019 года № 328. Зарегистрировано Департаментом юстиции Костанайской области 6 июня 2019 года № 8505. Утратило силу решением маслихата Карасуского района Костанайской области от 29 апреля 2022 года № 120 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Койбагарского сельского округа Карасуского района Костанайской области
  kaz: Қостанай облысы Қарасу ауданы Қойбағар ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-05-31
approved_by:
- '162011000002'
version_date:
  kaz: 2019-05-31
  rus: 2019-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/132160/kaz/31.05.2019
  rus: https://zan.gov.kz/client/#!/doc/132160/rus/31.05.2019
