act_code: '142916'
requisite: Решение акима Диевского сельского округа Аулиекольского района Костанайской области от 15 мая 2020 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 18 мая 2020 года № 9195
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-15
approved_by:
- '162005002002'
version_date:
  kaz: 2020-05-15
  rus: 2020-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/142916/kaz/15.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142916/rus/15.05.2020
