act_code: '191287'
requisite: Решение маслихата Костанайского района Костанайской области от 27 декабря 2023 года № 126
title:
  rus: О бюджетах города Тобыл, сельских округов Костанайского района на 2024-2026 годы
  kaz: Қостанай ауданы Тобыл қаласының, ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '162012000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/191287/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/191287/rus/22.02.2024
caused_by:
  code: '193785'
  requisite: Решение маслихата Костанайского района Костанайской области от 22 февраля 2024 года № 141
  title:
    rus: О внесении изменений в решение маслихата от 27 декабря 2023 года № 126 «О бюджетах города Тобыл, сельских округов Костанайского района на 2024-2026 годы»
    kaz: Мәслихаттың 2023 жылғы 27 желтоқсандағы № 126 «Қостанай ауданы Тобыл қаласының, ауылдық округтерінің 2024-2026 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193785/rus
