act_code: '42878'
requisite: Решение акима Камышинского сельского округа Федоровского района Костанайской области от 12 ноября 2008 года № 28. Зарегистрировано Управлением юстиции Федоровского района Костанайской области 18 декабря 2008 года № 9-20-122
title:
  rus: О наименовании составных частей села Алабутала Камышинского сельского округа
  kaz: Камышин ауылдық округінің Алабутала ауылының құрамдас бөлігін атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-12
approved_by:
- '162018005002'
version_date:
  kaz: 2008-11-12
  rus: 2008-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/42878/kaz/12.11.2008
  rus: https://zan.gov.kz/client/#!/doc/42878/rus/12.11.2008
