act_code: '150846'
requisite: Решение маслихата Карасуского района Костанайской области от 28 декабря 2020 года № 454. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2020 года № 9671
title:
  rus: О районном бюджете Карасуского района на 2021-2023 годы
  kaz: Қарасу ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '162011000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/150846/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150846/rus/24.12.2021
caused_by:
  code: '162257'
  requisite: Решение маслихата Карасуского района Костанайской области от 24 декабря 2021 года № 82. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26097
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2020 года № 454 «О районном бюджете Карасуского района на 2021-2023 годы»
    kaz: Мәслихаттың 2020 жылғы 28 желтоқсандағы № 454 «Қарасу ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162257/rus
