act_code: '56589'
requisite: Қостанай облысы Науырзым ауданы мәслихатының 2010 жылғы 20 желтоқсандағы № 321 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2010 жылғы 31 желтоқсанда № 9-16-112 тіркелді
title:
  rus: Науырзым ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Науырзым ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '162014000002'
version_date:
  kaz: 2011-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/56589/kaz/16.11.2011
caused_by:
  code: '61629'
  requisite: Решение маслихата Наурзумского района Костанайской области от 16 ноября 2011 года № 419. Зарегистрировано Управлением юстиции Наурзумского района Костанайской области 25 ноября 2011 года № 9-16-130
  title:
    rus: О внесении изменений в решение маслихата от 20 декабря 2010 года № 321 "О районном бюджете Наурзумского района на 2011-2013 годы"
    kaz: Мәслихаттың 2010 жылғы 20 желтоқсандағы № 321 "Науырзым ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61629/rus
