act_code: '56589'
requisite: Қостанай облысы Науырзым ауданы мәслихатының 2010 жылғы 20 желтоқсандағы № 321 шешімі. Қостанай облысы Науырзым ауданының Әділет басқармасында 2010 жылғы 31 желтоқсанда № 9-16-112 тіркелді
title:
  rus: Науырзым ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
  kaz: Науырзым ауданының 2011-2013 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-20
approved_by:
- '162014000002'
version_date:
  kaz: 2010-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/56589/kaz/20.12.2010
