act_code: '138866'
requisite: Решение маслихата Житикаринского района Костанайской области от 13 января 2020 года № 375. Зарегистрировано Департаментом юстиции Костанайской области 21 января 2020 года № 8910. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-01-13
approved_by:
- '162008000002'
version_date:
  kaz: 2021-09-17
  rus: 2021-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/138866/kaz/17.09.2021
  rus: https://zan.gov.kz/client/#!/doc/138866/rus/17.09.2021
caused_by:
  code: '158737'
  requisite: Решение маслихата Житикаринского района Костанайской области от 17 сентября 2021 года № 69. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 96 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 13 января 2020 года № 375 «Об утверждении Регламента собрания местного сообщества»
    kaz: Мәслихаттың 2020 жылғы 13 қаңтардағы № 375 «Жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158737/rus
