act_code: '69195'
requisite: Решение маслихата Костанайской области от 7 декабря 2012 года № 101. Зарегистрировано Департаментом юстиции Костанайской области 11 декабря 2012 года № 3930. Утратило силу в связи с истечением срока действия (письмо Костанайского областного маслихата от 22 января 2014 года № 21)
title:
  rus: Об областном бюджете Костанайской области на 2013-2015 годы
  kaz: Қостанай облысының 2013-2015 жылдарға арналған облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-07
approved_by:
- '162000000002'
version_date:
  kaz: 2013-12-09
  rus: 2013-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/69195/kaz/09.12.2013
  rus: https://zan.gov.kz/client/#!/doc/69195/rus/09.12.2013
caused_by:
  code: '75737'
  requisite: Решение маслихата Костанайской области от 9 декабря 2013 года № 220. Зарегистрировано Департаментом юстиции Костанайской области 10 декабря 2013 года № 4336. Утратило силу в связи с истечением срока действия (письмо Костанайского областного маслихата от 22 января 2014 года № 21)
  title:
    rus: О внесении изменений в решение маслихата от 7 декабря 2012 года № 101 "Об областном бюджете Костанайской области на 2013 - 2015 годы"
    kaz: Мәслихаттың 2012 жылғы 7 желтоқсандағы № 101 "Қостанай облысының 2013 - 2015 жылдарға арналған облыстық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75737/rus
