act_code: '121570'
requisite: Решение маслихата Денисовского района Костанайской области от 13 апреля 2018 года № 183. Зарегистрировано Департаментом юстиции Костанайской области 5 мая 2018 года № 7744. Утратило силу решением маслихата Денисовского района Костанайской области от 29 января 2020 года № 7 (вводится в действие для сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества Денисовского сельского округа Денисовского района Костанайской области
  kaz: Қостанай облысы Денисов ауданы Денисов ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-13
approved_by:
- '162006000002'
version_date:
  kaz: 2019-10-09
  rus: 2019-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/121570/kaz/09.10.2019
  rus: https://zan.gov.kz/client/#!/doc/121570/rus/09.10.2019
caused_by:
  code: '135511'
  requisite: Решение маслихата Денисовского района Костанайской области от 9 октября 2019 года № 65. Зарегистрировано Департаментом юстиции Костанайской области 24 октября 2019 года № 8717. Утратило силу решением маслихата Денисовского района Костанайской области от 29 января 2020 года № 7 (вводится в действие для сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 13 апреля 2018 года № 183 «Об утверждении Регламента собрания местного сообщества Денисовского сельского округа Денисовского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 13 сәуірдегі № 183 «Қостанай облысы Денисов ауданы Денисов ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135511/rus
