act_code: '145540'
requisite: Решение маслихата Мендыкаринского района Костанайской области от 13 августа 2020 года № 397. Зарегистрировано Департаментом юстиции Костанайской области 17 августа 2020 года № 9380. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 28 декабря 2023 года № 89 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-08-13
approved_by:
- '162013000002'
version_date:
  kaz: 2020-12-21
  rus: 2020-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/145540/kaz/21.12.2020
  rus: https://zan.gov.kz/client/#!/doc/145540/rus/21.12.2020
caused_by:
  code: '150391'
  requisite: Решение маслихата Мендыкаринского района Костанайской области от 21 декабря 2020 года № 423. Зарегистрировано Департаментом юстиции Костанайской области 24 декабря 2020 года № 9653. Утратило силу решением маслихата Мендыкаринского района Костанайской области от 28 декабря 2023 года № 89 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 13 августа 2020 года № 397 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мәслихаттың 2020 жылғы 13 тамыздағы № 397 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150391/rus
