act_code: '46319'
requisite: Решение маслихата города Лисаковска Костанайской области от 23 апреля 2009 года № 169. Зарегистрировано Управлением юстиции города Лисаковска Костанайской области 1 июня 2009 года № 9-4-143. Утратило силу решением маслихата города Лисаковска Костанайской области от 7 февраля 2018 года № 201
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салықтың ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-23
approved_by:
- '162020000002'
version_date:
  kaz: 2015-12-21
  rus: 2015-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/46319/kaz/21.12.2015
  rus: https://zan.gov.kz/client/#!/doc/46319/rus/21.12.2015
caused_by:
  code: '98009'
  requisite: Решение маслихата города Лисаковска Костанайской области от 21 декабря 2015 года № 384. Зарегистрировано Департаментом юстиции Костанайской области 19 января 2016 года № 6148. Утратило силу решением маслихата города Лисаковска Костанайской области от 7 февраля 2018 года № 201
  title:
    rus: О внесении изменений в решение маслихата от 23 апреля 2009 года № 169 "Об установлении единых ставок фиксированного налога"
    kaz: Мәслихаттың 2009 жылғы 23 сәуірдегі № 169 "Бірынғай тіркелген салықтың ставкаларын белгілеу туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/98009/rus
