act_code: '158015'
requisite: Решение акима Денисовского района Костанайской области от 13 августа 2021 года № 7. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 августа 2021 года № 24056
title:
  rus: Об образовании избирательных участков на территории Денисовского района
  kaz: Денисов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-08-13
approved_by:
- '162006000003'
version_date:
  kaz: 2021-08-13
  rus: 2021-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/158015/kaz/13.08.2021
  rus: https://zan.gov.kz/client/#!/doc/158015/rus/13.08.2021
