act_code: '151682'
requisite: Решение маслихата города Лисаковска Костанайской области от 8 января 2021 года № 469. Зарегистрировано Департаментом юстиции Костанайской области 12 января 2021 года № 9710
title:
  rus: О бюджетах поселка Октябрьский, села Красногорское города Лисаковска на 2021-2023 годы
  kaz: Лисаков қаласы Октябрь кентінің, Красногор ауылының 2021-2023 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '162020000002'
version_date:
  kaz: 2021-06-08
  rus: 2021-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/151682/kaz/08.06.2021
  rus: https://zan.gov.kz/client/#!/doc/151682/rus/08.06.2021
caused_by:
  code: '156525'
  requisite: Решение маслихата города Лисаковска Костанайской области от 8 июня 2021 года № 47. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 июня 2021 года № 23131
  title:
    rus: О внесении изменений в решение маслихата от 8 января 2021 года № 469 «О бюджетах поселка Октябрьский, села Красногорское города Лисаковска на 2021-2023 годы»
    kaz: Мәслихаттың 2021 жылғы 8 қаңтардағы № 469 «Лисаков қаласы Октябрь кентінің, Красногор аулының 2021-2023 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156525/rus
