act_code: '77876'
requisite: Решение акима Денисовского района Костанайской области от 27 января 2014 года № 2. Зарегистрировано Департаментом юстиции Костанайской области 5 марта 2014 года № 4476. Утратило силу решением акима Денисовского района Костанайской области от 3 августа 2015 года № 14
title:
  rus: Об образовании избирательных участков на территории Денисовского района
  kaz: Денисов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-27
approved_by:
- '162006000003'
version_date:
  kaz: 2014-01-27
  rus: 2014-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/77876/kaz/27.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77876/rus/27.01.2014
