act_code: '140039'
requisite: Решение акима Денисовского района Костанайской области от 2 марта 2020 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 6 марта 2020 года № 9003. Утратило силу решением акима Денисовского района Костанайской области от 13 августа 2021 года № 7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Денисовского района
  kaz: Денисов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-02
approved_by:
- '162006000003'
version_date:
  kaz: 2020-03-02
  rus: 2020-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/140039/kaz/02.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140039/rus/02.03.2020
