act_code: '120303'
requisite: Решение маслихата города Лисаковска Костанайской области от 19 марта 2018 года № 229. Зарегистрировано Департаментом юстиции Костанайской области 3 апреля 2018 года № 7656. Утратило силу решением маслихата города Лисаковска Костанайской области от 20 ноября 2025 года № 201 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Лисаковского городского маслихата»
  kaz: «Лисаков қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-19
approved_by:
- '162020000002'
version_date:
  kaz: 2022-02-28
  rus: 2022-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/120303/kaz/28.02.2022
  rus: https://zan.gov.kz/client/#!/doc/120303/rus/28.02.2022
caused_by:
  code: '164905'
  requisite: Решение маслихата города Лисаковска Костанайской области от 28 февраля 2022 года № 120. Отменено решением маслихата города Лисаковска Костанайской области от 20 ноября 2025 года № 202 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 19 марта 2018 года № 229 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Лисаковского городского маслихата»
    kaz: Мәслихаттың 2018 жылғы 19 наурыздағы № 229 «Лисаков қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164905/rus
