act_code: '107061'
requisite: Решение маслихата Житикаринского района Костанайской области от 20 сентября 2016 года № 59. Зарегистрировано Департаментом юстиции Костанайской области 21 октября 2016 года № 6662. Утратило силу решением маслихата Житикаринского района Костанайской области от 29 марта 2019 года № 286 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Житикаринскому району
  kaz: Жітіқара ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-20
approved_by:
- '162008000002'
version_date:
  kaz: 2016-09-20
  rus: 2016-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/107061/kaz/20.09.2016
  rus: https://zan.gov.kz/client/#!/doc/107061/rus/20.09.2016
