act_code: '164196'
requisite: Решение маслихата Житикаринского района Костанайской области от 25 января 2022 года № 113. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 января 2022 года № 26690
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Житикаринскому району
  kaz: Жітіқара ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-25
approved_by:
- '162008000002'
version_date:
  kaz: 2022-01-25
  rus: 2022-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/164196/kaz/25.01.2022
  rus: https://zan.gov.kz/client/#!/doc/164196/rus/25.01.2022
