act_code: '69689'
requisite: Решение маслихата Сарыкольского района Костанайской области от 21 декабря 2012 года № 53. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2012 года № 3974
title:
  rus: О районном бюджете Сарыкольского района на 2013-2015 годы
  kaz: Сарыкөл ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '162015000002'
version_date:
  kaz: 2013-07-11
  rus: 2013-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/69689/kaz/11.07.2013
  rus: https://zan.gov.kz/client/#!/doc/69689/rus/11.07.2013
caused_by:
  code: '73612'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 11 июля 2013 года № 94. Зарегистрировано Департаментом юстиции Костанайской области 23 июля 2013 года № 4202
  title:
    rus: О внесении изменения в решение маслихата от 21 декабря 2012 года № 53 "О районном бюджете Сарыкольского района на 2013-2015 годы"
    kaz: Мәслихаттың 2012 жылғы 21 желтоқсандағы № 53 "Сарыкөл ауданының 2013-2015 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73612/rus
