act_code: '82322'
requisite: Решение маслихата Тарановского района Костанайской области от 22 июля 2014 года № 219. Зарегистрировано Департаментом юстиции Костанайской области 20 августа 2014 года № 5027. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 23 января 2020 года № 350 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Новоильновского сельского округа Тарановского района Костанайской области
  kaz: Қостанай облысы Таран ауданы Новоильинов ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-07-22
approved_by:
- '162016000002'
version_date:
  kaz: 2014-07-22
  rus: 2014-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/82322/kaz/22.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82322/rus/22.07.2014
