act_code: '167631'
requisite: Решение акима города Костаная Костанайской области от 12 мая 2022 года № 2. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28028. Утратило силу решением акима города Костаная Костанайской области от 30 декабря 2024 года № 4 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-12
approved_by:
- '162002000003'
version_date:
  kaz: 2022-05-12
  rus: 2022-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/167631/kaz/12.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167631/rus/12.05.2022
