act_code: '121906'
requisite: Решение маслихата Карасуского района Костанайской области от 27 апреля 2018 года № 222. Зарегистрировано Департаментом юстиции Костанайской области 17 мая 2018 года № 7765. Утратило силу решением маслихата Карасуского района Костанайской области от 5 февраля 2020 года № 369 (вводится в действие для сел, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
title:
  rus: Об утверждении Регламента собрания местного сообщества села Карасу Карасуского района Костанайской области
  kaz: Қостанай облысы Қарасу ауданы Қарасу ауылы жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-27
approved_by:
- '162011000002'
version_date:
  kaz: 2019-10-01
  rus: 2019-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/121906/kaz/01.10.2019
  rus: https://zan.gov.kz/client/#!/doc/121906/rus/01.10.2019
caused_by:
  code: '135033'
  requisite: Решение маслихата Карасуского района Костанайской области от 1 октября 2019 года № 342. Зарегистрировано Департаментом юстиции Костанайской области 3 октября 2019 года № 8680. Утратило силу решением маслихата Карасуского района Костанайской области от 5 февраля 2020 года № 369 (вводится в действие для сел, сельского округа с численностью населения более двух тысяч человек с 1 января 2018 года и для сел, сельских округов с численностью населения две тысячи и менее человек с 1 января 2020 года)
  title:
    rus: О внесении изменения в решение маслихата от 27 апреля 2018 года № 222 «Об утверждении Регламента собрания местного сообщества села Карасу Карасуского района Костанайской области»
    kaz: Мәслихаттың 2018 жылғы 27 сәуірдегі № 222 «Қостанай облысы Қарасу ауданы Қарасу ауылы жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135033/rus
