act_code: '49664'
requisite: Решение маслихата Костанайского района Костанайской области от 23 декабря 2009 года № 254. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 30 декабря 2009 года № 9-14-116
title:
  rus: О районном бюджете Костанайского района на 2010-2012 годы
  kaz: Қостанай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '162012000002'
version_date:
  kaz: 2010-03-03
  rus: 2010-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49664/kaz/03.03.2010
  rus: https://zan.gov.kz/client/#!/doc/49664/rus/03.03.2010
caused_by:
  code: '51276'
  requisite: Решение маслихата Костанайского района Костанайской области от 3 марта 2010 года № 271. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 17 марта 2010 года № 9-14-121
  title:
    rus: О внесении изменений в решение маслихата от 23 декабря 2009 года № 254 "О районном бюджете Костанайского района на 2010-2012 годы"
    kaz: Мәслихаттың 2009 жылғы 23 желтоқсандағы № 254 "Қостанай ауданының 2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51276/rus
