act_code: '138250'
requisite: Решение маслихата Сарыкольского района Костанайской области от 10 января 2020 года № 309. Зарегистрировано Департаментом юстиции Костанайской области 10 января 2020 года № 8878
title:
  rus: О районном бюджете Сарыкольского района на 2020-2022 годы
  kaz: Сарыкөл ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-10
approved_by:
- '162015000002'
version_date:
  kaz: 2020-11-05
  rus: 2020-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/138250/kaz/05.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138250/rus/05.11.2020
caused_by:
  code: '148235'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 5 ноября 2020 года № 374. Зарегистрировано Департаментом юстиции Костанайской области 6 ноября 2020 года № 9539
  title:
    rus: О внесении изменений в решение маслихата от 10 января 2020 года № 309 «О районном бюджете Сарыкольского района на 2020-2022 годы»
    kaz: Мәслихаттың 2020 жылғы 10 қаңтардағы № 309 «Сарыкөл ауданының 2020-2022 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148235/rus
