act_code: '38755'
requisite: Решение маслихата города Рудного Костанайской области от 28 февраля 2008 года № 60. Зарегистрировано Управлением юстиции города Рудного Костанайской области 4 апреля 2008 года № 9-2-102. Утратило силу - Решением маслихата города Рудного Костанайской области от 10 апреля 2009 года № 189
title:
  rus: Об установлении ставки платы за размещение наружной (визуальной) рекламы
  kaz: Сыртқы (көрнекі) жарнаманы орналастырғаны үшін төлем ставкасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-28
approved_by:
- '162021000002'
version_date:
  kaz: 2008-02-28
  rus: 2008-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/38755/kaz/28.02.2008
  rus: https://zan.gov.kz/client/#!/doc/38755/rus/28.02.2008
