act_code: '150799'
requisite: Решение маслихата Амангельдинского района Костанайской области от 25 декабря 2020 года № 421. Зарегистрировано Департаментом юстиции Костанайской области 29 декабря 2020 года № 9660
title:
  rus: О районном бюджете Амангельдинского района на 2021 - 2023 годы
  kaz: Амангелді ауданының 2021 – 2023 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '162004000002'
version_date:
  kaz: 2021-09-21
  rus: 2021-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/150799/kaz/21.09.2021
  rus: https://zan.gov.kz/client/#!/doc/150799/rus/21.09.2021
caused_by:
  code: '159001'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 21 сентября 2021 года № 74. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 сентября 2021 года № 24539
  title:
    rus: О внесении изменений в решение маслихата от 25 декабря 2020 года № 421 «О районном бюджете Амангельдинского района на 2021 - 2023 годы»
    kaz: Мәслихаттың 2020 жылғы 25 желтоқсандағы № 421 «Амангелді ауданының 2021 - 2023 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159001/rus
