act_code: '159850'
requisite: Решение маслихата Сарыкольского района Костанайской области от 15 октября 2021 года № 63. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 октября 2021 года № 24960
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Сарыкольском районе
  kaz: Сарыкөл ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-10-15
approved_by:
- '162015000002'
version_date:
  kaz: 2023-06-07
  rus: 2023-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/159850/kaz/07.06.2023
  rus: https://zan.gov.kz/client/#!/doc/159850/rus/07.06.2023
caused_by:
  code: '182838'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 7 июня 2023 года № 44. Зарегистрировано в Департаменте юстиции Костанайской области 13 июня 2023 года № 10022
  title:
    rus: О внесении изменений в решение маслихата от 15 октября 2021 года № 63 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Сарыкольском районе»
    kaz: Мәслихаттың 2021 жылғы 15 қазандағы № 63 «Сарыкөл ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182838/rus
