act_code: '188768'
requisite: Решение маслихата Костанайской области от 25 июля 2016 года № 60
title:
  rus: Об утверждении Положения о государственном учреждении «Ревизионная комиссия по Костанайской области»
  kaz: «Қостанай облысы бойынша тексеру комиссиясы» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2016-07-25
approved_by:
- '162000000002'
version_date:
  kaz: 2026-08-13
  rus: 2026-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/188768/kaz/13.08.2026
  rus: https://zan.gov.kz/client/#!/doc/188768/rus/13.08.2026
caused_by:
  code: '229119'
  requisite: Решение Костанайского областного маслихата от 13 августа 2026 года № 309
  title:
    rus: О внесении изменений и дополнения в решение Костанайского областного маслихата от 25 июля 2016 года № 60 «Об утверждении Положения государственного учреждения «Ревизионная комиссия по Костанайской области»
    kaz: ««Қостанай облысы бойынша тексеру комиссиясы» мемлекеттік мекемесінің ережесін бекіту туралы» Қостанай облыстық мәслихатының 2016 жылғы 25 шілдедегі № 60 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229119/rus
