act_code: '139239'
requisite: Решение маслихата города Аркалыка Костанайской области от 28 января 2020 года № 297. Зарегистрировано Департаментом юстиции Костанайской области 31 января 2020 года № 8942
title:
  rus: Об утверждении Регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2020-01-28
approved_by:
- '162019000002'
version_date:
  kaz: 2023-05-17
  rus: 2023-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/139239/kaz/17.05.2023
  rus: https://zan.gov.kz/client/#!/doc/139239/rus/17.05.2023
caused_by:
  code: '181554'
  requisite: Решение маслихата города Аркалыка Костанайской области от 17 мая 2023 года № 29
  title:
    rus: О внесении изменения в решение маслихата от 28 января 2020 года № 297 «Об утверждении Регламента собрания местного сообщества»
    kaz: Мәслихаттың 2020 жылғы 28 қаңтардағы № 297 «Жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181554/rus
