act_code: '159171'
requisite: Решение маслихата Костанайского района Костанайской области от 22 сентября 2021 года № 93. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 октября 2021 года № 24621
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Костанайском районе
  kaz: Қостанай ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-09-22
approved_by:
- '162012000002'
version_date:
  kaz: 2021-09-22
  rus: 2021-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/159171/kaz/22.09.2021
  rus: https://zan.gov.kz/client/#!/doc/159171/rus/22.09.2021
