act_code: '126538'
requisite: Решение акима Камыстинского сельского округа Камыстинского района Костанайской области от 12 ноября 2018 года № 6. Зарегистрировано Департаментом юстиции Костанайской области 30 ноября 2018 года № 8143
title:
  rus: Об установлении публичного сервитута на земельный участок
  kaz: Жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-12
approved_by:
- '162009001002'
version_date:
  kaz: 2018-11-12
  rus: 2018-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/126538/kaz/12.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126538/rus/12.11.2018
