act_code: '85658'
requisite: Решение №198 от 24.12.2014, Маслихат Джангельдинского района
title:
  rus: О районном бюджете Джангельдинского района на 2015-2017 годы
  kaz: Жангелдин ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162007000002'
version_date:
  kaz: 2015-05-27
  rus: 2015-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85658/kaz/27.05.2015
  rus: https://zan.gov.kz/client/#!/doc/85658/rus/27.05.2015
caused_by:
  code: '90347'
  requisite: Решение №225 от 27.05.2015, Маслихат Джангельдинского района
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2014 года № 198 "О районном бюджете Джангельдинского района на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 198 "Жангелдин ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90347/rus
