act_code: '101823'
requisite: Решение маслихата Денисовского района Костанайской области от 1 апреля 2016 года № 18. Зарегистрировано Департаментом юстиции Костанайской области 29 апреля 2016 года № 6312. Утратило силу решением маслихата Денисовского района Костанайской области от 6 июня 2018 года № 202
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-01
approved_by:
- '162006000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/101823/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/101823/rus/01.04.2016
