act_code: '188163'
requisite: Решение акима Адаевского сельского округа Камыстинского района Костанайской области от 9 ноября 2023 года № 10
title:
  rus: Об установлении право ограниченного целевого землепользования (публичный сервитут) акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына шектеулі нысаналы жер пайдалану құқығын (жария сервитут) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-09
approved_by:
- '162009005002'
version_date:
  kaz: 2023-11-09
  rus: 2023-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/188163/kaz/09.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188163/rus/09.11.2023
