act_code: '55635'
requisite: Решение акима Аулиекольского района Костанайской области от 28 октября 2010 года № 5. Зарегистрировано Управлением юстиции Аулиекольского района Костанайской области 24 ноября 2010 года № 9-7-125
title:
  rus: Об организации и обеспечении приписки граждан мужского пола 1994 года рождения к призывному участку Аулиекольского района
  kaz: Әулиекөл ауданының әскерге шақыру учаскесiне 1994 жылы туған ер азаматтарды тiркеуді ұйымдастыру мен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-28
approved_by:
- '162005000003'
version_date:
  kaz: 2010-10-28
  rus: 2010-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/55635/kaz/28.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55635/rus/28.10.2010
