act_code: '117771'
requisite: Решение маслихата Федоровского района Костанайской области от 20 декабря 2017 года № 190. Зарегистрировано Департаментом юстиции Костанайской области 10 января 2018 года № 7473
title:
  rus: О районном бюджете Федоровского района на 2018 – 2020 годы
  kaz: Федоров ауданының 2018 - 2020 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-20
approved_by:
- '162018000002'
version_date:
  kaz: 2018-04-26
  rus: 2018-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/117771/kaz/26.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117771/rus/26.04.2018
caused_by:
  code: '121769'
  requisite: Решение маслихата Федоровского района Костанайской области от 26 апреля 2018 года № 235. Зарегистрировано Департаментом юстиции Костанайской области 11 мая 2018 года № 7756
  title:
    rus: О внесении изменений в решение маслихата от 20 декабря 2017 года № 190 «О районном бюджете Федоровского района на 2018 – 2020 годы»
    kaz: Мәслихаттың 2017 жылғы 20 желтоқсандағы № 190 «Федоров ауданының 2018-2020 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121769/rus
