act_code: '120253'
requisite: Решение маслихата Житикаринского района Костанайской области от 19 марта 2018 года № 197. Зарегистрировано Департаментом юстиции Костанайской области 2 апреля 2018 года № 7647. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 95 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Житикаринского районного маслихата»
  kaz: «Жітіқара аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-19
approved_by:
- '162008000002'
version_date:
  kaz: 2022-02-18
  rus: 2022-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/120253/kaz/18.02.2022
  rus: https://zan.gov.kz/client/#!/doc/120253/rus/18.02.2022
caused_by:
  code: '164615'
  requisite: Решение маслихата Житикаринского района Костанайской области от 18 февраля 2022 года № 131. Утратило силу решением маслихата Житикаринского района Костанайской области от 27 декабря 2023 года № 95 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 19 марта 2018 года № 197 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Житикаринского районного маслихата»
    kaz: Мәслихаттың 2018 жылғы 19 наурыздағы № 197 «Жітіқара аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164615/rus
