act_code: '64860'
requisite: Решение маслихата Узункольского района Костанайской области от 12 апреля 2012 года № 26. Зарегистрировано Управлением юстиции Узункольского района Костанайской области 18 апреля 2012 года № 9-19-175. Утратило силу решением маслихата Узункольского района Костанайской области от 29 ноября 2013 года № 155
title:
  rus: О социальной помощи отдельным категориям нуждающихся граждан
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлуметтік көмек туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2012-04-12
approved_by:
- '162017000002'
version_date:
  kaz: 2012-04-12
  rus: 2012-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/64860/kaz/12.04.2012
  rus: https://zan.gov.kz/client/#!/doc/64860/rus/12.04.2012
