act_code: '120005'
requisite: Решение маслихата Федоровского района Костанайской области от 15 марта 2018 года № 229. Зарегистрировано Департаментом юстиции Костанайской области 30 марта 2018 года № 7636
title:
  rus: О повышении ставок единого земельного налога
  kaz: Бірыңғай жер салығының мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-15
approved_by:
- '162018000002'
version_date:
  kaz: 2018-03-15
  rus: 2018-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/120005/kaz/15.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120005/rus/15.03.2018
