act_code: '82565'
requisite: Решение маслихата Сарыкольского района Костанайской области от 8 августа 2014 года № 198. Зарегистрировано Департаментом юстиции Костанайской области 19 августа 2014 года № 5013. Утратило силу решением маслихата Сарыкольского района Костанайской области от 4 сентября 2020 года № 358 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Златоустовского сельского округа Сарыкольского района Костанайской области
  kaz: Қостанай облысы Сарыкөл ауданының Златоуст ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-08-08
approved_by:
- '162015000002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/82565/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/82565/rus/27.06.2018
caused_by:
  code: '123459'
  requisite: Решение маслихата Сарыкольского района Костанайской области от 27 июня 2018 года № 181. Зарегистрировано Департаментом юстиции Костанайской области 9 июля 2018 года № 7940. Утратило силу решением маслихата Сарыкольского района Костанайской области от 4 сентября 2020 года № 358 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 8 августа 2014 года № 198 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Златоустовского сельского округа Сарыкольского района Костанайской области»
    kaz: Мәслихаттың 2014 жылғы 8 тамыздағы № 198 «Қостанай облысы Сарыкөл ауданының Златоуст ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123459/rus
