act_code: '82565'
requisite: Решение маслихата Сарыкольского района Костанайской области от 8 августа 2014 года № 198. Зарегистрировано Департаментом юстиции Костанайской области 19 августа 2014 года № 5013. Утратило силу решением маслихата Сарыкольского района Костанайской области от 4 сентября 2020 года № 358 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества Златоустовского сельского округа Сарыкольского района Костанайской области
  kaz: Қостанай облысы Сарыкөл ауданының Златоуст ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-08-08
approved_by:
- '162015000002'
version_date:
  kaz: 2014-08-08
  rus: 2014-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/82565/kaz/08.08.2014
  rus: https://zan.gov.kz/client/#!/doc/82565/rus/08.08.2014
