act_code: '85785'
requisite: Решение маслихата города Лисаковска Костанайской области от 24 декабря 2014 года № 259. Зарегистрировано Департаментом юстиции Костанайской области 9 января 2015 года № 5285
title:
  rus: О бюджете города Лисаковска  на 2015-2017 годы
  kaz: Лисаков қаласының 2015-2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162020000002'
version_date:
  kaz: 2015-08-18
  rus: 2015-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85785/kaz/18.08.2015
  rus: https://zan.gov.kz/client/#!/doc/85785/rus/18.08.2015
caused_by:
  code: '93102'
  requisite: Решение маслихата города Лисаковска Костанайской области от 18 августа 2015 года № 336. Зарегистрировано Департаментом юстиции Костанайской области 21 августа 2015 года № 5825
  title:
    rus: О внесении изменений в решение маслихата от 24 декабря 2014 года № 259 "О бюджете города Лисаковска на 2015-2017 годы"
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 259 "Лисаков қаласының 2015-2017 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93102/rus
