act_code: '178913'
requisite: Решение акима Владимировского сельского округа Костанайского района Костанайской области от 6 января 2023 года № 1р
title:
  rus: Об установлении акционерному обществу «Казахтелеком» публичного сервитута на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-01-06
approved_by:
- '162012003002'
version_date:
  kaz: 2023-01-06
  rus: 2023-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/178913/kaz/06.01.2023
  rus: https://zan.gov.kz/client/#!/doc/178913/rus/06.01.2023
