act_code: '133102'
requisite: Решение акима села Ашутасты города Аркалыка Костанайской области от 27 июня 2019 года № 3. Зарегистрировано Департаментом юстиции Костанайской области 28 июня 2019 года № 8560. Утратило силу решением акима Ашутастинского сельского округа города Аркалыка Костанайской области от 13 декабря 2021 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении публичного сервитута акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-27
approved_by:
- '162019006001'
version_date:
  kaz: 2020-11-23
  rus: 2020-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/133102/kaz/23.11.2020
  rus: https://zan.gov.kz/client/#!/doc/133102/rus/23.11.2020
caused_by:
  code: '148968'
  requisite: Решение акима Ашутастинского сельского округа города Аркалыка Костанайской области от 23 ноября 2020 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 26 ноября 2020 года № 9594. Утратило силу решением акима Ашутастинского сельского округа города Аркалыка Костанайской области от 13 декабря 2021 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима от 27 июня 2019 года № 3 «Об установлении публичного сервитута акционерному обществу «Казахтелеком»
    kaz: Әкімнің 2019 жылғы 27 маусымдағы № 3 «Қазақтелеком» акционерлік қоғамына қауымдық сервитут белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148968/rus
