act_code: '75098'
requisite: Решение маслихата Федоровского района Костанайской области от 3 октября 2013 года № 161. Зарегистрировано Департаментом юстиции Костанайской области 1 ноября 2013 года № 4282. Утратило силу решением маслихата Федоровского района Костанайской области от 1 августа 2016 года № 52
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-10-03
approved_by:
- '162018000002'
version_date:
  kaz: 2014-11-27
  rus: 2014-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/75098/kaz/27.11.2014
  rus: https://zan.gov.kz/client/#!/doc/75098/rus/27.11.2014
caused_by:
  code: '85597'
  requisite: Решение маслихата Федоровского района Костанайской области от 27 ноября 2014 года № 277. Зарегистрировано Департаментом юстиции Костанайской области 25 декабря 2014 года № 5246. Утратило силу решением маслихата Федоровского района Костанайской области от 1 августа 2016 года № 52
  title:
    rus: О внесении изменения в решение маслихата от 3 октября 2013 года № 161 "Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан"
    kaz: Мәслихаттың 2013 жылғы 3 қазандағы № 161 "Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85597/rus
