act_code: '195444'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 28 марта 2024 года № 90. Зарегистрировано в Департаменте юстиции Костанайской области 9 апреля 2024 года № 10173-10
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в районе Беимбета Майлина
  kaz: Бейімбет Майлин ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '162016000002'
version_date:
  kaz: 2025-11-06
  rus: 2025-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/195444/kaz/06.11.2025
  rus: https://zan.gov.kz/client/#!/doc/195444/rus/06.11.2025
caused_by:
  code: '216923'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 6 ноября 2025 года № 199. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 ноября 2025 года № 37418
  title:
    rus: «О внесении изменений в решение маслихата района Беимбета Майлина от 28 марта 2024 года № 90 «Об определении размера и порядка оказания жилищной помощи в районе Беимбета Майлина»»
    kaz: «Бейімбет Майлин ауданы мәслихатының 2024 жылғы 28 наурыздағы № 90 «Бейімбет Майлин ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы»» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216923/rus
