act_code: '216131'
requisite: Решение маслихата Узункольского района Костанайской области от 22 октября 2025 года № 192
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Узункольскому району на 2025-2029 годы
  kaz: Ұзынкөл ауданы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2025-10-22
approved_by:
- '162017000002'
version_date:
  kaz: 2025-10-22
  rus: 2025-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/216131/kaz/22.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216131/rus/22.10.2025
