act_code: '55000'
requisite: Қостанай облысы Аманкелді ауданы мәслихатының 2010 жылғы 17 қыркүйектегі № 207 шешімі. Қостанай облысы Аманкелді ауданының Әділет басқармасында 2010 жылғы 20 қазанда № 9-6-116 тіркелді
title:
  rus: Аманкелді ауданының елді мекендерінде иттер мен мысықтарды күтіп - ұстау Ережесін бекіту туралы
  kaz: Аманкелді ауданының елді мекендерінде иттер мен мысықтарды күтіп - ұстау Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-17
approved_by:
- '162004000002'
version_date:
  kaz: 2010-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/55000/kaz/17.09.2010
