act_code: '220466'
requisite: Решение маслихата Камыстинского района Костанайской области от 30 декабря 2025 года № 418
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по Камыстинскому району
  kaz: Қамысты ауданы бойынша шетелдіктер үшін 2026 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-30
approved_by:
- '162009000002'
version_date:
  kaz: 2025-12-30
  rus: 2025-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/220466/kaz/30.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220466/rus/30.12.2025
