act_code: '102195'
requisite: Решение маслихата Костанайского района Костанайской области от 1 апреля 2016 года № 18. Зарегистрировано Департаментом юстции Костанайской области 11 мая 2016 года № 6345. Утратило силу решением маслихата Костанайского района Костанайской области от 14 февраля 2018 года № 220
title:
  rus: О повышении базовых ставок земельного налога на 50 процентов
  kaz: Жер салығының базалық мөлшерлемелерін 50 пайызға жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-01
approved_by:
- '162012000002'
version_date:
  kaz: 2016-04-01
  rus: 2016-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/102195/kaz/01.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102195/rus/01.04.2016
