act_code: '102195'
requisite: Решение маслихата Костанайского района Костанайской области от 1 апреля 2016 года № 18. Зарегистрировано Департаментом юстции Костанайской области 11 мая 2016 года № 6345. Утратило силу решением маслихата Костанайского района Костанайской области от 14 февраля 2018 года № 220
title:
  rus: О повышении базовых ставок земельного налога на 50 процентов
  kaz: Жер салығының базалық мөлшерлемелерін 50 пайызға жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-01
approved_by:
- '162012000002'
version_date:
  kaz: 2017-06-23
  rus: 2017-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/102195/kaz/23.06.2017
  rus: https://zan.gov.kz/client/#!/doc/102195/rus/23.06.2017
caused_by:
  code: '113725'
  requisite: Решение маслихата Костанайского района Костанайской области от 23 июня 2017 года № 147. Зарегистрировано Департаментом юстиции Костанайской области 25 июля 2017 года № 7136. Утратило силу решением маслихата Костанайского района Костанайской области от 14 февраля 2018 года № 220
  title:
    rus: О внесении изменения в решение маслихата от 1 апреля 2016 года № 18 «О повышении базовых ставок земельного налога на 50 процентов»
    kaz: Мәслихаттың 2016 жылғы 1 сәуірдегі № 18 «Жер салығының базалық мөлшерлемелерін 50 пайызға жоғарылату туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/113725/rus
