act_code: '151088'
requisite: Решение маслихата Карабалыкского района Костанайской области от 28 декабря 2020 года № 557. Зарегистрировано Департаментом юстиции Костанайской области 31 декабря 2020 года № 9688
title:
  rus: О районном бюджете Карабалыкского района на 2021-2023 годы
  kaz: Қарабалық ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-28
approved_by:
- '162010000002'
version_date:
  kaz: 2021-09-02
  rus: 2021-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/151088/kaz/02.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151088/rus/02.09.2021
caused_by:
  code: '158518'
  requisite: Решение маслихата Карабалыкского района Костанайской области от 2 сентября 2021 года № 60. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 сентября 2021 года № 24331
  title:
    rus: О внесении изменений в решение маслихата от 28 декабря 2020 года № 557 «О районном бюджете Карабалыкского района на 2021-2023 годы»
    kaz: Мәслихаттың 2020 жылғы 28 желтоқсандағы № 557 «Қарабалық ауданының 2021-2023 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158518/rus
