act_code: '188547'
requisite: Решение маслихата Камыстинского района Костанайской области от 14 ноября 2023 года № 98
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходах местного сообщества сел Аралкольского сельского округа Камыстинского района Костанайской области
  kaz: Қостанай облысы Қамысты ауданы Аралкөл ауылдық округінің жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын және жергілікті қоғамдастықтың жиындарына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-14
approved_by:
- '162009000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/188547/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188547/rus/14.11.2023
