act_code: '141674'
requisite: Решение маслихата Житикаринского района Костанайской области от 9 апреля 2020 года № 394. Зарегистрировано Департаментом юстиции Костанайской области 15 апреля 2020 года № 9120. Утратило силу решением маслихата Житикаринского района Костанайской области от 30 ноября 2023 года № 84 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Муктикольского сельского округа Житикаринского района Костанайской области
  kaz: Қостанай облысы Жітіқара ауданы Мүктікөл ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-04-09
approved_by:
- '162008000002'
version_date:
  kaz: 2022-01-25
  rus: 2022-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/141674/kaz/25.01.2022
  rus: https://zan.gov.kz/client/#!/doc/141674/rus/25.01.2022
caused_by:
  code: '164076'
  requisite: Решение маслихата Житикаринского района Костанайской области от 25 января 2022 года № 120. Утратило силу решением маслихата Житикаринского района Костанайской области от 30 ноября 2023 года № 84 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата от 9 апреля 2020 года № 394 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Муктикольского сельского округа Житикаринского района Костанайской области»
    kaz: Мәслихаттың 2020 жылғы 9 сәуірдегі № 394 «Қостанай облысы Жітіқара ауданы Мүктікөл ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164076/rus
