act_code: '44426'
requisite: Решение маслихата Костанайского района Костанайской области от 16 января 2009 года № 140. Зарегистрировано Управлением юстиции Костанайского района Костанайской области 20 февраля 2009 года № 9-14-101. Утратило силу решением маслихата Костанайского района Костанайской области от 21 апреля 2009 года № 182
title:
  rus: Об утверждении стоимости разовых талонов
  kaz: Бір жолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-16
approved_by:
- '162012000002'
version_date:
  kaz: 2009-01-16
  rus: 2009-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/44426/kaz/16.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44426/rus/16.01.2009
