act_code: '80796'
requisite: Постановление акимата Костанайской области от 19 мая 2014 года № 214. Зарегистрировано Департаментом юстиции Костанайской области 19 июня 2014 года № 4856. Утратило силу постановлением акимата Костанайской области от 28 апреля 2022 года № 181 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении зон санитарной охраны водозаборных скважин № 70, № 74, № 75, № 105 Щербаковского месторождения подземных минеральных вод в Алтынсаринском районе
  kaz: Алтынсарин ауданындағы Щербаков минералды жерасты сулары көздерінің № 70, № 74, № 75, № 105 су тарту ұңғымаларының санитарлық қорғау аймақтарын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-19
approved_by:
- '162000000001'
version_date:
  kaz: 2014-05-19
  rus: 2014-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/80796/kaz/19.05.2014
  rus: https://zan.gov.kz/client/#!/doc/80796/rus/19.05.2014
