act_code: '68409'
requisite: Решение маслихата Костанайской области от 25 сентября 2012 года № 76. Зарегистрировано Департаментом юстиции Костанайской области 8 ноября 2012 года № 3877
title:
  rus: Об утверждении Правил подготовки и проведения отопительного сезона в Костанайской области
  kaz: Қостанай облысында жылыту маусымына дайындалу және өткізу қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-09-25
approved_by:
- '162000000002'
version_date:
  kaz: 2018-12-12
  rus: 2018-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/68409/kaz/12.12.2018
  rus: https://zan.gov.kz/client/#!/doc/68409/rus/12.12.2018
caused_by:
  code: '127313'
  requisite: Решение маслихата Костанайской области от 12 декабря 2018 года № 351. Зарегистрировано Департаментом юстиции Костанайской области 21 декабря 2018 года № 8176
  title:
    rus: О внесении изменений в решение маслихата от 25 сентября 2012 года № 76 «Об утверждении Правил подготовки и проведения отопительного сезона в Костанайской области»
    kaz: Мәслихаттың 2012 жылғы 25 қыркүйектегі № 76 «Қостанай облысында жылыту маусымына дайындалу және өткізу қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127313/rus
