act_code: '158000'
requisite: Решение маслихата Аулиекольского района Костанайской области от 11 августа 2021 года № 54. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 августа 2021 года № 24046. Утратило силу решением маслихата Аулиекольского района Костанайской области от 1 июля 2023 года № 44 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей  с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Аулиекольском районе
  kaz: Әулиекөл ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-08-11
approved_by:
- '162005000002'
version_date:
  kaz: 2022-04-27
  rus: 2022-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/158000/kaz/27.04.2022
  rus: https://zan.gov.kz/client/#!/doc/158000/rus/27.04.2022
caused_by:
  code: '167139'
  requisite: Решение маслихата Аулиекольского района Костанайской области от 27 апреля 2022 года № 123. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 апреля 2022 года № 27827. Утратило силу решением маслихата Аулиекольского района Костанайской области от 1 июля 2023 года № 44 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 11 августа 2021 года № 54 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Аулиекольском районе»
    kaz: Мәслихаттың 2021 жылғы 11 тамыздағы № 54 «Әулиекөл ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167139/rus
