act_code: '102822'
requisite: Решение маслихата Денисовского района Костанайской области от 27 апреля 2016 года № 23. Зарегистрировано Департаментом юстиции Костанайской области 30 мая 2016 года № 6407. Утратило силу решением маслихата Денисовского района Костанайской области от 6 октября 2021 года № 61 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов
  kaz: Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-27
approved_by:
- '162006000002'
version_date:
  kaz: 2020-05-14
  rus: 2020-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/102822/kaz/14.05.2020
  rus: https://zan.gov.kz/client/#!/doc/102822/rus/14.05.2020
caused_by:
  code: '142811'
  requisite: Решение маслихата Денисовского района Костанайской области от 14 мая 2020 года № 32. Зарегистрировано Департаментом юстиции Костанайской области 15 мая 2020 года № 9183. Утратило силу решением маслихата Денисовского района Костанайской области от 6 октября 2021 года № 61 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение  маслихата от 27 апреля 2016 года № 23 «О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов»
    kaz: Мәслихаттың 2016 жылғы 27 сәуірдегі № 23 «Мүгедектер қатарындағы кемтар балаларды үйде оқытуға жұмсаған шығындарын өндіріп алу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142811/rus
