act_code: '85651'
requisite: Решение от 24.12.2014 №278, Маслихат Амангельдинского района
title:
  rus: О районном бюджете Амангельдинского района на 2015-2017 годы
  kaz: Амангелді ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '162004000002'
version_date:
  kaz: 2015-08-18
  rus: 2015-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85651/kaz/18.08.2015
  rus: https://zan.gov.kz/client/#!/doc/85651/rus/18.08.2015
caused_by:
  code: '93003'
  requisite: Решение маслихата Амангельдинского района Костанайской области от 18 августа 2015 года № 339. Зарегистрировано Департаментом юстиции Костанайской области 24 августа 2015 года № 5830
  title:
    rus: О внесении изменений и дополнений в решение маслихата от 24 декабря 2014 года № 278 «О районном бюджете Амангельдинского района на 2015 - 2017 годы»
    kaz: Мәслихаттың 2014 жылғы 24 желтоқсандағы № 278 «Амангелді ауданының 2015-2017 жылдарға арналған аудандық бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93003/rus
