act_code: '20848'
requisite: Решение маслихата города Аркалыка Костанайской области от 21 июля 2004 года № 73. Зарегистрировано Управлением юстиции Костанайской области 3 августа 2004 года № 3102. Утратило силу решением маслихата города Аркалыка Костанайской области от 15 мая 2007 года № 378
title:
  rus: Об утверждении регламента работы Аркалыкского городского маслихата
  kaz: Арқалық қалалық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2004-07-20
approved_by:
- '162019000002'
version_date:
  kaz: 2004-07-20
  rus: 2004-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/20848/kaz/20.07.2004
  rus: https://zan.gov.kz/client/#!/doc/20848/rus/20.07.2004
