act_code: '139131'
requisite: Решение маслихата района Беимбета Майлина Костанайской области от 23 января 2020 года № 346. Зарегистрировано Департаментом юстиции Костанайской области 29 января 2020 года № 8926. Утратило силу решением маслихата района Беимбета Майлина Костанайской области от 15 сентября 2023 года № 42 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Асенкритовского сельского округа района Беимбета Майлина Костанайской области
  kaz: Қостанай облысы Бейімбет Майлин ауданы Асенкритов ауылдық округінің жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-01-23
approved_by:
- '162016000002'
version_date:
  kaz: 2022-03-09
  rus: 2022-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/139131/kaz/09.03.2022
  rus: https://zan.gov.kz/client/#!/doc/139131/rus/09.03.2022
caused_by:
  code: '165086'
  requisite: Решение маслихата района Беимбета Майлина Костанайской области от 9 марта 2022 года № 97. Отменено решением маслихата района Беимбета Майлина Костанайской области от 1 сентября 2023 года № 35 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата от 23 января 2020 года № 346 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Асенкритовского сельского округа района Беимбета Майлина Костанайской области»
    kaz: Мәслихаттың 2020 жылғы 23 қаңтардағы № 346 «Қостанай облысы Бейімбет Майлин ауданы Асенкритов ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165086/rus
