act_code: '145852'
requisite: Решение акима Каиндинского сельского округа города Аркалыка Костанайской области от 27 августа 2020 года № 4. Зарегистрировано Департаментом юстиции Костанайской области 28 августа 2020 года № 9415
title:
  rus: О снятии карантина
  kaz: Карантинді тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-27
approved_by:
- '162019002002'
version_date:
  kaz: 2020-08-27
  rus: 2020-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/145852/kaz/27.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145852/rus/27.08.2020
