act_code: '6166'
requisite: Решение акима Костанайской области от 20 апреля 2000 года № 93а. Зарегистрировано Управлением юстиции Костанайской области 9 июня 2000 года № 289. Прекратил действие в связи с истечением срока применения - письмо аппарата акима Костанайской области от 11 декабря 2006 года № 08-3/3087
title:
  rus: О разработке проекта бюджета Костанайской области на 2001 год
  kaz: 2001 жылға арналған Қостанай облысының бюджет жобасын әзірлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-19
approved_by:
- '162000000003'
version_date:
  kaz: 2000-04-19
  rus: 2000-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/6166/kaz/19.04.2000
  rus: https://zan.gov.kz/client/#!/doc/6166/rus/19.04.2000
