act_code: '133185'
requisite: Решение акима Бауманского сельского округа Узункольского района Костанайской области от 4 июля 2019 года № 1. Зарегистрировано Департаментом юстиции Костанайской области 5 июля 2019 года № 8578
title:
  rus: Об установлении публичного сервитута акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-04
approved_by:
- '162017001002'
version_date:
  kaz: 2019-07-04
  rus: 2019-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/133185/kaz/04.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133185/rus/04.07.2019
