act_code: '132671'
requisite: Решение акима Мичуринского сельского округа Костанайского района Костанайской области от 14 июня 2019 года № 4-р. Зарегистрировано Департаментом юстиции Костанайской области 18 июня 2019 года № 8539
title:
  rus: Об установлении акционерному обществу «Казахтелеком» публичного сервитута на земельный участок
  kaz: «Қазақтелеком» акционерлік қоғамына жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-14
approved_by:
- '162012009002'
version_date:
  kaz: 2019-06-14
  rus: 2019-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/132671/kaz/14.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132671/rus/14.06.2019
