act_code: '176549'
requisite: Решение маслихата Камыстинского района Костанайской области от 29 декабря 2022 года № 211
title:
  rus: О бюджете Аркинского сельского округа Камыстинского района на 2023-2025 годы
  kaz: Қамысты ауданы Арқа ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '162009000002'
version_date:
  kaz: 2023-07-03
  rus: 2023-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/176549/kaz/03.07.2023
  rus: https://zan.gov.kz/client/#!/doc/176549/rus/03.07.2023
caused_by:
  code: '183773'
  requisite: Решение маслихата Камыстинского района Костанайской области от 3 июля 2023 года № 53
  title:
    rus: О внесении изменений в решение маслихата от 29 декабря 2022 года № 211 «О бюджете Аркинского сельского округа Камыстинского района на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 29 желтоқсандағы № 211 «Қамысты ауданы Арқа ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183773/rus
