act_code: '166896'
requisite: Решение маслихата Костанайской области от 20 апреля 2022 года № 172. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 апреля 2022 года № 27716
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников
  kaz: Жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-20
approved_by:
- '162000000002'
version_date:
  kaz: 2023-08-11
  rus: 2023-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/166896/kaz/11.08.2023
  rus: https://zan.gov.kz/client/#!/doc/166896/rus/11.08.2023
caused_by:
  code: '185325'
  requisite: Решение маслихата Костанайской области от 11 августа 2023 года № 40. Зарегистрировано в Департаменте юстиции Костанайской области 23 августа 2023 года № 10050
  title:
    rus: О внесении изменения в решение маслихата от 20 апреля 2022 года № 172 «О ставках платы за пользование водными ресурсами из поверхностных источников»
    kaz: «Жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы» мәслихаттың 2022 жылғы 20 сәуірдегі № 172 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185325/rus
