act_code: '166896'
requisite: Решение маслихата Костанайской области от 20 апреля 2022 года № 172. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 апреля 2022 года № 27716
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников
  kaz: Жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-20
approved_by:
- '162000000002'
version_date:
  kaz: 2022-04-20
  rus: 2022-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/166896/kaz/20.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166896/rus/20.04.2022
